/**
 * Seed bookmark data imported from Raindrop.io CSV export.
 * Used by personalSeedData.ts to populate bookmark entities.
 */

import type { SeedEntity } from './personalSeedData'

interface BookmarkInput {
  title: string
  url: string
  excerpt?: string
  cover?: string
  folder?: string
  created: string
  pinned?: boolean
}

function domainOf(url: string): string {
  try { return new URL(url).hostname.replace(/^www\./, '') } catch { return '' }
}

function folderToTags(folder?: string): string[] {
  if (!folder || folder === 'Unsorted') return []
  return folder.split(' / ').map(s => s.toLowerCase().replace(/\s+/g, '-'))
}

function folderToCategory(folder?: string): 'work' | 'personal' {
  if (folder?.startsWith('Projects')) return 'work'
  return 'personal'
}

function buildBookmark(input: BookmarkInput, index: number): SeedEntity {
  const domain = domainOf(input.url)
  return {
    id: `bm-${index}`,
    type: 'bookmark',
    title: input.title || domain,
    description: '',
    startDate: input.created.split('T')[0],
    allDay: true,
    priority: 'low',
    urgency: 'not-urgent',
    priorityOverride: false,
    urgencyOverride: false,
    category: folderToCategory(input.folder),
    tags: folderToTags(input.folder),
    owner: 'you',
    involved: [],
    attachments: [],
    references: [],
    reminders: [],
    url: input.url,
    siteName: domain,
    favicon: domain ? `https://${domain}/favicon.ico` : '',
    thumbnail: input.cover || '',
    excerpt: input.excerpt || '',
    pinned: input.pinned || false,
  }
}

const BOOKMARKS: BookmarkInput[] = [
  { title: 'Servimatt Frontend Engineer', url: 'https://talentneural.com/careers/servimatt/frontend-engineer/assessment/', excerpt: 'Welcome to the Frontend Engineer assessment for Servimatt. Submit your answers and get notified instantly.', cover: 'https://talentneural.com/media/job_og_images/servimatt_cover.jpeg', folder: 'Unsorted', created: '2025-10-16T02:29:42.189Z' },
  { title: 'Sisters Gulassa — Pattern Observer', url: 'https://www.patternobserver.directory/listing/sisters-gulassa.html', folder: 'Unsorted', created: '2025-10-14T16:57:02.800Z' },
  { title: 'Login to your Canva account', url: 'https://www.canva.com/design/DAG1m9cit1s/2UDwqtVTAltYfCpGOztnpw/edit', excerpt: 'Login to access and create your next design.', cover: 'https://static.canva.com/domain-assets/canva/static/images/fb_cover-1.jpg', folder: 'Unsorted', created: '2025-10-13T04:19:28.347Z' },
  { title: 'Startup Pitches', url: 'https://www.youtube.com/@startup_pitches', excerpt: 'Are you passionate about entrepreneurship and innovation? Do you want to learn from successful startup founders, discover the next big thing, or get inspired for your own business ventures?', cover: 'https://yt3.googleusercontent.com/ytc/AIdro_kRdiwgGASa43GPYT-c3Z6MApteJOGOBXuLd7u6TpOt2CJm9iQ6p6u16RMmQYwe-Tke3g=s900-c-k-c0x00ffffff-no-rj', folder: 'Unsorted', created: '2025-10-12T18:55:09.462Z' },
  { title: 'AYOA®', url: 'https://www.youtube.com/@AYOA_Official', excerpt: 'AYOA is an all-in-one visual workspace that combines organic mind mapping, task management and team collaboration in a single intuitive platform.', cover: 'https://yt3.googleusercontent.com/THYvj0iHtzRZPlOdixGLskF8ABdQS8una_NI69qAtBBLHs5t2dJ8MOG8oxHtu8noTJKUb4Jqkw=s900-c-k-c0x00ffffff-no-rj', folder: 'Unsorted', created: '2025-10-12T13:33:57.028Z' },
  { title: 'Marksharp', url: 'https://www.marksharp.co/', cover: 'https://images.squarespace-cdn.com/content/v1/658a8f7c97333d2666a95d5d/d512f8c4-33c3-442e-b729-9b241cde1839/MarkSharpLogoGreen.png', folder: 'Unsorted', created: '2025-10-12T03:45:19.761Z' },
  { title: 'From Struggles to Success: The Life of Shahid Bolsen', url: 'https://shahidkingbolsen.org/biography/', excerpt: 'Discover the unique story of Shahid Bolsen, from his struggles as a child to his rise as a Muslim public intellectual.', cover: 'https://shahidkingbolsen.org/wp-content/uploads/2023/10/images.jpeg', folder: 'Unsorted', created: '2025-10-09T02:16:57.043Z' },
  { title: '852 Hz Pure Tone - 10 Hours - Inner Strength', url: 'https://www.youtube.com/watch?v=7wAb8_STOs4', excerpt: 'Solfeggio Frequency 852 Hz: it awakens inner strength, intuition, raises energy at cellular level.', cover: 'https://i.ytimg.com/vi/7wAb8_STOs4/maxresdefault.jpg', folder: 'Unsorted', created: '2025-10-07T06:54:31.160Z' },
  { title: 'LIONMILK LIVE AT SPECTRA (SOFTCORE SET)', url: 'https://www.youtube.com/watch?v=lGqTD9ocDaA', excerpt: 'RECORDED 5/25/25 AT SPECTRA STUDIO LOS ANGELES', cover: 'https://i.ytimg.com/vi/lGqTD9ocDaA/maxresdefault.jpg', folder: 'Unsorted', created: '2025-10-06T06:38:03.186Z' },
  { title: 'Makers studio podcast', url: 'https://www.pinterest.com/matthewrmanning/makers-studio-podcast/', folder: 'Unsorted', created: '2025-09-29T22:21:21.222Z' },
  { title: 'Earth\'s Ohm, 7.83 Hz Deep Theta Binaural Beat (Schumann Resonance)', url: 'https://www.youtube.com/watch?v=BJ9pkEiI4OQ&t=5352s', cover: 'https://i.ytimg.com/vi/BJ9pkEiI4OQ/maxresdefault.jpg', folder: 'Unsorted', created: '2025-09-20T08:58:26.452Z' },
  { title: 'Sitemap index — Media Burn', url: 'https://mediaburn.org/sitemap_index.xml', folder: 'Unsorted', created: '2025-09-19T08:03:06.423Z' },
  { title: 'GRAND Stack Explained | GraphQL, React, Apollo, Neo4j', url: 'https://www.youtube.com/watch?v=YD0UkFrPpB0', cover: 'https://i.ytimg.com/vi/YD0UkFrPpB0/maxresdefault.jpg', folder: 'Unsorted', created: '2025-09-18T23:44:09.131Z' },
  { title: 'Marcello Italian Made Mens Sweater | Depop', url: 'https://www.depop.com/products/journeydreamer-marcello-italian-made-mens-sweater-3d80/', cover: 'https://media-photos.depop.com/b1/35341997/2786570331_3fe67b04570343bf8fa079c8891b98bf/P0.jpg', folder: 'Unsorted', created: '2025-09-18T22:48:52.144Z' },
  { title: 'Every Noise at Once — Polish Contemporary Classical', url: 'https://everynoise.com/engenremap-polishcontemporaryclassical.html', folder: 'Unsorted', created: '2025-09-14T06:28:06.644Z' },
  { title: 'VS Code — Introducing Spec Kit for Spec-Driven Development', url: 'https://www.youtube.com/watch?v=DTw9X7MtU5s', cover: 'https://i.ytimg.com/vi/DTw9X7MtU5s/maxresdefault.jpg', folder: 'Unsorted', created: '2025-09-08T03:49:06.054Z' },
  { title: 'Get Started — Svelte | IMG.LY Docs', url: 'https://img.ly/docs/cesdk/svelte/get-started/overview-e18f40/', excerpt: 'Documentation for Get Started', cover: 'https://img.ly/docs/cesdk/opengraph_docs.png', folder: 'Unsorted', created: '2025-09-07T20:31:12.608Z' },
  { title: 'TikTok Studio', url: 'https://www.tiktok.com/tiktokstudio/content', excerpt: 'The TikTok Studio is a web-based comprehensive tool to support creators growing their channel and follower base.', folder: 'Unsorted', created: '2025-09-05T17:13:44.147Z' },
  { title: 'Pexels API Documentation', url: 'https://www.pexels.com/api/documentation/#videos-search', excerpt: 'Free high quality photos you can use everywhere. Free for commercial use. No attribution required.', cover: 'https://static.pexels.com/0/assets/pexels-stock-photos-6c3d5eb0cbed47e1bdf44ff85ebd9cd4669f50b895b3c6e76a23a4fd43852099.jpg', folder: 'Unsorted', created: '2025-09-05T11:00:02.407Z' },
  { title: 'Export Media Library (WordPress)', url: 'https://wordpress.org/plugins/export-media-library/', excerpt: 'Allows users to export media library files as a compressed zip archive.', folder: 'Unsorted', created: '2025-09-04T05:11:17.981Z' },
  { title: 'PageSpeed Insights', url: 'https://pagespeed.web.dev/', folder: 'Unsorted', created: '2025-09-04T03:01:06.463Z' },
  { title: 'Shippo Integration Paths', url: 'https://docs.goshippo.com/docs/guides_general/integration_paths/', excerpt: 'The shipping layer of the internet.', folder: 'Unsorted', created: '2025-09-02T08:52:39.765Z' },
  { title: 'Working with the Webflow CMS API', url: 'https://developers.webflow.com/data/docs/working-with-the-cms', excerpt: 'Explore the complete guide to Webflow\'s CMS API, including prerequisites, code snippets, and examples.', folder: 'Unsorted', created: '2025-09-02T08:16:36.680Z' },
  { title: 'Build An Agent in 10 mins with AI SDK 5', url: 'https://www.youtube.com/watch?v=TjAbtsPC-Sw', cover: 'https://i.ytimg.com/vi/TjAbtsPC-Sw/maxresdefault.jpg', folder: 'Unsorted', created: '2025-09-02T08:06:58.126Z' },
  { title: 'SyncedStore — Svelte integration', url: 'https://syncedstore.org/docs/svelte/', excerpt: 'SyncedStore works seamlessly together with Svelte Stores.', folder: 'Unsorted', created: '2025-09-02T02:23:14.563Z' },
  { title: 'CRDT projects — Best of JS', url: 'https://bestofjs.org/projects?tags=crdt', excerpt: '11 projects tagged with "CRDT": AFFiNE, Yjs, Gun, Automerge, PartyKit, BlockSuite, Fluid Framework, TinyBase...', cover: 'https://bestofjs.org/api/og/projects/', folder: 'Unsorted', created: '2025-08-31T11:45:37.246Z' },
  { title: 'LaunchCode', url: 'https://www.launchcode.org/', excerpt: 'A nonprofit organization helping people learn to code, land a job, or hire tech talent.', cover: 'https://www.launchcode.org/assets/launchcode-mission-cfde5ab27b990682b1e3ad8b5b2c13e2632440c7a67c88ef28d39a6d0a114626.png', folder: 'Unsorted', created: '2025-08-31T05:48:19.649Z' },
  { title: 'PocketHost', url: 'https://pockethost.io/docs/server-side-pocketbase-antipattern', excerpt: 'Get a PocketBase backend for your next app in under 10 seconds.', cover: 'https://pockethost.io/newPoster.png', folder: 'Unsorted', created: '2025-08-29T02:36:41.235Z' },
  { title: 'Audible Library', url: 'https://www.audible.com/library/titles', folder: 'Unsorted', created: '2025-08-28T08:43:28.205Z' },
  { title: 'Leetcode 75', url: 'https://leetcode.com/studyplan/leetcode-75/', folder: 'Unsorted', created: '2025-08-19T17:43:52.567Z' },
  { title: 'JavaScript Date cheatsheet', url: 'https://devhints.io/js-date', excerpt: 'The one-page guide to JavaScript Date: usage, examples, links, snippets, and more.', cover: 'https://assets.devhints.io/previews/js-date.jpg', folder: 'Unsorted', created: '2025-08-19T02:24:01.463Z' },
  { title: 'How to articulate your thoughts more clearly', url: 'https://www.youtube.com/watch?v=JHmAS4q-GqY', cover: 'https://i.ytimg.com/vi/JHmAS4q-GqY/maxresdefault.jpg', folder: 'Unsorted', created: '2025-08-11T03:32:55.630Z' },
  { title: 'Spatial audio in the Web Audio API', url: 'https://www.youtube.com/watch?v=vwPtGYgRytc', cover: 'https://i.ytimg.com/vi/vwPtGYgRytc/maxresdefault.jpg', folder: 'Unsorted', created: '2025-08-10T22:56:41.649Z' },
  { title: 'PartyKit — Cave Folks', url: 'https://cave-folks.trentbrew.partykit.dev/#/flow', excerpt: 'Everything\'s better with friends!', folder: 'Unsorted', created: '2025-08-10T21:53:19.894Z' },
  { title: 'Custom Nodes — React Flow', url: 'https://reactflow.dev/learn/customization/custom-nodes', excerpt: 'Custom nodes in React Flow are just React components.', cover: 'https://reactflow.dev/opengraph-image.jpg', folder: 'Unsorted', created: '2025-08-08T01:15:04.641Z' },
  { title: 'Jazz — Whip up an app', url: 'https://jazz.tools/', excerpt: 'Jazz gives you data without needing a database — plus auth, permissions, files and multiplayer without needing a backend.', cover: 'https://jazz.tools/opengraph-image', folder: 'Unsorted', created: '2025-08-07T10:18:41.787Z' },
  { title: 'Man-Computer Symbiosis', url: 'https://groups.csail.mit.edu/medg/people/psz/Licklider.html', folder: 'Unsorted', created: '2025-08-07T04:34:03.353Z' },
  { title: 'ComfyUI — Generate video, images, 3D, audio with AI', url: 'https://www.comfy.org/careers', excerpt: 'The most powerful and modular visual AI application and engine', cover: 'https://framerusercontent.com/images/0BcAr9INx6VHF0VtAXa30RHfqPo.png', folder: 'Unsorted', created: '2025-08-04T08:42:04.340Z' },
  { title: 'Claudia', url: 'https://claudiacode.com/', excerpt: 'Transform your AI coding workflow with a beautiful GUI that makes managing Claude sessions effortless.', cover: 'https://claudiacode.com/og-image.jpg', folder: 'Unsorted', created: '2025-08-04T01:57:33.503Z' },
  { title: 'Stripe Connect: Separate Charges and Transfers', url: 'https://www.youtube.com/watch?v=Wn9YrnLnPz4', cover: 'https://i.ytimg.com/vi/Wn9YrnLnPz4/maxresdefault.jpg', folder: 'Unsorted', created: '2025-08-01T20:34:21.983Z' },
  { title: 'Mux — Video streaming APIs', url: 'https://www.mux.com/', excerpt: 'The most cost-effective video infrastructure for businesses of all scale.', folder: 'Unsorted', created: '2025-08-01T11:16:35.670Z' },
  { title: 'Founders Running Club :: LA', url: 'https://lu.ma/h239sht3', cover: 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=2,anim=false,background=white,quality=75,width=500,height=500/event-covers/gn/b5a27111-3d74-4e0c-be0e-f3031e7a23cc.jpg', folder: 'Unsorted', created: '2025-08-01T02:21:08.097Z' },
  { title: 'Discover Events — Luma', url: 'https://lu.ma/discover', excerpt: 'Discover popular events in your city and featured calendars from the community.', cover: 'https://images.lumacdn.com/social-images/discover-social.png', folder: 'Unsorted', created: '2025-08-01T02:19:09.245Z' },
  { title: 'Santa Barbara Apartments — Rancho Cucamonga', url: 'https://www.lewisapartments.com/santa-barbara-apartments-rancho-cucamonga-ca/floorplans', excerpt: 'We offer 1, 2, 3, & 4 bedroom houses for rent in Rancho Cucamonga.', folder: 'Unsorted', created: '2025-07-30T18:12:21.095Z' },
  { title: 'VSEDC', url: 'https://vsedc.org/', excerpt: 'VSEDC empowers South LA by offering business coaching, lending, financing, training, education, networking, incubation, and access to technology.', cover: 'https://vsedc.org/wp-content/uploads/2024/05/vermont-slauson-economic-development-corporation-1024x683.jpg', folder: 'Unsorted', created: '2025-07-22T23:05:11.258Z' },
  { title: 'The Only Embedding Model You Need for RAG', url: 'https://www.youtube.com/watch?v=p7yRLIj9IyQ', cover: 'https://i.ytimg.com/vi/p7yRLIj9IyQ/maxresdefault.jpg', folder: 'Unsorted', created: '2025-07-21T17:25:05.104Z' },
  { title: 'Snowfall | P-Stream', url: 'https://pstream.mov/media/tmdb-tv-71694-snowfall/88329/1317084', cover: 'https://image.tmdb.org/t/p/original/eEXwPg7nIERmRHC1yJoBf3Q5C7k.jpg', folder: 'Unsorted', created: '2025-07-21T08:36:00.416Z' },
  { title: 'Navy Federal Customer Portal', url: 'https://nfcu.my.site.com/NPORTAL__Portal', folder: 'Unsorted', created: '2025-07-04T00:38:08.344Z' },
  { title: 'Figma — Browser Concept', url: 'https://embed.figma.com/design/vxEq0BTJBjcH0mbcbrROWb/Browser-Concept', folder: 'Unsorted', created: '2025-06-26T02:29:42.552Z' },
  { title: 'Events | Markwhen Documentation', url: 'https://docs.markwhen.com/syntax/events.html', folder: 'Unsorted', created: '2025-06-24T23:54:31.641Z' },
  { title: 'Zero — Open Source Email', url: 'https://0.email/mail/inbox', excerpt: 'Experience email the way you want with 0 - the first open source email app that puts your privacy and safety first.', cover: 'https://0.email/og.png', folder: 'Unsorted', created: '2025-06-22T04:39:21.890Z' },
  { title: 'Animate UI', url: 'https://animate-ui.com/docs', excerpt: 'Use Animate UI components to animate your pages.', cover: 'https://animate-ui.com/og-image.png', folder: 'Unsorted', created: '2025-06-22T00:53:44.424Z' },
  { title: 'InferenceWeb — Stanford KSL', url: 'http://www.ksl.stanford.edu/software/iw/Ex1/', folder: 'Unsorted', created: '2025-06-20T10:58:10.487Z' },
  { title: 'Different Ways To Share State In Svelte 5', url: 'https://joyofcode.xyz/how-to-share-state-in-svelte-5', excerpt: 'Learn different ways you can export and share reactive state in Svelte 5.', cover: 'https://social-share-images.vercel.app/Different%20Ways%20To%20Share%20State%20In%20Svelte%205.png', folder: 'Unsorted', created: '2025-06-19T10:46:05.883Z' },
  { title: 'JSON-LD Playground', url: 'https://json-ld.org/playground/', folder: 'Unsorted', created: '2025-06-18T04:45:55.595Z' },
  { title: 'client-vector-search', url: 'https://github.com/yusufhilmi/client-vector-search', excerpt: 'A client side vector search library that can embed, store, search, and cache vectors. Works on the browser and node.', cover: 'https://opengraph.githubassets.com/5c9554b08b90aa8e0422ae4b355bd5dbc8508906297112838ac8e9bfdbf0a230/yusufhilmi/client-vector-search', folder: 'Unsorted', created: '2025-06-15T04:43:13.969Z' },
  { title: 'X6tf5n — CodeSandbox', url: 'https://codesandbox.io/p/devbox/x6tf5n', folder: 'Unsorted', created: '2025-06-15T04:42:43.020Z' },
  { title: 'BonBon Browser', url: 'https://github.com/BonBon-exchange/bonbon-browser', cover: 'https://opengraph.githubassets.com/93784f9e79b1eb84742387fd8928314c55e7c14d484db577e269987d797592ef/BonBon-exchange/bonbon-browser', folder: 'Unsorted', created: '2025-06-15T01:07:35.333Z' },
  { title: 'SWISH — SWI-Prolog for SHaring', url: 'https://swish.swi-prolog.org/', folder: 'Unsorted', created: '2025-06-15T01:07:14.020Z' },
  { title: 'Zyphra Playground', url: 'https://playground.zyphra.com/sign-in', folder: 'Unsorted', created: '2025-06-12T09:06:13.855Z' },
  { title: 'JSR: the JavaScript Registry', url: 'https://jsr.io/', excerpt: 'JSR is the open-source package registry for modern JavaScript. JSR natively supports TypeScript.', cover: 'https://jsr.io/images/og-image.webp', folder: 'Unsorted', created: '2025-06-12T08:48:47.836Z' },
  { title: 'The Power of Prolog', url: 'https://www.metalevel.at/prolog', excerpt: 'Introduction to modern Prolog', folder: 'Unsorted', created: '2025-06-12T08:39:22.878Z' },
  { title: 'SLED Contract Opportunities', url: 'https://www.highergov.com/sl/contract-opportunity/', excerpt: 'Search over one million state, local, and educational contract solicitations.', folder: 'Unsorted', created: '2025-06-11T02:32:01.569Z' },
  { title: '541511 Bids, RFP & Government Contracts', url: 'https://www.instantmarkets.com/q/541511', cover: 'https://d3ot3obhbewajn.cloudfront.net/dist/browser/assets/instantmarkets_square_1200x1200.png', folder: 'Unsorted', created: '2025-06-11T02:04:27.440Z' },
  { title: 'Localbase — Firebase-Style Database Offline', url: 'https://github.com/samuk190/localbase', cover: 'https://opengraph.githubassets.com/dbbc75b2ad7cc642574bb40646d4a5d04b666f542378f4844040ca7c2b1d4b2b/samuk190/localbase', folder: 'Unsorted', created: '2025-06-10T06:36:05.039Z' },
  { title: 'TerminusCMS | Jamstack', url: 'https://jamstack.org/headless-cms/terminuscms/', excerpt: 'TerminusCMS is a dev-first headless content management system.', folder: 'Unsorted', created: '2025-06-08T11:20:59.524Z' },
  { title: 'TerminusCMS', url: 'https://terminusdb.com/terminuscms/', folder: 'Unsorted', created: '2025-06-08T11:18:39.494Z' },
  { title: 'Install the TerminusDB JavaScript Client', url: 'https://terminusdb.org/docs/install-terminusdb-js-client/', excerpt: 'Installation instruction for the TerminusDB JavaScript Client', cover: 'https://assets.terminusdb.com/docs/technical-documentation-terminuscms-og.png', folder: 'Unsorted', created: '2025-06-08T11:17:41.886Z' },
  { title: 'It\'s the Language of AI — So Why Doesn\'t AI Use Prolog?', url: 'https://www.youtube.com/watch?v=4qJVzOl4wWk', cover: 'https://i.ytimg.com/vi/4qJVzOl4wWk/maxresdefault.jpg', folder: 'Unsorted', created: '2025-06-08T11:05:46.113Z' },
  { title: 'Prolog — Wikipedia', url: 'https://en.wikipedia.org/wiki/Prolog', folder: 'Unsorted', created: '2025-06-08T11:05:41.295Z' },
  { title: 'ImageKit Dashboard', url: 'https://imagekit.io/dashboard', excerpt: 'Login to Imagekit dashboard. Manage your images effortlessly.', folder: 'Unsorted', created: '2025-06-07T22:52:52.996Z' },
  { title: 'Zyphra Playground — Audio', url: 'https://playground.zyphra.com/audio', folder: 'Unsorted', created: '2025-06-07T20:30:30.552Z' },
  { title: 'GSAP Cheatsheet', url: 'https://gsap.com/cheatsheet/', folder: 'Unsorted', created: '2025-06-07T18:09:53.299Z' },
  { title: 'Mighty Networks — 3 Minute Tour', url: 'https://www.youtube.com/watch?v=KohkszOmlHc', cover: 'https://i.ytimg.com/vi/KohkszOmlHc/hqdefault.jpg', folder: 'Unsorted', created: '2025-06-06T11:17:03.708Z' },
  { title: 'Mighty Networks', url: 'https://www.mightynetworks.com/', excerpt: 'The MOST $1M communities created. Ranked #1 community platform on G2.', cover: 'https://images.ctfassets.net/m9n8o4ceoyuw/3Oe871ww60CDt3yYp4ULpd/79f825735315319e3e163e08e9cd548d/image__37___1_.png', folder: 'Unsorted', created: '2025-06-06T03:57:16.088Z' },
  { title: 'Zustand — Bear necessities for state management', url: 'https://github.com/pmndrs/zustand', cover: 'https://repository-images.githubusercontent.com/180328715/fca49300-e7f1-11ea-9f51-cfd949b31560', folder: 'Unsorted', created: '2025-06-06T03:30:11.392Z' },
  { title: 'Firecrawl', url: 'https://www.firecrawl.dev/', excerpt: 'Turn any website into LLM-ready data.', cover: 'https://www.firecrawl.dev/og.png', folder: 'Unsorted', created: '2025-06-06T01:30:16.483Z' },
  { title: 'Codebase to Tutorial', url: 'https://code2tutorial.com/', excerpt: 'Generate easy to follow tutorials from GitHub codebases with AI', folder: 'Unsorted', created: '2025-06-05T03:52:57.899Z' },
  { title: 'Origin UI Vue', url: 'https://originui-vue.pages.dev/dialogs', folder: 'Unsorted', created: '2025-06-03T01:32:51.194Z' },
  { title: 'Reka UI', url: 'https://reka-ui.com/docs/components/checkbox', excerpt: 'An open-source library with unstyled, primitive components.', cover: 'https://reka-ui.com/docs/og.jpg', folder: 'Unsorted', created: '2025-06-03T01:21:54.459Z' },
  { title: 'Building data-centric apps with a reactive relational database', url: 'https://riffle.systems/essays/prelude/', excerpt: 'Storing all application and UI state in a client-side reactive relational database.', cover: 'https://riffle.systems/assets/essays/prelude/reactive.png', folder: 'Unsorted', created: '2025-06-02T17:15:52.652Z' },
  { title: 'Riffle Systems — Essays', url: 'https://riffle.systems/essays', folder: 'Unsorted', created: '2025-06-02T17:15:20.981Z' },
  { title: 'An introduction to CRDTs', url: 'https://www.youtube.com/watch?v=gZP2VUmH05A', cover: 'https://i.ytimg.com/vi/gZP2VUmH05A/maxresdefault.jpg', folder: 'Unsorted', created: '2025-06-02T16:59:07.238Z' },
  { title: 'Polymarket', url: 'https://polymarket.com/', excerpt: 'The world\'s largest prediction market.', cover: 'https://polymarket.com/images/homepage-twitter-card.png', folder: 'Unsorted', created: '2025-06-02T13:48:14.507Z' },
  { title: 'TheHiddenOne', url: 'https://the-hidden-servant.blogspot.com/', folder: 'Unsorted', created: '2025-06-02T10:33:03.169Z' },
  { title: 'vue-ganttastic', url: 'https://github.com/zunnzunn/vue-ganttastic', excerpt: 'Simple, interactive and highly customizable Gantt chart component for Vue 3', cover: 'https://repository-images.githubusercontent.com/247787309/c42eb980-6adb-11ea-9257-8f76cbcf69ae', folder: 'Unsorted', created: '2025-06-01T08:47:24.536Z' },
  { title: 'LiveStore', url: 'https://livestore.dev/', excerpt: 'LiveStore is a state management framework based on SQLite and event-sourcing.', cover: 'https://livestore.dev/opengraph-image.jpg', folder: 'Unsorted', created: '2025-05-31T21:21:56.288Z' },
  { title: 'Rombo — Animation library for Tailwind CSS', url: 'https://rombo.co/tailwind/', folder: 'Unsorted', created: '2025-05-31T12:31:32.625Z' },
  { title: 'Crafted — Pasquale Vitiello & Davide Pacilio', url: 'https://crafted.is/', excerpt: 'A showcase of beautiful designed app UIs.', cover: 'https://crafted.is/opengraph-image.png', folder: 'Unsorted', created: '2025-05-31T10:22:14.084Z' },
  { title: 'Schema Visualizer — UI Thing', url: 'https://ui-thing.behonbaker.com/examples/schema-visualizer', excerpt: 'A schema visualizer created with Vue Flow.', folder: 'Unsorted', created: '2025-05-31T10:03:55.992Z' },
  { title: 'Kipling Apartments — Los Angeles', url: 'https://www.zillow.com/apartments/los-angeles-ca/kipling-apartments/CmCN7j/', cover: 'https://photos.zillowstatic.com/fp/1c062939dc3836c11aa1e4d485d52099-cc_ft_384.webp', folder: 'Unsorted', created: '2025-05-31T00:51:37.304Z' },
  { title: 'Huly', url: 'https://huly.app/workbench/turtlelabs/card', folder: 'Unsorted', created: '2025-05-25T15:01:54.356Z' },
  { title: 'λ-2D: Drawing as Programming Language — MIT Media Lab', url: 'https://www.media.mit.edu/projects/2d-an-exploration-of-drawing-as-programming-language-featuring-ideas-from-lambda-calculus/overview/', cover: 'https://dam-prod2.media.mit.edu/thumb/2022/04/02/PXL_20220302_203150013.jpg.1400x1400.jpg', folder: 'Unsorted', created: '2025-05-25T12:28:07.341Z' },
  { title: 'The Svelte feature you\'re sleeping on...', url: 'https://www.youtube.com/watch?v=kMBDsyozllk', cover: 'https://i.ytimg.com/vi/kMBDsyozllk/maxresdefault.jpg', folder: 'Unsorted', created: '2025-05-22T23:22:55.433Z' },
  { title: 'PocketBase — Turtle', url: 'https://turtle.pockethost.io/_/#/collections', folder: 'Unsorted', created: '2025-05-22T22:52:54.517Z' },
  { title: 'PocketHost — JS Docs', url: 'https://pockethost.io/docs/js', excerpt: 'Get a PocketBase backend for your next app in under 10 seconds.', cover: 'https://pockethost.io/poster.png', folder: 'Unsorted', created: '2025-05-21T22:34:38.511Z' },
  { title: 'Wabi GPT', url: 'https://chatgpt.com/g/g-A1OHJVG9k-wabi', folder: 'Unsorted', created: '2025-05-21T05:42:54.727Z' },
  { title: 'Vox GIFs on GIPHY', url: 'https://giphy.com/voxdotcom/', cover: 'https://media0.giphy.com/media/VfEJqkWpsEbF2Wqdmb/giphy.gif', folder: 'Unsorted', created: '2025-05-21T04:04:32.420Z' },
  { title: 'Linear — YouTube Playlist', url: 'https://www.youtube.com/watch?v=VcwhJaV6ZYs&list=PLP9v0Y4zla9vkQMGvpj2KNuRIefy0HaR2', folder: 'Unsorted', created: '2025-05-20T22:53:05.541Z' },
  { title: '21st.dev — Grid Motion', url: 'https://21st.dev/DavidHDev/grid-motion/default', cover: 'https://21st.dev/DavidHDev/grid-motion/default/opengraph-image', folder: 'Unsorted', created: '2025-05-19T04:46:08.015Z' },
  { title: 'arXiv.org', url: 'https://arxiv.org/', folder: 'Unsorted', created: '2025-05-19T01:28:53.731Z' },
  { title: 'NoCodeXport', url: 'https://nocodexport.com/tools', excerpt: 'Free you from the shackles of NoCode Website Builders', cover: 'https://nocodexport.com/og-image.png', folder: 'Unsorted', created: '2025-05-16T23:04:39.831Z' },
  { title: 'a16z speedrun', url: 'https://speedrun.a16z.com/', excerpt: 'Where startups gain the power to scale.', cover: 'https://cdn.sanity.io/images/tzetulnq/production/9980438b30f7722c01ea83f9e82699761732dfba-1920x1080.png', folder: 'Unsorted', created: '2025-05-13T01:35:36.849Z' },
  { title: 'Google Cloud Platform — Nodebook', url: 'https://console.cloud.google.com/welcome', folder: 'Unsorted', created: '2025-05-12T05:20:44.536Z' },
  { title: 'Theia AI IDE — An IDE That Thinks With You', url: 'https://www.youtube.com/watch?v=Cz9Rh9jVHz4', cover: 'https://i.ytimg.com/vi/Cz9Rh9jVHz4/maxresdefault.jpg', folder: 'Unsorted', created: '2025-05-11T03:54:09.710Z' },
  { title: 'Techstars Entrepreneur\'s Toolkit', url: 'https://toolkit.techstars.com/', excerpt: 'An online educational resource to help you learn the fundamentals of entrepreneurship.', cover: 'https://toolkit.techstars.com/hubfs/Techstars%20Toolkit%20Featured%20Image-cropped.png', folder: 'Unsorted', created: '2025-05-11T03:51:28.421Z' },
  { title: 'YC Startup Library', url: 'https://www.ycombinator.com/library/', excerpt: 'YC\'s library of startup advice: essays and videos that teach you how to start a company.', cover: 'https://www.ycombinator.com/assets/ycdc/yc-og-image-0cfa80cac837d64d9b4f0705950000b66906ac032791376bd721f246fafcc7b4.png', folder: 'Unsorted', created: '2025-05-11T03:50:49.115Z' },
  { title: 'Code With Antonio', url: 'https://www.codewithantonio.com/', excerpt: 'Build something great!', cover: 'https://codewithantonio.com//og.png', folder: 'Unsorted', created: '2025-05-10T06:51:36.843Z' },
  { title: 'YouTube Video Summarizer — NoteGPT', url: 'https://notegpt.io/youtube-video-summarizer', excerpt: 'Get free transcripts and subtitles for YouTube videos online.', folder: 'Unsorted', created: '2025-05-09T13:45:22.307Z' },
  { title: '21st.dev — Parallax Floating', url: 'https://21st.dev/danielpetho/parallax-floating/default', cover: 'https://21st.dev/danielpetho/parallax-floating/default/opengraph-image', folder: 'Unsorted', created: '2025-05-09T09:13:03.685Z' },
  { title: '21st.dev — Hero Section', url: 'https://21st.dev/meschacirung/hero-section-5/default', cover: 'https://21st.dev/meschacirung/hero-section-5/default/opengraph-image', folder: 'Unsorted', created: '2025-05-09T09:12:48.329Z' },
  { title: '21st.dev — Gooey Filter', url: 'https://21st.dev/danielpetho/gooey-filter/background', cover: 'https://21st.dev/danielpetho/gooey-filter/background/opengraph-image', folder: 'Unsorted', created: '2025-05-09T09:12:27.204Z' },
  { title: '21st.dev — Hero Components', url: 'https://21st.dev/s/hero', folder: 'Unsorted', created: '2025-05-09T09:08:16.554Z' },
  { title: 'Launch UI — Shadcn Templates', url: 'https://www.shadcntemplates.com/theme/launch-ui-launch-ui/', cover: 'https://www.shadcntemplates.com/images/theme/thumbnail/launch-ui-launch-ui-thumbnail-2x.webp', folder: 'Unsorted', created: '2025-05-09T08:41:07.918Z' },
  { title: 'Fullscreen auto-scroll with easing — CodePen', url: 'https://codepen.io/tbrew1023/pen/XWymovW', cover: 'https://shots.codepen.io/username/pen/XWymovW-800.jpg', folder: 'Unsorted', created: '2025-05-09T08:40:51.339Z' },
  { title: 'Grida Canvas', url: 'https://grida.co/canvas', folder: 'Unsorted', created: '2025-05-09T08:29:20.189Z' },
  { title: 'Build a Slack clone — Code With Antonio', url: 'https://www.codewithantonio.com/projects/slack-clone', cover: 'https://utfs.io/f/0a80a056-c4b7-47fd-942c-c09e7f50593d-1vu9za.png', folder: 'Unsorted', created: '2025-05-09T06:44:29.312Z' },
  { title: 'Google Cloud Platform — Academic Atlas', url: 'https://console.cloud.google.com/auth/audience', folder: 'Unsorted', created: '2025-05-08T06:43:16.986Z' },
  { title: 'Why and how we do work trials at Linear', url: 'https://linear.app/blog/why-and-how-we-do-work-trials-at-linear', excerpt: 'Learn why and how Linear uses paid work trials to evaluate candidates.', cover: 'https://webassets.linear.app/images/ornj730p/production/fdaac1d4b554aa28b3c8a83e1420a3be07554f77-4800x2512.webp', folder: 'Unsorted', created: '2025-05-07T22:00:25.552Z' },
  { title: 'ChatGPT — Jean Froggo', url: 'https://chatgpt.com/g/g-4igzzK0kw-jean-froggo', excerpt: 'An art critic with a gift for seeing the soul in art and people.', folder: 'Unsorted', created: '2025-05-07T20:32:29.277Z' },
  { title: 'Jitter — Social Media Showreel', url: 'https://jitter.video/file/?id=AFtZOWEDHuoM4gvuqlEJhe4y', cover: 'https://jitter.video/static/homepage-2025-9e6e31916ac6440c60bf616b81500c31.png', folder: 'Unsorted', created: '2025-05-07T13:07:06.781Z' },
  { title: 'Searchable Database — The SFU', url: 'https://research.solutionfocusedbrieftherapy.com/searchable-database/', folder: 'Unsorted', created: '2025-05-07T11:41:13.917Z' },
  { title: 'Quality — Linear', url: 'https://linear.app/quality', excerpt: 'What is quality? And how do things of quality get built?', cover: 'https://linear.app/static/og/quality.jpg', folder: 'Unsorted', created: '2025-05-07T05:19:30.479Z' },
  { title: 'Movies / TV / Anime — FMHY', url: 'https://fmhy.net/videopiracyguide', folder: 'Unsorted', created: '2025-05-04T08:23:35.602Z' },
  { title: 'Paradigm AI', url: 'https://app.paradigmai.com/home', folder: 'Unsorted', created: '2025-04-23T08:49:51.983Z' },
  { title: 'CANALS — By Marcus Brown & Aristide Benoist', url: 'https://canals-amsterdam.com/', excerpt: 'A visual glimpse into the creation and history of the iconic Amsterdam canals.', cover: 'https://canals-amsterdam.com/og/1200-630.png', folder: 'Unsorted', created: '2025-04-22T06:00:39.408Z' },
  { title: 'Apply to ChainGPT Labs', url: 'https://labs.chaingpt.org/apply', excerpt: 'Have a promising Web3 project? Apply to ChainGPT Labs for incubation support.', cover: 'https://cdn.prod.website-files.com/664753c2515af09bef5b9826/67124894d2ee412412c4d91c_LABS_URL_preview.webp', folder: 'Unsorted', created: '2025-04-22T05:58:03.099Z' },
  { title: 'Mermaid Live Editor', url: 'https://mermaid.live/', excerpt: 'Open source Visio Alternative for generating charts from text via javascript.', cover: 'https://github.com/mermaid-js/mermaid/raw/develop/img/header.png', folder: 'Unsorted', created: '2025-04-22T02:47:17.341Z' },
  { title: 'Puck Editor', url: 'https://demo.puckeditor.com/edit', folder: 'Unsorted', created: '2025-04-19T13:27:35.979Z' },
  { title: 'AI News & Strategy Daily — Nate B Jones', url: 'https://www.youtube.com/@NateBJones', cover: 'https://yt3.googleusercontent.com/0Lng6uYeNunwTRPO0KSTfioIVcN84p1XlHfwhGwv9SYBFxofSkYZs3TSrratDvo2u-DoXZT68R4=s900-c-k-c0x00ffffff-no-rj', folder: 'Unsorted', created: '2025-04-19T07:40:09.849Z' },
  { title: 'Graph Explorer — Microsoft Graph', url: 'https://developer.microsoft.com/en-us/graph/graph-explorer', excerpt: 'Try the Graph Explorer developer tool to learn about Microsoft Graph APIs.', folder: 'Unsorted', created: '2025-04-16T19:56:33.080Z' },
  { title: 'Justfile Cheat Sheet', url: 'https://cheatography.com/linux-china/cheat-sheets/justfile/', excerpt: 'Just is a command runner.', cover: 'https://media.cheatography.com/storage/thumb/linux-china_justfile.600.jpg', folder: 'Unsorted', created: '2025-04-12T08:44:07.574Z' },
  { title: 'Adieu Sounds — Screenshot', url: 'https://adieusounds.com/cdn/shop/articles/Screen_Shot_2024-02-24_at_11.51.25_AM.png', folder: 'Unsorted', created: '2025-04-12T05:54:37.713Z' },
  { title: 'colorgram-js — Color extraction library', url: 'https://github.com/darosh/colorgram-js', cover: 'https://opengraph.githubassets.com/8de201167eadafc6ba9c57f2cacef391bde1e6b518b1c580c379e8c8b2c9c6b3/darosh/colorgram-js', folder: 'Unsorted', created: '2025-04-10T21:11:05.855Z' },
  { title: 'Tauri — Features & Recipes', url: 'https://v2.tauri.app/plugin/', excerpt: 'The cross-platform app building toolkit', cover: 'https://v2.tauri.app/og.png', folder: 'Unsorted', created: '2025-04-10T13:10:29.097Z' },
  { title: 'Tauri — Multiwindow', url: 'https://v1.tauri.app/v1/guides/features/multiwindow/', excerpt: 'Manage multiple windows on a single application.', cover: 'https://tauri.app/img/social.png', folder: 'Unsorted', created: '2025-04-10T12:31:18.471Z' },
  { title: 'tweakcn — Visual editor for shadcn/ui', url: 'https://github.com/jnsahaj/tweakcn', cover: 'https://opengraph.githubassets.com/b876e7a0784724abf7f3b19e0245fa55e277812db0f72bd03f6fc7e2561ef019/jnsahaj/tweakcn', folder: 'Unsorted', created: '2025-04-10T07:36:49.346Z' },
  { title: 'Trent Brew — UX Portfolio', url: 'https://trentbrew.github.io/ux-portfolio', folder: 'Unsorted', created: '2025-04-08T23:04:17.761Z' },
  { title: 'casey/just — Command runner', url: 'https://github.com/casey/just', cover: 'https://opengraph.githubassets.com/1b169feb54788928217d767e56d9ef885d649f6145166eec17cbad2fb1787ad4/casey/just', folder: 'Unsorted', created: '2025-04-08T17:28:57.123Z' },
  { title: 'ChatGPT — Daria', url: 'https://chatgpt.com/g/g-wbfoUANvp-daria/c/67f4dbb6-92e0-8010-a645-cbb7604f7b39', folder: 'Unsorted', created: '2025-04-08T10:23:36.636Z' },
  { title: 'Google Drive — Saves', url: 'https://drive.google.com/drive/folders/1G2gHYZn7Dbx_X9iYUgpOfCBiWCixBTWU', folder: 'Unsorted', created: '2025-04-08T06:54:19.806Z' },
  { title: 'MCP Servers', url: 'https://mcp.so/', excerpt: 'The largest collection of MCP Servers.', folder: 'Unsorted', created: '2025-04-08T06:46:01.599Z' },
  { title: 'Parallax — Motion for React', url: 'https://examples.motion.dev/react/parallax', cover: 'https://examples.motion.dev/social/react/parallax.png', folder: 'Unsorted', created: '2025-04-06T07:43:38.683Z' },
  { title: 'Motion Examples', url: 'https://examples.motion.dev/react', excerpt: 'Official examples of how to use Motion, including scroll animations, layout animations, keyframes, springs and more.', cover: 'https://examples.motion.dev/social/site.png', folder: 'Unsorted', created: '2025-04-06T06:59:04.301Z' },
  { title: 'pqoqubbw/icons — Beautifully crafted animated icons', url: 'https://icons.pqoqubbw.dev/', cover: 'https://icons.pqoqubbw.dev/_next/static/media/og.19d1954d.png', folder: 'Unsorted', created: '2025-04-06T06:56:20.906Z' },
  { title: 'Digitizing Field Notes inside Obsidian', url: 'https://www.youtube.com/watch?v=9T9VL8_i1Tg', cover: 'https://i.ytimg.com/vi/9T9VL8_i1Tg/maxresdefault.jpg', folder: 'Unsorted', created: '2025-04-06T06:18:03.942Z' },
  { title: 'hello world', url: 'https://www.youtube.com/watch?v=Yw6u6YkTgQ4', cover: 'https://i.ytimg.com/vi/Yw6u6YkTgQ4/hqdefault.jpg', folder: 'Unsorted', created: '2025-04-06T05:29:36.744Z' },
  { title: 'Optimize Your AI — Quantization Explained', url: 'https://www.youtube.com/watch?v=K75j8MkwgJ0', cover: 'https://i.ytimg.com/vi/K75j8MkwgJ0/maxresdefault.jpg', folder: 'Unsorted', created: '2025-04-06T04:05:40.461Z' },
  { title: 'webview_deno — Desktop GUIs for Deno', url: 'https://github.com/webview/webview_deno', cover: 'https://repository-images.githubusercontent.com/245254578/3b791d80-c830-11ea-8803-6012462de384', folder: 'Unsorted', created: '2025-04-06T02:57:51.015Z' },
  { title: 'Qwen Chat', url: 'https://chat.qwen.ai/', excerpt: 'Qwen Chat offers comprehensive functionality spanning chatbot, image and video understanding, image generation, and more.', folder: 'Unsorted', created: '2025-04-05T18:11:52.565Z' },
  { title: 'QvQ Max — FREE VISUAL REASONING AI MODEL', url: 'https://www.youtube.com/watch?v=QCk4rnf3LAg', cover: 'https://i.ytimg.com/vi/QCk4rnf3LAg/maxresdefault.jpg', folder: 'Unsorted', created: '2025-04-05T18:11:07.334Z' },
  { title: 'Manus AI', url: 'https://manus.im/login', folder: 'Unsorted', created: '2025-04-05T09:31:35.446Z' },
  { title: 'LLM Agents = Graphs!? — PocketFlow', url: 'https://www.youtube.com/watch?v=h3N1Lecptb0', cover: 'https://i.ytimg.com/vi/h3N1Lecptb0/maxresdefault.jpg', folder: 'Unsorted', created: '2025-04-03T09:53:54.224Z' },
  { title: 'Inkbase: Programmable Ink', url: 'https://www.inkandswitch.com/inkbase/', excerpt: 'What would be possible if hand-drawn sketches were programmable like spreadsheets?', cover: 'https://www.inkandswitch.com/inkbase/static/social-image--16x9--1024w.jpg', folder: 'Unsorted', created: '2024-03-22T16:50:22.905Z' },
  { title: 'LinkedIn Document', url: 'https://media.licdn.com/dms/document/media/D4D1FAQFW3fn6gMIUXw/feedshare-document-pdf-analyzed/0/1708625990256', folder: 'Unsorted', created: '2024-03-01T02:01:23.984Z' },
  { title: 'Notion — Projects', url: 'https://www.notion.so/trentbrew/Projects-c897348c92a24ae199f965653ef103c1', folder: 'Projects', created: '2024-01-18T23:03:16.623Z' },
  { title: 'Google Drive — KIA', url: 'https://drive.google.com/drive/u/0/folders/13RLU59sBcexhdFZune5u-bQilfUCtCtM', folder: 'Projects / Turtle / Clients / KIA', created: '2024-01-18T23:21:49.714Z' },
  { title: 'Home — Normal Studio', url: 'https://thenormalstudio.com/', folder: 'Projects / Turtle / Clients / KIA', created: '2024-01-18T23:21:41.944Z' },
  { title: 'kianijee.com', url: 'https://www.notion.so/kianijee-com-44f62e32c9ab4efd863c41f9e5197a56', folder: 'Projects / Turtle / Clients / KIA', created: '2024-01-18T23:21:32.458Z' },
  { title: 'LeadershipWise — Development & Design Contract', url: 'https://docs.google.com/document/d/1cedBpVlD45y16NVDQKQ8-mClLLNbebjqSS5n9XX03KE/edit', folder: 'Projects / Turtle / Clients / LW', created: '2024-01-18T23:21:08.712Z' },
  { title: 'LeadershipWise — Webflow', url: 'https://webflow.com/dashboard/login', folder: 'Projects / Turtle / Clients / LW', created: '2024-01-18T23:21:04.007Z' },
  { title: 'LeadershipWise', url: 'https://www.theleadershipwise.com/', cover: 'https://assets-global.website-files.com/65247c06612bd7502a2447a9/653cf33311e1dd3cc2b4d14e_alpha.png', folder: 'Projects / Turtle / Clients / LW', created: '2024-01-18T23:20:51.751Z' },
  { title: 'leadershipwise.com — Notion', url: 'https://www.notion.so/trentbrew/leadershipwise-com-894aed9d69814dd99c00b2cc28cb0dae', folder: 'Projects / Turtle / Clients / LW', created: '2024-01-18T23:20:18.472Z' },
  // ── Research ─────────────────────────────────────────────────────────
  { title: 'Jeremy Chone', url: 'https://www.youtube.com/@JeremyChone', excerpt: 'Channel focused on production coding with Rust, software engineering, and building next-gen applications.', cover: 'https://yt3.googleusercontent.com/-QPZj0mPDrLZGjoccYdsI6DHo0dCPEDoZW--_UcTmCJtSDdfShCGMo2s_DDNL1Zy24z5ASnXYA=s900-c-k-c0x00ffffff-no-rj', folder: 'Research', created: '2025-02-08T02:15:31.197Z' },
  { title: 'Sage the Bad Naturalist', url: 'https://www.youtube.com/@BadNaturalist/shorts', excerpt: 'Mycology, plants, and science rants.', cover: 'https://yt3.googleusercontent.com/shKpKmfaoVa9A5gTZgZa8GkQCyL0Du5cnVofj-yVRlIyI76A8nnut39wnooFNNxD8xAeQjLf9xY=s900-c-k-c0x00ffffff-no-rj', folder: 'Research', created: '2025-01-07T04:37:49.846Z' },
  { title: 'Threlte — 3D framework for Svelte', url: 'https://threlte.xyz/docs/examples/animation/animation-transitions', cover: 'https://threlte.xyz/threlte-social-preview-v2.jpg', folder: 'Research', created: '2024-12-15T00:24:46.015Z' },
  { title: 'Luma Dream Machine — AI Video Generator', url: 'https://lumalabs.ai/dream-machine/creations', cover: 'https://cdn-luma.com/public/lumalabs.ai/june-12-launch-dream-machine-high-res/og-image.png', folder: 'Research', created: '2024-12-14T09:31:49.157Z' },
  { title: 'mymind — Extension for your mind', url: 'https://mymind.com/', excerpt: 'A private place to save your most precious notes, images, quotes and highlights.', cover: 'https://mymind.com/wp-content/uploads/2023/05/Mymind_2023_F.jpg', folder: 'Research', created: '2024-12-14T07:40:40.325Z' },
  { title: 'Eternal — rob.computer', url: 'https://eternal.rob.computer/', folder: 'Research', created: '2024-12-07T20:24:06.903Z' },
  { title: 'GitHub Next — Code Atlas', url: 'https://githubnext.com/projects/code-atlas/', excerpt: 'How can we make LLM responses more robust and easier to understand?', cover: 'https://githubnext.com/assets/images/og/project/code-atlas.png', folder: 'Research', created: '2024-11-17T01:48:07.889Z' },
  { title: 'GitHub Next — Code Brushes', url: 'https://githubnext.com/projects/code-brushes/', excerpt: 'Can editing code feel more tactile, like painting with Photoshop brushes?', cover: 'https://githubnext.com/assets/images/og/project/code-brushes.png', folder: 'Research', created: '2024-11-17T01:47:55.408Z' },
  { title: 'Eventually consistent plain text accounting', url: 'https://tylercipriani.com/blog/2024/10/24/plain-text-accounting/', folder: 'Research', created: '2024-11-17T00:44:26.582Z' },
  { title: 'Elicit: The AI Research Assistant', url: 'https://elicit.com/?workflow=table-of-papers', excerpt: 'Use AI to search, summarize, extract data from, and chat with over 125 million papers.', cover: 'https://cdn.prod.website-files.com/6516f50e7a19045d3d7b12f2/65cbaa12d92010f7b80468ab_elicit-og-image.png', folder: 'Research', created: '2024-10-01T06:55:19.681Z' },
  { title: 'bolt.new — Vue project', url: 'https://bolt.new/~/bolt-vue', folder: 'Research', created: '2024-10-05T08:18:50.524Z' },
  { title: 'Natural language is the lazy user interface', url: 'https://austinhenley.com/blog/naturallanguageui.html', excerpt: 'A chatbot is the lazy user interface. It puts all the burden on the user.', cover: 'https://austinhenley.com/blog/images/twochatbots.png', folder: 'Research', created: '2024-09-20T07:02:37.798Z' },
  { title: 'Kelset', url: 'https://kelset.dev/', folder: 'Research', created: '2024-08-13T17:19:14.684Z' },
  { title: 'Coggle Diagram', url: 'https://coggle.it/diagram/aMiK2GXYPwvrYewy/t/-', folder: 'AI / Tools', created: '2025-09-15T21:54:51.387Z' },
  { title: 'public-apis — A collective list of free APIs', url: 'https://github.com/public-apis/public-apis', cover: 'https://repository-images.githubusercontent.com/54346799/e5ee272c-dfe1-40e5-b66b-b0a36e815254', folder: 'Research / Development', created: '2024-08-21T08:01:18.709Z' },
  // ── Research / Articles ──────────────────────────────────────────────
  { title: 'The Mundane Afrofuturist Manifesto', url: 'https://rhizome.org/editorial/2013/dec/17/mundane-afrofuturist-manifesto/', folder: 'Research / Articles', created: '2024-08-14T04:28:17.501Z' },
  { title: 'Thought as a Technology', url: 'https://cognitivemedium.com/tat/index.html', cover: 'https://cognitivemedium.com/tat/assets/C64.gif', folder: 'Research / Articles', created: '2024-03-04T09:23:21.819Z' },
  { title: 'Reinventing Explanation', url: 'https://michaelnielsen.org/reinventing_explanation/index.html', cover: 'https://michaelnielsen.org/reinventing_explanation/Babylonian_map.JPG', folder: 'Research / Articles', created: '2024-03-04T09:21:20.361Z' },
  { title: 'Repenning & Sterman — Nobody Ever Gets Credit for Fixing Problems', url: 'https://web.mit.edu/nelsonr/www/Repenning=Sterman_CMR_su01_.pdf', folder: 'Research / Articles', created: '2024-03-04T09:19:39.620Z' },
  { title: 'Magic Paper', url: 'https://cognitivemedium.com/magic_paper/index.html', cover: 'https://cognitivemedium.com/magic_paper/assets/multiple_graphs.png', folder: 'Research / Articles', created: '2024-02-06T12:20:28.103Z' },
  { title: 'Incremental and Iterative Development', url: 'https://medium.com/@alexbunardzic/incremental-and-iterative-development-8a55ffcf4145', folder: 'Research / Articles', created: '2024-01-20T02:45:06.921Z' },
  { title: 'Designing for AI Notes — Nick Arner', url: 'https://nickarner.com/notes/designing-for-ai-notes---december-12-2023/', cover: 'https://nickarner.com/card.jpg', folder: 'Research / Articles', created: '2024-01-18T21:48:28.172Z' },
  { title: 'Invisible Details of Interaction Design', url: 'https://rauno.me/craft/interaction-design#fidgetability', excerpt: 'What makes great interactions feel right?', cover: 'https://rauno.me/static/craft/og-interaction-design2.png', folder: 'Design / Articles', created: '2024-03-19T23:03:58.161Z' },
  { title: 'Listen or Speak — Mike Fisher', url: 'https://mikefisher.substack.com/p/listen-or-speak', excerpt: 'What should leaders do more of?', folder: 'Design / Articles', created: '2024-03-04T09:26:34.137Z' },
  { title: 'The artist and the machine — Michael Nielsen', url: 'https://michaelnielsen.org/blog/the-artist-and-the-machine/', cover: 'https://michaelnielsen.org/blog/wp-content/uploads/2013/02/Hubble_EDF.jpg', folder: 'Design / Articles', created: '2024-03-04T09:24:10.996Z' },
  { title: 'What I Learned as a Product Designer at Apple', url: 'https://medium.com/@pachecoandrea/what-i-learned-as-a-product-designer-at-apple-35341d9ced8a', cover: 'https://miro.medium.com/v2/resize:fit:1200/1*BniKIhT3c54sIEuPtzRQKw.jpeg', folder: 'Design / Articles', created: '2024-01-18T23:12:43.994Z' },
  { title: 'Rianna Jade Parker — Writing', url: 'http://riannajadeparker.com/writing', folder: 'Design / Articles', created: '2024-01-18T23:12:37.911Z' },
  // ── Research / Blogs ─────────────────────────────────────────────────
  { title: 'Ahmni Infinite Canvas', url: 'https://www.ahmni.app/blog', excerpt: 'Study tips and discussions for self-regulated, higher-order learning.', folder: 'Research / Blogs', created: '2024-12-20T19:19:35.258Z' },
  { title: 'rhizome.org', url: 'http://rhizome.org', folder: 'Research / Blogs', created: '2024-08-14T04:26:57.413Z' },
  { title: 'Cognitive Medium', url: 'https://cognitivemedium.com/', folder: 'Research / Blogs', created: '2024-08-14T00:21:41.162Z' },
  { title: 'Michael Nielsen', url: 'https://michaelnielsen.org/', cover: 'https://michaelnielsen.org/images/mn.jpg', folder: 'Research / Blogs', created: '2024-02-06T12:17:25.711Z' },
  { title: 'Media for Thinking the Unthinkable — Bret Victor', url: 'https://worrydream.com/MediaForThinkingTheUnthinkable/', folder: 'Research / Blogs', created: '2024-03-04T09:19:16.600Z' },
  { title: 'Michael\'s Notebook', url: 'https://michaelnotebook.com/', cover: 'https://michaelnotebook.com/assets/self.jpg', folder: 'Research / Blogs', created: '2024-02-06T14:02:15.414Z' },
  { title: 'Embark: Dynamic documents for making plans', url: 'https://www.inkandswitch.com/embark/', excerpt: 'Gradually enriching a text outline with travel planning tools', cover: 'https://www.inkandswitch.com/embark/static/embark-social-image.jpg', folder: 'Research / Blogs', created: '2024-01-18T21:48:28.174Z' },
  { title: 'Adept AI — Blog', url: 'https://www.adept.ai/blog', cover: 'https://www.adept.ai/images/adept-logo.png', folder: 'Research / Blogs', created: '2024-01-18T21:48:28.171Z' },
  { title: 'Gordon Brander | Substack', url: 'https://substack.com/@gordonbrander', folder: 'Research / Blogs', created: '2024-01-18T22:57:12.681Z', pinned: true },
  { title: 'Amelia Wattenberger', url: 'https://wattenberger.com/', folder: 'Research / Blogs', created: '2024-01-18T21:48:28.173Z' },
  { title: 'Andy Matuschak', url: 'https://andymatuschak.org/', folder: 'Research / Blogs', created: '2024-01-18T22:57:42.718Z' },
  { title: 'Subconscious — Gordon Brander', url: 'https://subconscious.substack.com/', folder: 'Research / Blogs', created: '2024-01-18T22:57:29.656Z' },
  { title: 'The Garden of Maggie Appleton', url: 'https://maggieappleton.com/garden', excerpt: 'A digital garden filled with visual essays on programming, design, and anthropology', cover: 'https://maggieappleton.com/og.png', folder: 'Research / Blogs', created: '2024-01-18T22:56:56.270Z' },
  { title: 'Rach Smith\'s digital garden', url: 'https://rachsmith.com/', folder: 'Research / Blogs', created: '2024-01-18T21:48:28.157Z' },
  // ── Research / Tools ─────────────────────────────────────────────────
  { title: 'CSS ICON', url: 'https://cssicon.space/#/animate/clock-h3m30/to/clock-h9m0-solid', folder: 'Research / Tools', created: '2024-08-24T01:44:59.524Z' },
  { title: 'Scribe — Create Step-by-Step Guides', url: 'https://scribehow.com/', excerpt: 'Scribe documents your processes for you.', cover: 'https://cdn.prod.website-files.com/615f415173b71a5211e28de7/64763110bc00acf4a3ac305b_scribe-opengraph-new.webp', folder: 'Research / Tools', created: '2024-08-22T20:48:06.199Z' },
  { title: 'Framer Academy — Fetch', url: 'https://www.framer.com/academy/lessons/fetch', excerpt: 'Fetch enables you to leverage the power of APIs to add dynamic data to your Framer Site.', folder: 'Research / Tools', created: '2024-08-13T07:16:52.960Z' },
  { title: 'Retool', url: 'https://retool.com/', excerpt: 'The fastest way to build effective business software.', cover: 'https://d3399nw8s4ngfo.cloudfront.net/og-image-default.webp', folder: 'Research / Tools / Apps', created: '2024-03-02T23:16:40.848Z' },
  { title: 'Kinopio', url: 'https://kinopio.club/hello-kinopio-U2RURv25JPx_GCkFo4-EZ', folder: 'Research / Tools / Apps', created: '2024-01-18T22:55:28.914Z' },
  { title: 'Craft Docs', url: 'https://docs.craft.do/recents', excerpt: 'A fresh take on documents.', cover: 'https://docs.craft.do/static/craft_og.png', folder: 'Research / Tools / Apps', created: '2024-01-18T22:54:56.237Z' },
  { title: 'Dynaboard — Collaborative low-code IDE', url: 'https://dynaboard.com/', excerpt: 'The fast development platform for full-stack web apps.', cover: 'https://images.ctfassets.net/b0wn34vnc1k8/UnmzMMHv5u02RJcDhhFSA/e78b60d6f86e26247b6b581c62b55353/dynaboard.png', folder: 'AI / Tools', created: '2024-03-02T23:16:51.613Z' },
  { title: 'v0 by Vercel', url: 'https://v0.dev/', excerpt: 'Generate UI with simple text prompts. Copy, paste, ship.', cover: 'https://v0.dev/opengraph-image-19iptc.png', folder: 'AI / Tools', created: '2024-02-06T04:39:24.395Z' },
  { title: 'Relevance AI — Tool Templates', url: 'https://app.relevanceai.com/templates', excerpt: 'Easily build AI superpowers into your product.', folder: 'AI / Tools', created: '2024-01-18T23:01:31.298Z' },
  { title: 'Together AI', url: 'https://www.together.ai/', excerpt: 'Build gen AI models with Together AI.', folder: 'AI / Tools', created: '2024-01-18T23:01:20.525Z' },
  { title: 'ElevenLabs — Text to Speech', url: 'https://elevenlabs.io/text-to-speech', excerpt: 'Create natural AI voice instantly in any language.', cover: 'https://elevenlabs.io/image/opengraph-image.png', folder: 'AI / Tools', created: '2024-01-18T23:01:15.577Z' },
  { title: 'Langflow', url: 'https://www.langflow.org/', excerpt: 'A GUI for LangChain, designed with react-flow to provide an effortless way to experiment and prototype flows.', cover: 'https://framerusercontent.com/images/egFvXTIHvGSaT59SvltkVS2kxNs.png', folder: 'AI / Tools', created: '2024-01-18T23:01:09.779Z' },
  { title: 'Elicit — Analyze research papers', url: 'https://elicit.com/?workflow=table-of-papers', excerpt: 'Automate time-consuming research tasks like summarizing papers and extracting data.', folder: 'AI / Tools', created: '2024-01-18T23:01:00.261Z' },
  { title: 'Raycast — Supercharged productivity', url: 'https://raycast.com', excerpt: 'Raycast lets you control your tools with a few keystrokes.', cover: 'https://raycast-frontend-q6k11bj7g-raycastapp.vercel.app/_next/static/media/og-image.881e005e.png', folder: 'AI / Tools', created: '2024-01-18T23:00:54.481Z' },
  // ── Research / Gardens ───────────────────────────────────────────────
  { title: 'Nick Arner — Notes', url: 'https://nickarner.com/notes', cover: 'https://nickarner.com/card.jpg', folder: 'Research / Gardens', created: '2024-01-20T05:38:58.611Z' },
  { title: 'The Garden of Maggie Appleton', url: 'https://maggieappleton.com/garden', cover: 'https://maggieappleton.com/og.png', folder: 'Research / Gardens', created: '2024-01-20T02:52:33.008Z' },
  // ── Design ───────────────────────────────────────────────────────────
  { title: 'Collage — Eyecandy Technique', url: 'https://eyecannndy.com/technique/collage', cover: 'https://asset.eyecannndy.com/static/images/eyecandy-og.jpg', folder: 'Design', created: '2024-02-29T17:25:33.466Z' },
  { title: 'Elizabeth Lin — Designer & Aspiring Princess', url: 'https://www.elizabethylin.com/', cover: 'http://www.elizabethylin.com/thumbnail-alt.png', folder: 'Design', created: '2024-02-13T21:45:04.568Z' },
  // ── Design / Tools ───────────────────────────────────────────────────
  { title: 'VS Code Theme Studio', url: 'https://themes.vscode.one/', excerpt: 'The easiest way to create a theme for VS Code.', cover: 'https://themes.vscode.one/theme-studio.png', folder: 'Design / Tools', created: '2024-01-18T23:11:49.843Z' },
  { title: 'Coolors', url: 'https://coolors.co/355070-6d597a-b56576-e56b6f-eaac8b', folder: 'Design / Tools', created: '2024-01-18T23:11:30.033Z' },
  { title: 'Designs.AI — Design Maker', url: 'https://designs.ai/designmaker/start/designs/65950e722522fe00133fb7e9/edit', folder: 'Design / Tools', created: '2024-01-18T23:11:07.796Z' },
  // ── Design / Inspiration / Web Design ────────────────────────────────
  { title: 'Disguised', url: 'https://www.disguised.gg/', folder: 'Design / Inspiration / Web Design', created: '2024-01-18T23:10:31.540Z' },
  { title: 'Friesday', url: 'https://friesday.lspn.fr/', folder: 'Design / Inspiration / Web Design', created: '2024-01-18T23:10:25.145Z' },
  { title: 'Evan Fasquelle — Digital designer', url: 'https://evanfasquelle.com/about/', folder: 'Design / Inspiration / Web Design', created: '2024-01-18T23:10:13.197Z' },
  { title: 'Xavier Coulombe-Murray', url: 'https://xavier.works/', excerpt: 'Co-Creative Director @ Sid Lee', cover: 'https://www.datocms-assets.com/67144/1651639850-e91c04c21d45d1dffd3a8117aa002799.jpeg', folder: 'Design / Inspiration / Web Design', created: '2024-01-18T23:09:47.081Z' },
  // ── Design / Surface Design ──────────────────────────────────────────
  { title: 'How to make a living as a surface pattern designer', url: 'https://majafaber.com/blog/how-to-make-a-living-as-a-surface-pattern-designer', folder: 'Design / Surface Design', created: '2024-01-18T23:09:22.693Z' },
  { title: 'Elizabeth Silver — Surface Pattern Design', url: 'https://www.youtube.com/@ElizabethSilver/playlists', cover: 'https://yt3.googleusercontent.com/ytc/AIf8zZQUou7E-PJWr_D06bxiNvUombM3VT8E4k-5jUnmfA=s900-c-k-c0x00ffffff-no-rj', folder: 'Design / Surface Design', created: '2024-01-18T23:08:49.646Z' },
  { title: 'Easy Pattern Design In Procreate Using Ogee Layout', url: 'https://www.youtube.com/watch?v=pw0eq0zQ0K4', cover: 'https://i.ytimg.com/vi/pw0eq0zQ0K4/maxresdefault.jpg', folder: 'Design / Surface Design', created: '2024-01-18T23:07:23.232Z' },
  // ── AI / GPTs ────────────────────────────────────────────────────────
  { title: 'Agency Owners GPT', url: 'https://chat.openai.com/g/g-hdxS6cpxE-agency-owners-gpt', excerpt: 'Find the right problems worth solving.', folder: 'AI / GPTs', created: '2024-01-20T02:44:57.681Z' },
  { title: 'Business Growth Advisor GPT', url: 'https://chat.openai.com/g/g-NulUxPn8B-business-growth-advisor-gpt', excerpt: 'Generate ideas for maximizing returns with minimum effort.', folder: 'AI / GPTs', created: '2024-01-20T02:44:53.483Z' },
  { title: 'Hustle GPT', url: 'https://chat.openai.com/g/g-T38EPOinI-hustle-gpt', excerpt: 'A guide for online income generation using AI tools.', folder: 'AI / GPTs', created: '2024-01-20T02:44:49.996Z' },
  { title: 'Business Coach GPT', url: 'https://chat.openai.com/g/g-k9tj7pbBT-business-coach-gpt', excerpt: 'A world-class coach for Solopreneurs.', folder: 'AI / GPTs', created: '2024-01-20T02:44:42.091Z' },
  // ── Research (deep) ──────────────────────────────────────────────────
  { title: 'Introduction to the Noosphere', url: 'https://www.youtube.com/watch?v=HXtznVDVPzs', cover: 'https://i.ytimg.com/vi/HXtznVDVPzs/maxresdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.205Z' },
  { title: 'Climbing the Ladder of Abstraction — Amelia Wattenberger', url: 'https://www.youtube.com/watch?v=PAy_GHUAICw', cover: 'https://i.ytimg.com/vi/PAy_GHUAICw/hqdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.205Z' },
  { title: 'How I take tech notes — devaslife', url: 'https://www.youtube.com/watch?v=rjOuCFrs584', cover: 'https://i.ytimg.com/vi/rjOuCFrs584/maxresdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.204Z' },
  { title: 'How To Get Started: The Cult of Done', url: 'https://www.youtube.com/watch?v=bJQj1uKtnus', cover: 'https://i.ytimg.com/vi/bJQj1uKtnus/maxresdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.203Z' },
  { title: 'The Expanding Dark Forest and Generative AI — Maggie Appleton', url: 'https://www.youtube.com/watch?v=QPoM-h1fK8M', cover: 'https://i.ytimg.com/vi/QPoM-h1fK8M/maxresdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.202Z' },
  { title: 'AI Jason — YouTube', url: 'https://www.youtube.com/@AIJasonZ/videos', cover: 'https://yt3.googleusercontent.com/4Cr1CODrmOzV2i9V4sEE1Re7Ip5-XMKl3iM-zOrXFMzUx2AsXvqak7MgsbzKefFa00LO7aCRKA=s900-c-k-c0x00ffffff-no-rj', folder: 'Research', created: '2024-01-18T21:48:28.201Z' },
  { title: 'Subconscious — Building a Second Brain', url: 'https://www.youtube.com/watch?v=3EGBKamKvJI', cover: 'https://i.ytimg.com/vi/3EGBKamKvJI/maxresdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.200Z' },
  { title: 'Home — Spatial Web Foundation', url: 'https://spatialwebfoundation.org/', cover: 'https://spatialwebfoundation.org/wp-content/uploads/2023/08/swf-social-share.png', folder: 'Research', created: '2024-01-18T21:48:28.193Z' },
  { title: 'Spatial Web Browsing — Maggie Appleton', url: 'https://maggieappleton.com/spatial-web', excerpt: 'Adding spatial affordances to the experience of browsing the web', cover: 'https://maggieappleton.com/images/og/2643d336cfb4a6b3040fb34f709a87df.png', folder: 'Research', created: '2024-01-18T21:48:28.191Z' },
  { title: 'Getting started | InfiniteCanvas', url: 'https://infinite-canvas.org/getting-started.html', folder: 'Research', created: '2024-01-18T21:48:28.191Z' },
  { title: 'Nette — A Research OS for the Web', url: 'https://nette.io/hiring', folder: 'Research', created: '2024-01-18T21:48:28.191Z' },
  { title: 'Amelia Wattenberger — Evolving the Infinite Canvas', url: 'https://wattenberger.com/thoughts/evolving-the-infinite-canvas', folder: 'Research', created: '2024-01-18T21:48:28.174Z' },
  { title: 'AI Engineer Summit — Climbing the Ladder of Abstraction', url: 'https://www.ai.engineer/summit/schedule/climbing-the-ladder-of-abstraction', cover: 'https://aie-cms-uploads.s3.us-west-1.amazonaws.com/amelia_thumb_af34637b36.png', folder: 'Research', created: '2024-01-18T21:48:28.170Z' },
  { title: 'Knowledge synthesis: A conceptual model and practical guide', url: 'https://oasislab.pubpub.org/pub/54t0y9mk/release/3', cover: 'https://assets.pubpub.org/yzvnxdby/21609052646170.png', folder: 'Research', created: '2024-01-18T21:48:28.169Z' },
  { title: 'Finding a Standard for Capturing Knowledge', url: 'https://postdrafts.com/finding-a-standard-for-capturing-knowledge/', cover: 'https://postdrafts.com/wp-content/uploads/2023/07/image-finding-a-standard-for-capturing-knowledge.jpg', folder: 'Research', created: '2024-01-18T21:48:28.168Z' },
  { title: 'Digital Garden — postdrafts', url: 'https://postdrafts.com/category/digital-garden/', folder: 'Research', created: '2024-01-18T21:48:28.164Z' },
  { title: 'Block Protocol — Docs', url: 'https://blockprotocol.org/docs#overview', excerpt: 'An open standard for data-driven blocks', cover: 'https://blockprotocol.org/assets/bp_og_cover.png', folder: 'Research', created: '2024-01-18T21:48:28.181Z' },
  { title: 'A Brief Introduction to Digital Anthropology', url: 'https://maggieappleton.com/digital-anthropology', excerpt: 'A discipline at the intersection of cultural anthropology and binary logic', cover: 'https://maggieappleton.com/images/og/05c744ddb6cf2d1b66fd0e2ef60c1878.png', folder: 'Research', created: '2024-01-18T21:48:28.180Z' },
  { title: 'Ultra — Multi-media smart canvas', url: 'https://ultra.tf/', excerpt: 'A multi-media smart canvas for your mind.', cover: 'https://ultra.tf/og3.png', folder: 'Research', created: '2024-01-18T21:48:28.176Z' },
  { title: 'WICG/proposals — Web platform incubations', url: 'https://github.com/WICG/proposals', cover: 'https://opengraph.githubassets.com/56c6293eef49ac7df52dc30ef09277b52a76b645a998a3e1b8968a6142019388/WICG/proposals', folder: 'Research', created: '2024-01-18T21:48:28.178Z' },
  { title: 'W3C API Overview', url: 'https://w3c.github.io/w3c-api/', folder: 'Research', created: '2024-01-18T21:48:28.177Z' },
  { title: 'W3C Community and Business Groups', url: 'https://www.w3.org/community/', folder: 'Research', created: '2024-01-18T21:48:28.177Z' },
  { title: 'Evergreen notes — Andy Matuschak', url: 'https://notes.andymatuschak.org/z5E5QawiXCMbtNtupvxeoEX', folder: 'Research', created: '2024-01-18T21:48:28.147Z' },
  { title: 'Taxonomy of note types — Andy Matuschak', url: 'https://notes.andymatuschak.org/zTDjZQbKAT9pALtsk2HfePx', folder: 'Research', created: '2024-01-18T21:48:28.153Z' },
  { title: 'Growing the Evergreens — Maggie Appleton', url: 'https://maggieappleton.com/evergreens', cover: 'https://maggieappleton.com/images/og/f17f2e7e67ac2192852c5f77d719e470.png', folder: 'Research', created: '2024-01-18T21:48:28.146Z' },
  { title: 'Metaphors We Web By — Maggie Appleton', url: 'https://maggieappleton.com/metaphors-web', cover: 'https://maggieappleton.com/images/og/4408b5a1a70df0ace6e31ac1d6a7ebf7.png', folder: 'Research', created: '2024-01-18T21:48:28.145Z' },
  { title: 'Tools for thought should evolve building blocks — Gordon Brander', url: 'https://subconscious.substack.com/p/tools-for-thought-should-evolve-building', folder: 'Research', created: '2024-01-18T21:48:28.145Z' },
  { title: 'How can we develop transformative tools for thought?', url: 'https://numinous.productions/ttft/', excerpt: 'Numinous Productions', cover: 'https://numinous.productions/ttft/assets/social.png', folder: 'Research', created: '2024-01-18T21:48:28.143Z' },
  { title: 'Feedback is all you need — Gordon Brander', url: 'https://subconscious.substack.com/p/feedback-is-all-you-need', excerpt: '...for LLMs to gain agency.', folder: 'Research', created: '2024-01-18T21:48:28.142Z' },
  { title: 'Tools for thought: science, design, art, craftsmanship? — Andy Matuschak', url: 'https://andymatuschak.org/sdac/', folder: 'Research', created: '2024-01-18T21:48:28.142Z' },
  { title: 'Tools for Thought Rocks! — YouTube', url: 'https://www.youtube.com/@ToolsforThought/videos', cover: 'https://yt3.googleusercontent.com/b4W36rzxLDP21CexWR_vS8nEUfzX4kksh4bNZHhRKcC1IoPAygNdrWIdXXh8DdWc0J9vnFBab3M=s900-c-k-c0x00ffffff-no-rj', folder: 'Research', created: '2024-01-18T21:48:28.141Z' },
  { title: 'Early Tools for Thought — Mark Bernstein', url: 'https://www.youtube.com/watch?v=smTUHRDYm5E', cover: 'https://i.ytimg.com/vi/smTUHRDYm5E/maxresdefault.jpg', folder: 'Research', created: '2024-01-18T21:48:28.141Z' },
  { title: 'Provocation-driven development — Gordon Brander', url: 'https://subconscious.substack.com/p/provocation-driven-development', folder: 'Research', created: '2024-01-18T21:48:28.157Z' },
  { title: 'Fragments: vertebrate technology — Gordon Brander', url: 'https://subconscious.substack.com/p/fragments-vertebrate-technology', folder: 'Research', created: '2024-01-18T21:48:28.158Z' },
  { title: 'Learn In Public — swyx', url: 'https://www.swyx.io/learn-in-public', excerpt: 'The fastest way to build your expertise, network, and second brain.', folder: 'Research', created: '2024-01-18T21:48:28.162Z' },
  { title: 'Fitts\'s law — Wikipedia', url: 'https://en.wikipedia.org/wiki/Fitts%27s_law', cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Fitts_Law.svg/1200px-Fitts_Law.svg.png', folder: 'Research', created: '2024-01-18T21:48:28.144Z' },
  { title: 'Three component model of memory — supermemo.guru', url: 'https://supermemo.guru/wiki/Three_component_model_of_memory', folder: 'Research', created: '2024-01-18T21:48:28.143Z' },
  { title: 'LiveStore — Local-first data layer', url: 'https://livestore.dev/', excerpt: 'LiveStore is a state management framework based on SQLite and event-sourcing.', cover: 'https://livestore.dev/opengraph-image.jpg', folder: 'Research', created: '2024-05-31T21:21:56.288Z' },
]

export function getBookmarkSeedItems(): SeedEntity[] {
  return BOOKMARKS.map((b, i) => buildBookmark(b, i + 1))
}
