/**
 * Seed data for personal calendar items.
 *
 * Used by instant.client.ts to populate the calendarItems namespace
 * on first boot. Dates are relative to "today" so the data always
 * looks fresh.
 */

const today = new Date()
const fmt = (d: Date) => d.toISOString().split('T')[0]!
const daysFromNow = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + n)
  return fmt(d)
}

export interface SeedCalendarItem {
  id: string
  [key: string]: any
}

export function getPersonalSeedItems(): SeedCalendarItem[] {
  return [
    // ── Tasks ──────────────────────────────────────────────────────────
    {
      id: 'task-1',
      type: 'task',
      title: 'Finish quarterly review slides',
      description: 'Prepare the slide deck for Q1 review with stakeholders.',
      startDate: daysFromNow(-2),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['presentation', 'quarterly'],
      owner: 'you',
      involved: [],
      folder: 'Work',
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-t1-e2',
          entityId: 'event-2',
          entityType: 'event',
          title: 'Design review — new dashboard',
          direction: 'outgoing',
        },
        { kind: 'file', id: 'ref-t1-f1', name: 'Q1_Slides_Draft.pdf', fileType: 'pdf' },
      ],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [
        { id: 'cl-1', label: 'Draft outline', completed: true, order: 0 },
        { id: 'cl-2', label: 'Add financial charts', completed: false, order: 1 },
        { id: 'cl-3', label: 'Review with manager', completed: false, order: 2 },
      ],
    },
    {
      id: 'task-2',
      type: 'task',
      title: 'Call dentist to confirm appointment',
      description: 'Confirm the cleaning scheduled for next week.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'medium',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['appointment'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r1', timing: '1-hour-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-3',
      type: 'task',
      title: 'Submit expense report',
      description: 'January expenses — receipts already uploaded.',
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['finance'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [{ kind: 'file', id: 'ref-t3-f1', name: 'January_Receipts.xlsx', fileType: 'spreadsheet' }],
      reminders: [{ id: 'r2', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-4',
      type: 'task',
      title: 'Read chapter 5 — Replication',
      description: 'Continue "Designing Data-Intensive Applications".',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['reading', 'engineering'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-t4-n4',
          entityId: 'note-4',
          entityType: 'note',
          title: 'Book recommendations',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [],
    },
    {
      id: 'task-5',
      type: 'task',
      title: 'Water the plants',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['home'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r3', timing: '1-day-before', method: 'push' }],
      recurrence: { frequency: 'weekly', weekdays: [1, 4] },
      taskStatus: 'completed',
      checklist: [],
    },
    {
      id: 'task-6',
      type: 'task',
      title: 'Back up laptop',
      description: 'Full Time Machine backup — last one was 3 weeks ago.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: true,
      category: 'personal',
      tags: ['tech'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'overdue',
      checklist: [],
    },
    {
      id: 'task-7',
      type: 'task',
      title: 'Pick up dry cleaning',
      startDate: daysFromNow(2),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['errands'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r4', timing: '15-min-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-8',
      type: 'task',
      title: 'Send birthday card to Sam',
      description: 'Birthday is on the 15th — mail by the 12th.',
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['birthday'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r5', timing: '2-days-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-9',
      type: 'task',
      title: 'Book annual physical',
      description: 'Schedule appointment with Dr. Patel.',
      startDate: daysFromNow(5),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['doctor'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-10',
      type: 'task',
      title: 'Renew car registration',
      description: 'Registration expires end of month.',
      startDate: daysFromNow(12),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['admin', 'vehicle'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r6', timing: '1-week-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-11',
      type: 'task',
      title: 'Update portfolio website',
      description: 'Add recent project case studies and refresh the design section.',
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['portfolio', 'design'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // Multi-day task: sprint
    {
      id: 'task-12',
      type: 'task',
      title: 'Sprint 14 — API refactor',
      description: 'Refactor authentication endpoints and add rate limiting.',
      startDate: daysFromNow(-1),
      endDate: daysFromNow(4),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['sprint', 'backend'],
      owner: 'you',
      involved: ['alex', 'jordan'],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [
        { id: 'cl-s1', label: 'Audit existing auth endpoints', completed: true, order: 0 },
        { id: 'cl-s2', label: 'Implement rate limiter middleware', completed: false, order: 1 },
        { id: 'cl-s3', label: 'Write integration tests', completed: false, order: 2 },
        { id: 'cl-s4', label: 'Deploy to staging', completed: false, order: 3 },
      ],
    },
    {
      id: 'task-13',
      type: 'task',
      title: 'Morning standup prep',
      description: 'Review Jira board and prepare status update.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '08:45',
      endTime: '09:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['daily', 'routine'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      recurrence: { frequency: 'weekdays' },
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-14',
      type: 'task',
      title: 'Review PR #482 — pagination fix',
      description: "Alex's PR for the infinite scroll pagination bug.",
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['code-review'],
      owner: 'you',
      involved: ['alex'],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-15',
      type: 'task',
      title: 'Grocery run',
      description: 'Weekly groceries — check the meal plan first.',
      startDate: daysFromNow(2),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['errands', 'weekly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      recurrence: { frequency: 'weekly', weekdays: [0] },
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-16',
      type: 'task',
      title: 'Prep slide deck for investor update',
      description: 'Q1 metrics, runway, and product roadmap.',
      startDate: daysFromNow(3),
      endDate: daysFromNow(5),
      allDay: true,
      priority: 'critical',
      urgency: 'urgent',
      priorityOverride: true,
      urgencyOverride: true,
      category: 'work',
      tags: ['presentation', 'investors'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      references: [],
      reminders: [{ id: 'r-t16', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-17',
      type: 'task',
      title: 'Journal — daily reflection',
      description: 'End-of-day reflection and gratitude practice.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '21:00',
      endTime: '21:30',
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['journal', 'daily'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      recurrence: { frequency: 'daily' },
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-18',
      type: 'task',
      title: 'Migrate CI to GitHub Actions',
      description: 'Move from CircleCI to GitHub Actions for cost savings.',
      startDate: daysFromNow(9),
      endDate: daysFromNow(11),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['devops', 'migration'],
      owner: 'you',
      involved: ['eli'],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Events ─────────────────────────────────────────────────────────
    {
      id: 'event-1',
      type: 'event',
      title: 'Team standup',
      description: 'Daily sync with the product team.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '09:30',
      endTime: '09:45',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['recurring'],
      owner: 'you',
      involved: ['alex', 'jordan'],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'meeting',
      recurrence: { frequency: 'weekdays' },
    },
    {
      id: 'event-2',
      type: 'event',
      title: 'Design review — new dashboard',
      description: 'Present wireframes and get feedback.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '14:00',
      endTime: '15:00',
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['design'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-e2-t1',
          entityId: 'task-1',
          entityType: 'task',
          title: 'Finish quarterly review slides',
          direction: 'incoming',
        },
      ],
      reminders: [{ id: 'r7', timing: '15-min-before', method: 'push' }],
      eventType: 'meeting',
    },
    {
      id: 'event-3',
      type: 'event',
      title: 'Dentist appointment',
      description: 'Cleaning & checkup at Bright Smiles.',
      startDate: daysFromNow(3),
      allDay: false,
      startTime: '14:00',
      endTime: '15:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'appointment',
      tags: ['health'],
      owner: 'you',
      involved: [],
      location: '123 Main St, Suite 200',
      attachments: [],
      references: [],
      reminders: [{ id: 'r8', timing: '1-day-before', method: 'push' }],
      eventType: 'appointment',
    },
    {
      id: 'event-4',
      type: 'event',
      title: 'Design systems workshop',
      description: 'Internal training on component library patterns.',
      startDate: daysFromNow(6),
      allDay: false,
      startTime: '13:00',
      endTime: '16:00',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['training', 'design-systems'],
      owner: 'you',
      involved: ['maya', 'eli'],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'training',
      conferenceLink: 'https://meet.example.com/workshop',
    },
    {
      id: 'event-5',
      type: 'event',
      title: "Mom's birthday dinner",
      description: 'Reservation at Olive Garden, 6 PM.',
      startDate: daysFromNow(10),
      allDay: false,
      startTime: '18:00',
      endTime: '20:00',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['family', 'birthday'],
      owner: 'you',
      involved: ['family'],
      location: 'Olive Garden, Elmwood Ave',
      attachments: [],
      references: [],
      reminders: [{ id: 'r9', timing: '1-day-before', method: 'push' }],
      eventType: 'social',
    },

    // Multi-day event: conference
    {
      id: 'event-6',
      type: 'event',
      title: 'React Summit 2026',
      description: 'Two-day frontend conference — talks, workshops, and networking.',
      startDate: daysFromNow(14),
      endDate: daysFromNow(15),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['conference', 'frontend'],
      owner: 'you',
      involved: ['maya', 'eli'],
      location: 'Convention Center, Downtown',
      attachments: [],
      references: [],
      reminders: [{ id: 'r-e6', timing: '1-week-before', method: 'push' }],
      eventType: 'training',
    },
    {
      id: 'event-7',
      type: 'event',
      title: 'Sprint retrospective',
      description: 'Bi-weekly retro — what went well, what to improve.',
      startDate: daysFromNow(4),
      allDay: false,
      startTime: '16:00',
      endTime: '17:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['retro', 'sprint'],
      owner: 'you',
      involved: ['alex', 'jordan', 'maya'],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'meeting',
    },
    {
      id: 'event-8',
      type: 'event',
      title: 'Lunch with Sam',
      startDate: daysFromNow(2),
      allDay: false,
      startTime: '12:00',
      endTime: '13:00',
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['social'],
      owner: 'you',
      involved: [],
      location: 'Blue Bottle Coffee, 5th Ave',
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'social',
    },
    {
      id: 'event-9',
      type: 'event',
      title: 'Board game night',
      startDate: daysFromNow(5),
      allDay: false,
      startTime: '19:00',
      endTime: '22:00',
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['social', 'fun'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'social',
    },
    {
      id: 'event-10',
      type: 'event',
      title: 'Company all-hands',
      description: 'Quarterly company-wide meeting — CEO keynote + department updates.',
      startDate: daysFromNow(8),
      allDay: false,
      startTime: '10:00',
      endTime: '11:30',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['all-hands', 'quarterly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'meeting',
      conferenceLink: 'https://meet.example.com/all-hands',
    },

    // ── Trips ─────────────────────────────────────────────────────────
    {
      id: 'trip-1',
      type: 'trip',
      title: 'Asheville weekend getaway',
      description: 'Hiking, breweries, and relaxation in the Blue Ridge Mountains.',
      startDate: daysFromNow(18),
      endDate: daysFromNow(20),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'travel',
      tags: ['vacation', 'hiking'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r-tr1', timing: '1-week-before', method: 'push' }],
      destination: 'Asheville, NC',
      transportation: 'drive',
      tripStatus: 'booked',
    },
    {
      id: 'trip-2',
      type: 'trip',
      title: 'NYC client visit',
      description: 'On-site meeting with Acme Corp — demo new platform features.',
      startDate: daysFromNow(22),
      endDate: daysFromNow(23),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['client', 'travel'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      references: [],
      reminders: [{ id: 'r-tr2', timing: '2-days-before', method: 'push' }],
      destination: 'New York, NY',
      origin: 'Charlotte, NC',
      transportation: 'flight',
      confirmationNumber: 'AA-7291',
      tripStatus: 'booked',
    },

    // ── Payments ───────────────────────────────────────────────────────
    {
      id: 'pay-1',
      type: 'payment',
      title: 'Rent — February',
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'critical',
      urgency: 'urgent',
      priorityOverride: true,
      urgencyOverride: true,
      category: 'finance',
      tags: ['housing', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r10', timing: '2-days-before', method: 'push' }],
      amount: 1850,
      currency: 'USD',
      payee: 'Greenfield Apartments',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'bank-transfer',
    },
    {
      id: 'pay-2',
      type: 'payment',
      title: 'Figma subscription',
      startDate: daysFromNow(8),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['subscription', 'tools'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 15,
      currency: 'USD',
      payee: 'Figma Inc.',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },
    {
      id: 'pay-3',
      type: 'payment',
      title: 'Electric bill',
      startDate: daysFromNow(14),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'finance',
      tags: ['utilities', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 127.43,
      currency: 'USD',
      payee: 'City Power & Light',
      recurring: true,
      paymentStatus: 'pending',
    },

    {
      id: 'pay-4',
      type: 'payment',
      title: 'Internet bill',
      startDate: daysFromNow(6),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'finance',
      tags: ['utilities', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 79.99,
      currency: 'USD',
      payee: 'Spectrum',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },
    {
      id: 'pay-5',
      type: 'payment',
      title: 'Gym membership',
      startDate: daysFromNow(12),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['fitness', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 45,
      currency: 'USD',
      payee: 'Planet Fitness',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },

    // ── Notes ──────────────────────────────────────────────────────────
    {
      id: 'note-1',
      type: 'note',
      title: 'Project ideas brainstorm',
      description: 'Collection of side-project concepts to explore this quarter.',
      startDate: daysFromNow(-5),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['ideas', 'projects'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      content:
        '1. CLI tool for graph visualization\n2. Recipe tracker PWA\n3. Open-source calendar widget\n4. Markdown-based habit tracker',
      pinned: true,
      linkedItems: [],
    },
    {
      id: 'note-2',
      type: 'note',
      title: 'Meeting notes — roadmap planning',
      description: 'Key takeaways from the Q1 planning session.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['meeting-notes', 'planning'],
      owner: 'you',
      involved: ['alex', 'maya'],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n2-e2',
          entityId: 'event-2',
          entityType: 'event',
          title: 'Design review — new dashboard',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      content:
        '- Ship v2 by end of March\n- Hire 1 more frontend engineer\n- Migrate auth to new provider\n- Deprecate legacy API by April',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-3',
      type: 'note',
      title: 'Gratitude journal — week 5',
      description: 'Weekly reflection.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['journal', 'gratitude'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      content: 'Grateful for: good health, a productive week, a long walk in the park.',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-4',
      type: 'note',
      title: 'Book recommendations',
      description: 'Books suggested by friends and colleagues.',
      startDate: daysFromNow(-10),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['reading', 'books'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n4-t4',
          entityId: 'task-4',
          entityType: 'task',
          title: 'Read chapter 5 — Replication',
          direction: 'incoming',
        },
      ],
      reminders: [],
      content:
        '- "The Pragmatic Programmer" — recommended by Alex\n- "Atomic Habits" — re-read\n- "Staff Engineer" — Will Larson\n- "Designing Data-Intensive Applications" — currently reading',
      pinned: true,
      linkedItems: [],
    },
    {
      id: 'note-5',
      type: 'note',
      title: 'Design tokens research',
      description: 'Notes on design token strategies for the component library.',
      startDate: daysFromNow(-3),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['design-systems', 'research'],
      owner: 'you',
      involved: ['eli'],
      attachments: [],
      references: [],
      reminders: [],
      content:
        '- W3C Design Tokens spec (draft)\n- Style Dictionary vs Theo\n- Figma Variables API integration\n- Token naming: category.property.variant.state',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-6',
      type: 'note',
      title: 'Vacation packing list — spring trip',
      description: 'Essentials for the Asheville trip.',
      startDate: daysFromNow(-7),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['travel', 'lists'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      content: '- Hiking boots\n- Rain jacket\n- Camera + spare battery\n- Trail snacks\n- Journal & pen',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-7',
      type: 'note',
      title: 'API rate-limiting research',
      description: 'Notes from investigating rate-limiting strategies for Sprint 14.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['research', 'backend'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n7-t12',
          entityId: 'task-12',
          entityType: 'task',
          title: 'Sprint 14 — API refactor',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      content:
        '- Token bucket vs sliding window\n- Redis-backed counters\n- Per-user vs per-IP\n- 429 response with Retry-After header',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-8',
      type: 'note',
      title: 'Trip packing — Asheville',
      description: 'Packing list for the weekend getaway.',
      startDate: daysFromNow(16),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['travel', 'lists'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n8-tr1',
          entityId: 'trip-1',
          entityType: 'trip',
          title: 'Asheville weekend getaway',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      content: '- Hiking boots + wool socks\n- Rain shell\n- Binoculars\n- Cooler for road snacks\n- AirTag in luggage',
      pinned: false,
      linkedItems: [],
    },
  ]
}
