/**
 * Seed data for personal calendar items.
 *
 * Used by instant.client.ts to populate the calendarItems namespace
 * on first boot. Dates are relative to "today" so the data always
 * looks fresh.
 */

const today = new Date()
const fmt = (d: Date) => d.toISOString().split('T')[0]!
const daysFromNow = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + n)
  return fmt(d)
}

export interface SeedCalendarItem {
  id: string
  [key: string]: any
}

function buildPitchDeckSlides() {
  return [
    {
      id: 'slide-cover',
      fields: {
        order: 0,
        title: 'Trellis',
        subtitle: 'A semantic operating system for knowledge work.',
        body: '',
        layout: 'title',
        background: '',
        media: '',
        speakerNotes: 'Opening slide.',
      },
    },
    {
      id: 'slide-problem',
      fields: {
        order: 1,
        title: 'The Problem',
        subtitle: 'Your work is trapped in silos.',
        body: [
          '- The average knowledge worker uses **9+ apps** daily',
          '- Data is **locked in proprietary formats**',
          '- AI assistants cannot reason across tools',
          '- Context switching costs **$450B/year**',
        ].join('\n'),
        layout: 'content',
        background: '',
        media: '',
        speakerNotes: '',
      },
    },
    {
      id: 'slide-insight',
      fields: {
        order: 2,
        title: 'The Insight',
        subtitle: '',
        body: '"The next trillion-dollar platforms are systems of record for **decisions**, not just objects."',
        layout: 'quote',
        background: '',
        media: '',
        speakerNotes: '',
      },
    },
    {
      id: 'slide-intro',
      fields: {
        order: 3,
        title: 'Introducing Trellis',
        subtitle: 'NixOS for knowledge work',
        body: [
          '| Concept | Traditional | Trellis |',
          '|---------|------------|---------|',
          '| Data | Locked | Open JSON-LD graph |',
          '| Views | Hard-coded | Declarative projections |',
          '| AI | Bolted-on | First-class citizen |',
        ].join('\n'),
        layout: 'content',
        background: '',
        media: '',
        speakerNotes: '',
      },
    },
    {
      id: 'slide-entity',
      fields: {
        order: 4,
        title: 'Entity System',
        subtitle: 'Four classes cover all knowledge work.',
        body: [
          '**Temporal** — task, event, trip, payment',
          '**Document** — note, file, page, slide deck',
          '**Actor** — person, contact, organization',
          '**Container** — project, folder, collection',
        ].join('\n'),
        layout: 'content',
        background: '',
        media: '',
        speakerNotes: '',
      },
    },
    {
      id: 'slide-vision',
      fields: {
        order: 5,
        title: 'The Vision',
        subtitle: '',
        body: 'Same `.trellis` config = same workspace, anywhere.\n\n**Data you own. Views that adapt. AI that understands.**',
        layout: 'quote',
        background: '',
        media: '',
        speakerNotes: '',
      },
    },
  ]
}

export function getPersonalSeedItems(): SeedCalendarItem[] {
  return [
    // ── Tasks ──────────────────────────────────────────────────────────
    {
      id: 'task-1',
      type: 'task',
      title: 'Finish quarterly review slides',
      description: 'Prepare the slide deck for Q1 review with stakeholders.',
      startDate: daysFromNow(-2),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['presentation', 'quarterly'],
      owner: 'you',
      involved: [],
      folder: 'Work',
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-t1-e2',
          entityId: 'event-2',
          entityType: 'event',
          title: 'Design review — new dashboard',
          direction: 'outgoing',
        },
        { kind: 'file', id: 'ref-t1-f1', name: 'Q1_Slides_Draft.pdf', fileType: 'pdf' },
      ],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [
        { id: 'cl-1', label: 'Draft outline', completed: true, order: 0 },
        { id: 'cl-2', label: 'Add financial charts', completed: false, order: 1 },
        { id: 'cl-3', label: 'Review with manager', completed: false, order: 2 },
      ],
    },
    {
      id: 'task-2',
      type: 'task',
      title: 'Call dentist to confirm appointment',
      description: 'Confirm the cleaning scheduled for next week.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'medium',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['appointment'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r1', timing: '1-hour-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-3',
      type: 'task',
      title: 'Submit expense report',
      description: 'January expenses — receipts already uploaded.',
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['finance'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [{ kind: 'file', id: 'ref-t3-f1', name: 'January_Receipts.xlsx', fileType: 'spreadsheet' }],
      reminders: [{ id: 'r2', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-4',
      type: 'task',
      title: 'Read chapter 5 — Replication',
      description: 'Continue "Designing Data-Intensive Applications".',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['reading', 'engineering'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-t4-n4',
          entityId: 'note-4',
          entityType: 'note',
          title: 'Book recommendations',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [],
    },
    {
      id: 'task-5',
      type: 'task',
      title: 'Water the plants',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['home'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r3', timing: '1-day-before', method: 'push' }],
      recurrence: { frequency: 'weekly', weekdays: [1, 4] },
      taskStatus: 'completed',
      checklist: [],
    },
    {
      id: 'task-6',
      type: 'task',
      title: 'Back up laptop',
      description: 'Full Time Machine backup — last one was 3 weeks ago.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: true,
      category: 'personal',
      tags: ['tech'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'overdue',
      checklist: [],
    },
    {
      id: 'task-7',
      type: 'task',
      title: 'Pick up dry cleaning',
      startDate: daysFromNow(2),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['errands'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r4', timing: '15-min-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-8',
      type: 'task',
      title: 'Send birthday card to Sam',
      description: 'Birthday is on the 15th — mail by the 12th.',
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['birthday'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r5', timing: '2-days-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-9',
      type: 'task',
      title: 'Book annual physical',
      description: 'Schedule appointment with Dr. Patel.',
      startDate: daysFromNow(5),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['doctor'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-10',
      type: 'task',
      title: 'Renew car registration',
      description: 'Registration expires end of month.',
      startDate: daysFromNow(12),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['admin', 'vehicle'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r6', timing: '1-week-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-11',
      type: 'task',
      title: 'Update portfolio website',
      description: 'Add recent project case studies and refresh the design section.',
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['portfolio', 'design'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // Multi-day task: sprint
    {
      id: 'task-12',
      type: 'task',
      title: 'Sprint 14 — API refactor',
      description: 'Refactor authentication endpoints and add rate limiting.',
      startDate: daysFromNow(-1),
      endDate: daysFromNow(4),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['sprint', 'backend'],
      owner: 'you',
      involved: ['alex', 'jordan'],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [
        { id: 'cl-s1', label: 'Audit existing auth endpoints', completed: true, order: 0 },
        { id: 'cl-s2', label: 'Implement rate limiter middleware', completed: false, order: 1 },
        { id: 'cl-s3', label: 'Write integration tests', completed: false, order: 2 },
        { id: 'cl-s4', label: 'Deploy to staging', completed: false, order: 3 },
      ],
    },
    {
      id: 'task-13',
      type: 'task',
      title: 'Morning standup prep',
      description: 'Review Jira board and prepare status update.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '08:45',
      endTime: '09:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['daily', 'routine'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      recurrence: { frequency: 'weekdays' },
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-14',
      type: 'task',
      title: 'Review PR #482 — pagination fix',
      description: "Alex's PR for the infinite scroll pagination bug.",
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['code-review'],
      owner: 'you',
      involved: ['alex'],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-15',
      type: 'task',
      title: 'Grocery run',
      description: 'Weekly groceries — check the meal plan first.',
      startDate: daysFromNow(2),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['errands', 'weekly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      recurrence: { frequency: 'weekly', weekdays: [0] },
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-16',
      type: 'task',
      title: 'Prep slide deck for investor update',
      description: 'Q1 metrics, runway, and product roadmap.',
      startDate: daysFromNow(3),
      endDate: daysFromNow(5),
      allDay: true,
      priority: 'critical',
      urgency: 'urgent',
      priorityOverride: true,
      urgencyOverride: true,
      category: 'work',
      tags: ['presentation', 'investors'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      references: [],
      reminders: [{ id: 'r-t16', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-17',
      type: 'task',
      title: 'Journal — daily reflection',
      description: 'End-of-day reflection and gratitude practice.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '21:00',
      endTime: '21:30',
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['journal', 'daily'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      recurrence: { frequency: 'daily' },
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-18',
      type: 'task',
      title: 'Migrate CI to GitHub Actions',
      description: 'Move from CircleCI to GitHub Actions for cost savings.',
      startDate: daysFromNow(9),
      endDate: daysFromNow(11),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['devops', 'migration'],
      owner: 'you',
      involved: ['eli'],
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Events ─────────────────────────────────────────────────────────
    {
      id: 'event-1',
      type: 'event',
      title: 'Team standup',
      description: 'Daily sync with the product team.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '09:30',
      endTime: '09:45',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['recurring'],
      owner: 'you',
      involved: ['alex', 'jordan'],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'meeting',
      recurrence: { frequency: 'weekdays' },
    },
    {
      id: 'event-2',
      type: 'event',
      title: 'Design review — new dashboard',
      description: 'Present wireframes and get feedback.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '14:00',
      endTime: '15:00',
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['design'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-e2-t1',
          entityId: 'task-1',
          entityType: 'task',
          title: 'Finish quarterly review slides',
          direction: 'incoming',
        },
      ],
      reminders: [{ id: 'r7', timing: '15-min-before', method: 'push' }],
      eventType: 'meeting',
    },
    {
      id: 'event-3',
      type: 'event',
      title: 'Dentist appointment',
      description: 'Cleaning & checkup at Bright Smiles.',
      startDate: daysFromNow(3),
      allDay: false,
      startTime: '14:00',
      endTime: '15:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'appointment',
      tags: ['health'],
      owner: 'you',
      involved: [],
      location: '123 Main St, Suite 200',
      attachments: [],
      references: [],
      reminders: [{ id: 'r8', timing: '1-day-before', method: 'push' }],
      eventType: 'appointment',
    },
    {
      id: 'event-4',
      type: 'event',
      title: 'Design systems workshop',
      description: 'Internal training on component library patterns.',
      startDate: daysFromNow(6),
      allDay: false,
      startTime: '13:00',
      endTime: '16:00',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['training', 'design-systems'],
      owner: 'you',
      involved: ['maya', 'eli'],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'training',
      conferenceLink: 'https://meet.example.com/workshop',
    },
    {
      id: 'event-5',
      type: 'event',
      title: "Mom's birthday dinner",
      description: 'Reservation at Olive Garden, 6 PM.',
      startDate: daysFromNow(10),
      allDay: false,
      startTime: '18:00',
      endTime: '20:00',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['family', 'birthday'],
      owner: 'you',
      involved: ['family'],
      location: 'Olive Garden, Elmwood Ave',
      attachments: [],
      references: [],
      reminders: [{ id: 'r9', timing: '1-day-before', method: 'push' }],
      eventType: 'social',
    },

    // Multi-day event: conference
    {
      id: 'event-6',
      type: 'event',
      title: 'React Summit 2026',
      description: 'Two-day frontend conference — talks, workshops, and networking.',
      startDate: daysFromNow(14),
      endDate: daysFromNow(15),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['conference', 'frontend'],
      owner: 'you',
      involved: ['maya', 'eli'],
      location: 'Convention Center, Downtown',
      attachments: [],
      references: [],
      reminders: [{ id: 'r-e6', timing: '1-week-before', method: 'push' }],
      eventType: 'training',
    },
    {
      id: 'event-7',
      type: 'event',
      title: 'Sprint retrospective',
      description: 'Bi-weekly retro — what went well, what to improve.',
      startDate: daysFromNow(4),
      allDay: false,
      startTime: '16:00',
      endTime: '17:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['retro', 'sprint'],
      owner: 'you',
      involved: ['alex', 'jordan', 'maya'],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'meeting',
    },
    {
      id: 'event-8',
      type: 'event',
      title: 'Lunch with Sam',
      startDate: daysFromNow(2),
      allDay: false,
      startTime: '12:00',
      endTime: '13:00',
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['social'],
      owner: 'you',
      involved: [],
      location: 'Blue Bottle Coffee, 5th Ave',
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'social',
    },
    {
      id: 'event-9',
      type: 'event',
      title: 'Board game night',
      startDate: daysFromNow(5),
      allDay: false,
      startTime: '19:00',
      endTime: '22:00',
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['social', 'fun'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'social',
    },
    {
      id: 'event-10',
      type: 'event',
      title: 'Company all-hands',
      description: 'Quarterly company-wide meeting — CEO keynote + department updates.',
      startDate: daysFromNow(8),
      allDay: false,
      startTime: '10:00',
      endTime: '11:30',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['all-hands', 'quarterly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      eventType: 'meeting',
      conferenceLink: 'https://meet.example.com/all-hands',
    },

    // ── Trips ─────────────────────────────────────────────────────────
    {
      id: 'trip-1',
      type: 'trip',
      title: 'Asheville weekend getaway',
      description: 'Hiking, breweries, and relaxation in the Blue Ridge Mountains.',
      startDate: daysFromNow(18),
      endDate: daysFromNow(20),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'travel',
      tags: ['vacation', 'hiking'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r-tr1', timing: '1-week-before', method: 'push' }],
      destination: 'Asheville, NC',
      transportation: 'drive',
      tripStatus: 'booked',
    },
    {
      id: 'trip-2',
      type: 'trip',
      title: 'NYC client visit',
      description: 'On-site meeting with Acme Corp — demo new platform features.',
      startDate: daysFromNow(22),
      endDate: daysFromNow(23),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['client', 'travel'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      references: [],
      reminders: [{ id: 'r-tr2', timing: '2-days-before', method: 'push' }],
      destination: 'New York, NY',
      origin: 'Charlotte, NC',
      transportation: 'flight',
      confirmationNumber: 'AA-7291',
      tripStatus: 'booked',
    },

    // ── Payments ───────────────────────────────────────────────────────
    {
      id: 'pay-1',
      type: 'payment',
      title: 'Rent — February',
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'critical',
      urgency: 'urgent',
      priorityOverride: true,
      urgencyOverride: true,
      category: 'finance',
      tags: ['housing', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [{ id: 'r10', timing: '2-days-before', method: 'push' }],
      amount: 1850,
      currency: 'USD',
      payee: 'Greenfield Apartments',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'bank-transfer',
    },
    {
      id: 'pay-2',
      type: 'payment',
      title: 'Figma subscription',
      startDate: daysFromNow(8),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['subscription', 'tools'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 15,
      currency: 'USD',
      payee: 'Figma Inc.',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },
    {
      id: 'pay-3',
      type: 'payment',
      title: 'Electric bill',
      startDate: daysFromNow(14),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'finance',
      tags: ['utilities', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 127.43,
      currency: 'USD',
      payee: 'City Power & Light',
      recurring: true,
      paymentStatus: 'pending',
    },

    {
      id: 'pay-4',
      type: 'payment',
      title: 'Internet bill',
      startDate: daysFromNow(6),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'finance',
      tags: ['utilities', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 79.99,
      currency: 'USD',
      payee: 'Spectrum',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },
    {
      id: 'pay-5',
      type: 'payment',
      title: 'Gym membership',
      startDate: daysFromNow(12),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['fitness', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      amount: 45,
      currency: 'USD',
      payee: 'Planet Fitness',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },

    // ── Notes ──────────────────────────────────────────────────────────
    {
      id: 'note-1',
      type: 'note',
      title: 'Project ideas brainstorm',
      description: 'Collection of side-project concepts to explore this quarter.',
      startDate: daysFromNow(-5),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['ideas', 'projects'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      content:
        '1. CLI tool for graph visualization\n2. Recipe tracker PWA\n3. Open-source calendar widget\n4. Markdown-based habit tracker',
      pinned: true,
      linkedItems: [],
    },
    {
      id: 'note-2',
      type: 'note',
      title: 'Meeting notes — roadmap planning',
      description: 'Key takeaways from the Q1 planning session.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['meeting-notes', 'planning'],
      owner: 'you',
      involved: ['alex', 'maya'],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n2-e2',
          entityId: 'event-2',
          entityType: 'event',
          title: 'Design review — new dashboard',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      content:
        '- Ship v2 by end of March\n- Hire 1 more frontend engineer\n- Migrate auth to new provider\n- Deprecate legacy API by April',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-3',
      type: 'note',
      title: 'Gratitude journal — week 5',
      description: 'Weekly reflection.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['journal', 'gratitude'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      content: 'Grateful for: good health, a productive week, a long walk in the park.',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-4',
      type: 'note',
      title: 'Book recommendations',
      description: 'Books suggested by friends and colleagues.',
      startDate: daysFromNow(-10),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['reading', 'books'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n4-t4',
          entityId: 'task-4',
          entityType: 'task',
          title: 'Read chapter 5 — Replication',
          direction: 'incoming',
        },
      ],
      reminders: [],
      content:
        '- "The Pragmatic Programmer" — recommended by Alex\n- "Atomic Habits" — re-read\n- "Staff Engineer" — Will Larson\n- "Designing Data-Intensive Applications" — currently reading',
      pinned: true,
      linkedItems: [],
    },
    {
      id: 'note-5',
      type: 'note',
      title: 'Design tokens research',
      description: 'Notes on design token strategies for the component library.',
      startDate: daysFromNow(-3),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['design-systems', 'research'],
      owner: 'you',
      involved: ['eli'],
      attachments: [],
      references: [],
      reminders: [],
      content:
        '- W3C Design Tokens spec (draft)\n- Style Dictionary vs Theo\n- Figma Variables API integration\n- Token naming: category.property.variant.state',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-6',
      type: 'note',
      title: 'Vacation packing list — spring trip',
      description: 'Essentials for the Asheville trip.',
      startDate: daysFromNow(-7),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['travel', 'lists'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      content: '- Hiking boots\n- Rain jacket\n- Camera + spare battery\n- Trail snacks\n- Journal & pen',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-7',
      type: 'note',
      title: 'API rate-limiting research',
      description: 'Notes from investigating rate-limiting strategies for Sprint 14.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['research', 'backend'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n7-t12',
          entityId: 'task-12',
          entityType: 'task',
          title: 'Sprint 14 — API refactor',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      content:
        '- Token bucket vs sliding window\n- Redis-backed counters\n- Per-user vs per-IP\n- 429 response with Retry-After header',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-8',
      type: 'note',
      title: 'Trip packing — Asheville',
      description: 'Packing list for the weekend getaway.',
      startDate: daysFromNow(16),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['travel', 'lists'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-n8-tr1',
          entityId: 'trip-1',
          entityType: 'trip',
          title: 'Asheville weekend getaway',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      content: '- Hiking boots + wool socks\n- Rain shell\n- Binoculars\n- Cooler for road snacks\n- AirTag in luggage',
      pinned: false,
      linkedItems: [],
    },

    // ── Bookmarks are seeded separately via instant.client.ts migration ──
    // ── People & Organizations are seeded via entitySeedData.ts ──
  ]
}

// ============================================================================
// Trellis Project Tasks — dogfooding the app with real dev work
// ============================================================================

export function getTrellisProjectTasks(): SeedCalendarItem[] {
  return [
    // ── Phase 1: Inline Editing + Mutation Pipeline ─────────────────────
    {
      id: 'trellis-dt-1',
      type: 'task',
      title: 'Build useCollectionTableData composable',
      description:
        'Extract data parsing, mutation, and serialization logic into a shared composable. Provides updateCell, addRow, deleteRows, and reorderColumns.',
      startDate: daysFromNow(0),
      endDate: daysFromNow(2),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-1', 'composable'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [
        { id: 'dt1-cl1', label: 'Parse JSON-LD content into sourceItems + derivedKeys', completed: false, order: 0 },
        { id: 'dt1-cl2', label: 'updateCell(rowIndex, key, value) — mutate & emit', completed: false, order: 1 },
        { id: 'dt1-cl3', label: 'addRow(defaults?) — append new record node', completed: false, order: 2 },
        { id: 'dt1-cl4', label: 'deleteRows(indices[]) — remove record nodes', completed: false, order: 3 },
        { id: 'dt1-cl5', label: 'Wire emit(update:modelValue) for persistence', completed: false, order: 4 },
      ],
    },
    {
      id: 'trellis-dt-2',
      type: 'task',
      title: 'Dual-mode CellRenderer (read + edit)',
      description:
        'Evolve CellRenderer.vue into a component that supports both read mode (type-aware display) and edit mode (inline inputs). Click to edit, Enter/Tab to save, Escape to cancel.',
      startDate: daysFromNow(1),
      endDate: daysFromNow(3),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      dependsOn: ['trellis-dt-1'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-1', 'component'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [
        {
          kind: 'entity',
          id: 'ref-dt2-dt1',
          entityId: 'trellis-dt-1',
          entityType: 'task',
          title: 'Build useCollectionTableData composable',
          direction: 'outgoing',
        },
      ],
      reminders: [],
      taskStatus: 'pending',
      checklist: [
        { id: 'dt2-cl1', label: 'Read mode: current type-aware rendering', completed: true, order: 0 },
        { id: 'dt2-cl2', label: 'Edit mode: text, number, date, checkbox, select inputs', completed: false, order: 1 },
        { id: 'dt2-cl3', label: 'Keyboard nav: Tab → next cell, Enter → cell below, Escape → cancel', completed: false, order: 2 },
        { id: 'dt2-cl4', label: 'Inline validation feedback (red border + message)', completed: false, order: 3 },
      ],
    },
    {
      id: 'trellis-dt-3',
      type: 'task',
      title: 'Wire schema prop through TableView → DataTable',
      description:
        'Pass DatabaseSchema from [slug].vue → TableView → CollectionDataTableProjection so columns use typed field definitions when available.',
      startDate: daysFromNow(2),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-1'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-1', 'wiring'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [
        { id: 'dt3-cl1', label: 'Add schema prop to TableView.vue', completed: false, order: 0 },
        { id: 'dt3-cl2', label: 'Add schema prop to CollectionDataTableProjection.vue', completed: false, order: 1 },
        { id: 'dt3-cl3', label: 'Pass schema from [slug].vue template', completed: false, order: 2 },
        { id: 'dt3-cl4', label: 'Use schema fields for column type info when available', completed: false, order: 3 },
      ],
    },

    // ── Phase 1 Milestone ───────────────────────────────────────────────
    {
      id: 'trellis-dt-m1',
      type: 'task',
      title: '🏁 Milestone: Cells are editable end-to-end',
      dependsOn: ['trellis-dt-1', 'trellis-dt-2', 'trellis-dt-3'],
      description:
        'Phase 1 complete — every cell in the datatable supports click-to-edit with type-aware inputs, changes persist to JSON-LD and auto-save to InstantDB.',
      startDate: daysFromNow(4),
      allDay: true,
      priority: 'critical',
      urgency: 'urgent',
      priorityOverride: true,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'milestone'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [
        { kind: 'entity', id: 'ref-m1-dt1', entityId: 'trellis-dt-1', entityType: 'task', title: 'Build useCollectionTableData composable', direction: 'outgoing' },
        { kind: 'entity', id: 'ref-m1-dt2', entityId: 'trellis-dt-2', entityType: 'task', title: 'Dual-mode CellRenderer (read + edit)', direction: 'outgoing' },
        { kind: 'entity', id: 'ref-m1-dt3', entityId: 'trellis-dt-3', entityType: 'task', title: 'Wire schema prop through TableView', direction: 'outgoing' },
      ],
      reminders: [{ id: 'r-m1', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Phase 2: Column (Property) Management ───────────────────────────
    {
      id: 'trellis-dt-4',
      type: 'task',
      title: 'Column header context menu',
      description:
        'Right-click or chevron dropdown on column headers with: rename, change type, sort asc/desc, filter, hide, delete (with confirmation).',
      startDate: daysFromNow(5),
      endDate: daysFromNow(7),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-m1'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-2', 'component'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [
        { id: 'dt4-cl1', label: 'Create ColumnHeaderMenu.vue component', completed: false, order: 0 },
        { id: 'dt4-cl2', label: 'Rename field inline', completed: false, order: 1 },
        { id: 'dt4-cl3', label: 'Change field type with dropdown', completed: false, order: 2 },
        { id: 'dt4-cl4', label: 'Sort ascending / descending toggle', completed: false, order: 3 },
        { id: 'dt4-cl5', label: 'Delete column with confirmation dialog', completed: false, order: 4 },
      ],
    },
    {
      id: 'trellis-dt-5',
      type: 'task',
      title: '"+ " column button — add new properties',
      description: 'Add a "+" button at the end of column headers that opens a popover with name input + type selector to create a new field.',
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-4'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-2'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'trellis-dt-6',
      type: 'task',
      title: 'Column reorder + schema auto-sync',
      description: 'Drag-to-reorder columns via header handles. Auto-sync renames, type changes, and additions back to DatabaseSchema in InstantDB.',
      startDate: daysFromNow(8),
      endDate: daysFromNow(9),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-4'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-2', 'schema'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Phase 3: Row Operations + Selection ─────────────────────────────
    {
      id: 'trellis-dt-7',
      type: 'task',
      title: 'Checkbox selection column + select-all',
      description: 'Add a leftmost checkbox column with header checkbox for select-all. Track selectedRows as Set<number>.',
      startDate: daysFromNow(10),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-5', 'trellis-dt-6'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-3'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'trellis-dt-8',
      type: 'task',
      title: 'Add / delete / duplicate rows',
      description: 'Bottom-of-table "+ New" row, delete selected rows, duplicate selected rows. Context menu on right-click.',
      startDate: daysFromNow(11),
      endDate: daysFromNow(12),
      allDay: true,
      priority: 'high',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-7'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-3'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'trellis-dt-9',
      type: 'task',
      title: 'Batch operations toolbar',
      description: 'Toolbar actions that appear when rows are selected: delete selected (with count), duplicate selected, bulk update field value.',
      startDate: daysFromNow(13),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-7', 'trellis-dt-8'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-3'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Phase 4: Column Filtering ───────────────────────────────────────
    {
      id: 'trellis-dt-10',
      type: 'task',
      title: 'Per-column filter dropdowns',
      description:
        'Type-aware filter controls per column: text contains/equals, number comparisons, date ranges, select is/is-not, checkbox checked/unchecked.',
      startDate: daysFromNow(14),
      endDate: daysFromNow(16),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-8', 'trellis-dt-9'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-4', 'filtering'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'trellis-dt-11',
      type: 'task',
      title: 'Filter bar with active filter pills',
      description: 'Toolbar filter bar showing removable pills for each active filter. Add filter button to pick column → operator → value.',
      startDate: daysFromNow(16),
      endDate: daysFromNow(17),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-10'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-4', 'filtering'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Phase 5: Data Import ────────────────────────────────────────────
    {
      id: 'trellis-dt-12',
      type: 'task',
      title: 'Import dialog — CSV / Excel / JSON / URL',
      description:
        'Import dialog with tabs: file upload (CSV, Excel, JSON), paste textarea, URL fetch. Column mapping step with preview. Append or replace modes.',
      startDate: daysFromNow(18),
      endDate: daysFromNow(21),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      dependsOn: ['trellis-dt-11'],
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'phase-5', 'import'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [
        { id: 'dt12-cl1', label: 'Add papaparse + xlsx dependencies', completed: false, order: 0 },
        { id: 'dt12-cl2', label: 'File upload tab with drag-and-drop', completed: false, order: 1 },
        { id: 'dt12-cl3', label: 'Paste tab for CSV/JSON text', completed: false, order: 2 },
        { id: 'dt12-cl4', label: 'URL tab with fetch + auto-detect format', completed: false, order: 3 },
        { id: 'dt12-cl5', label: 'Column mapping step with preview', completed: false, order: 4 },
        { id: 'dt12-cl6', label: 'Append vs replace import modes', completed: false, order: 5 },
      ],
    },

    // ── Phase 5 Milestone (all phases shipped) ──────────────────────────
    {
      id: 'trellis-dt-m2',
      type: 'task',
      title: '🏁 Milestone: Interactive DataTable v1 shipped',
      dependsOn: ['trellis-dt-12'],
      description:
        'All 5 phases complete — inline editing, column management, row operations, filtering, and data import are live. The collection datatable is a full Notion/Airtable-style experience.',
      startDate: daysFromNow(22),
      allDay: true,
      priority: 'critical',
      urgency: 'not-urgent',
      priorityOverride: true,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'datatable', 'milestone'],
      owner: 'you',
      involved: [],
      folder: 'Trellis',
      attachments: [],
      references: [
        { kind: 'entity', id: 'ref-m2-m1', entityId: 'trellis-dt-m1', entityType: 'task', title: 'Milestone: Cells are editable end-to-end', direction: 'outgoing' },
        { kind: 'entity', id: 'ref-m2-dt12', entityId: 'trellis-dt-12', entityType: 'task', title: 'Import dialog — CSV / Excel / JSON / URL', direction: 'outgoing' },
      ],
      reminders: [{ id: 'r-m2', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Slide Decks ─────────────────────────────────────────────────────
    {
      id: 'slide-deck-1',
      type: 'slide_deck',
      title: 'Trellis Pitch Deck',
      description: 'Investor pitch deck for Trellis — a semantic operating system for knowledge work.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['trellis', 'pitch', 'presentation'],
      owner: 'you',
      involved: [],
      attachments: [],
      references: [],
      reminders: [],
      pinned: true,
      slides: JSON.stringify(buildPitchDeckSlides()),
      slideTheme: 'dark',
      slideTransition: 'fade',
    },
  ]
}
