/**
 * Seed data for personal calendar items.
 *
 * Used by instant.client.ts to populate the calendarItems namespace
 * on first boot. Dates are relative to "today" so the data always
 * looks fresh.
 */

const today = new Date()
const fmt = (d: Date) => d.toISOString().split('T')[0]!
const daysFromNow = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + n)
  return fmt(d)
}

export interface SeedCalendarItem {
  id: string
  [key: string]: any
}

export function getPersonalSeedItems(): SeedCalendarItem[] {
  return [
    // ── Tasks ──────────────────────────────────────────────────────────
    {
      id: 'task-1',
      type: 'task',
      title: 'Finish quarterly review slides',
      description: 'Prepare the slide deck for Q1 review with stakeholders.',
      startDate: daysFromNow(-2),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['presentation', 'quarterly'],
      owner: 'you',
      involved: [],
      folder: 'Work',
      attachments: [],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [
        { id: 'cl-1', label: 'Draft outline', completed: true, order: 0 },
        { id: 'cl-2', label: 'Add financial charts', completed: false, order: 1 },
        { id: 'cl-3', label: 'Review with manager', completed: false, order: 2 },
      ],
    },
    {
      id: 'task-2',
      type: 'task',
      title: 'Call dentist to confirm appointment',
      description: 'Confirm the cleaning scheduled for next week.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'medium',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['appointment'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r1', timing: '1-hour-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-3',
      type: 'task',
      title: 'Submit expense report',
      description: 'January expenses — receipts already uploaded.',
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['finance'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r2', timing: '1-day-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-4',
      type: 'task',
      title: 'Read chapter 5 — Replication',
      description: 'Continue "Designing Data-Intensive Applications".',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['reading', 'engineering'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      taskStatus: 'in-progress',
      checklist: [],
    },
    {
      id: 'task-5',
      type: 'task',
      title: 'Water the plants',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['home'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r3', timing: '1-day-before', method: 'push' }],
      recurrence: { frequency: 'weekly', weekdays: [1, 4] },
      taskStatus: 'completed',
      checklist: [],
    },
    {
      id: 'task-6',
      type: 'task',
      title: 'Back up laptop',
      description: 'Full Time Machine backup — last one was 3 weeks ago.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: true,
      category: 'personal',
      tags: ['tech'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      taskStatus: 'overdue',
      checklist: [],
    },
    {
      id: 'task-7',
      type: 'task',
      title: 'Pick up dry cleaning',
      startDate: daysFromNow(2),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['errands'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r4', timing: '15-min-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-8',
      type: 'task',
      title: 'Send birthday card to Sam',
      description: "Birthday is on the 15th — mail by the 12th.",
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['birthday'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r5', timing: '2-days-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-9',
      type: 'task',
      title: 'Book annual physical',
      description: 'Schedule appointment with Dr. Patel.',
      startDate: daysFromNow(5),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'health',
      tags: ['doctor'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-10',
      type: 'task',
      title: 'Renew car registration',
      description: 'Registration expires end of month.',
      startDate: daysFromNow(12),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['admin', 'vehicle'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r6', timing: '1-week-before', method: 'push' }],
      taskStatus: 'pending',
      checklist: [],
    },
    {
      id: 'task-11',
      type: 'task',
      title: 'Update portfolio website',
      description: 'Add recent project case studies and refresh the design section.',
      startDate: daysFromNow(7),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['portfolio', 'design'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      taskStatus: 'pending',
      checklist: [],
    },

    // ── Events ─────────────────────────────────────────────────────────
    {
      id: 'event-1',
      type: 'event',
      title: 'Team standup',
      description: 'Daily sync with the product team.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '09:30',
      endTime: '09:45',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['recurring'],
      owner: 'you',
      involved: ['alex', 'jordan'],
      attachments: [],
      reminders: [],
      eventType: 'meeting',
      recurrence: { frequency: 'weekdays' },
    },
    {
      id: 'event-2',
      type: 'event',
      title: 'Design review — new dashboard',
      description: 'Present wireframes and get feedback.',
      startDate: daysFromNow(0),
      allDay: false,
      startTime: '14:00',
      endTime: '15:00',
      priority: 'high',
      urgency: 'urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'meeting',
      tags: ['design'],
      owner: 'you',
      involved: ['maya'],
      attachments: [],
      reminders: [{ id: 'r7', timing: '15-min-before', method: 'push' }],
      eventType: 'meeting',
    },
    {
      id: 'event-3',
      type: 'event',
      title: 'Dentist appointment',
      description: 'Cleaning & checkup at Bright Smiles.',
      startDate: daysFromNow(3),
      allDay: false,
      startTime: '14:00',
      endTime: '15:00',
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'appointment',
      tags: ['health'],
      owner: 'you',
      involved: [],
      location: '123 Main St, Suite 200',
      attachments: [],
      reminders: [{ id: 'r8', timing: '1-day-before', method: 'push' }],
      eventType: 'appointment',
    },
    {
      id: 'event-4',
      type: 'event',
      title: 'Design systems workshop',
      description: 'Internal training on component library patterns.',
      startDate: daysFromNow(6),
      allDay: false,
      startTime: '13:00',
      endTime: '16:00',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['training', 'design-systems'],
      owner: 'you',
      involved: ['maya', 'eli'],
      attachments: [],
      reminders: [],
      eventType: 'training',
      conferenceLink: 'https://meet.example.com/workshop',
    },
    {
      id: 'event-5',
      type: 'event',
      title: "Mom's birthday dinner",
      description: 'Reservation at Olive Garden, 6 PM.',
      startDate: daysFromNow(10),
      allDay: false,
      startTime: '18:00',
      endTime: '20:00',
      priority: 'high',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['family', 'birthday'],
      owner: 'you',
      involved: ['family'],
      location: 'Olive Garden, Elmwood Ave',
      attachments: [],
      reminders: [{ id: 'r9', timing: '1-day-before', method: 'push' }],
      eventType: 'social',
    },

    // ── Payments ───────────────────────────────────────────────────────
    {
      id: 'pay-1',
      type: 'payment',
      title: 'Rent — February',
      startDate: daysFromNow(1),
      allDay: true,
      priority: 'critical',
      urgency: 'urgent',
      priorityOverride: true,
      urgencyOverride: true,
      category: 'finance',
      tags: ['housing', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [{ id: 'r10', timing: '2-days-before', method: 'push' }],
      amount: 1850,
      currency: 'USD',
      payee: 'Greenfield Apartments',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'bank-transfer',
    },
    {
      id: 'pay-2',
      type: 'payment',
      title: 'Figma subscription',
      startDate: daysFromNow(8),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['subscription', 'tools'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      amount: 15,
      currency: 'USD',
      payee: 'Figma Inc.',
      recurring: true,
      paymentStatus: 'pending',
      paymentMethod: 'credit-card',
      recurrence: { frequency: 'monthly' },
    },
    {
      id: 'pay-3',
      type: 'payment',
      title: 'Electric bill',
      startDate: daysFromNow(14),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'finance',
      tags: ['utilities', 'monthly'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      amount: 127.43,
      currency: 'USD',
      payee: 'City Power & Light',
      recurring: true,
      paymentStatus: 'pending',
    },

    // ── Notes ──────────────────────────────────────────────────────────
    {
      id: 'note-1',
      type: 'note',
      title: 'Project ideas brainstorm',
      description: 'Collection of side-project concepts to explore this quarter.',
      startDate: daysFromNow(-5),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['ideas', 'projects'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      content: '1. CLI tool for graph visualization\n2. Recipe tracker PWA\n3. Open-source calendar widget\n4. Markdown-based habit tracker',
      pinned: true,
      linkedItems: [],
    },
    {
      id: 'note-2',
      type: 'note',
      title: 'Meeting notes — roadmap planning',
      description: 'Key takeaways from the Q1 planning session.',
      startDate: daysFromNow(-1),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['meeting-notes', 'planning'],
      owner: 'you',
      involved: ['alex', 'maya'],
      attachments: [],
      reminders: [],
      content: '- Ship v2 by end of March\n- Hire 1 more frontend engineer\n- Migrate auth to new provider\n- Deprecate legacy API by April',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-3',
      type: 'note',
      title: 'Gratitude journal — week 5',
      description: 'Weekly reflection.',
      startDate: daysFromNow(0),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['journal', 'gratitude'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      content: 'Grateful for: good health, a productive week, a long walk in the park.',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-4',
      type: 'note',
      title: 'Book recommendations',
      description: 'Books suggested by friends and colleagues.',
      startDate: daysFromNow(-10),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['reading', 'books'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      content: '- "The Pragmatic Programmer" — recommended by Alex\n- "Atomic Habits" — re-read\n- "Staff Engineer" — Will Larson\n- "Designing Data-Intensive Applications" — currently reading',
      pinned: true,
      linkedItems: [],
    },
    {
      id: 'note-5',
      type: 'note',
      title: 'Design tokens research',
      description: 'Notes on design token strategies for the component library.',
      startDate: daysFromNow(-3),
      allDay: true,
      priority: 'medium',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'work',
      tags: ['design-systems', 'research'],
      owner: 'you',
      involved: ['eli'],
      attachments: [],
      reminders: [],
      content: '- W3C Design Tokens spec (draft)\n- Style Dictionary vs Theo\n- Figma Variables API integration\n- Token naming: category.property.variant.state',
      pinned: false,
      linkedItems: [],
    },
    {
      id: 'note-6',
      type: 'note',
      title: 'Vacation packing list — spring trip',
      description: 'Essentials for the Asheville trip.',
      startDate: daysFromNow(-7),
      allDay: true,
      priority: 'low',
      urgency: 'not-urgent',
      priorityOverride: false,
      urgencyOverride: false,
      category: 'personal',
      tags: ['travel', 'lists'],
      owner: 'you',
      involved: [],
      attachments: [],
      reminders: [],
      content: '- Hiking boots\n- Rain jacket\n- Camera + spare battery\n- Trail snacks\n- Journal & pen',
      pinned: false,
      linkedItems: [],
    },
  ]
}
