/**
 * Default Sidebar Seed Templates
 *
 * These define the initial sidebar tree structure for each scope.
 * They mirror the current hardcoded sections from tql-routes.ts
 * so that migrating to the dynamic sidebar is seamless.
 */

import type { SidebarNodeSeed } from '~/composables/useSidebarTree'

// ── Workspace (default "Personal Knowledge Management" template) ────────

export const DEFAULT_WORKSPACE_SIDEBAR: SidebarNodeSeed[] = [
  {
    id: 'ws-pinned',
    label: 'PINNED',
    icon: 'lucide:pin',
    scope: 'workspace',
    nodeType: 'section',
    locked: true,
    collapsed: false,
    order: 1,
    sectionKey: 'personal-pinned',
    specialItems: 'pinned',
  },
  {
    id: 'ws-today',
    label: 'TODAY',
    icon: 'lucide:sun',
    scope: 'workspace',
    nodeType: 'section',
    locked: true,
    collapsed: false,
    order: 10,
    sectionKey: 'personal-today-section',
    children: [
      {
        id: 'ws-today-overview',
        label: 'Overview',
        icon: 'lucide:layout-dashboard',
        routePath: '/workspace/today',
        scope: 'workspace',
        nodeType: 'item',
        locked: true,
        order: 1,
      },
      {
        id: 'ws-today-feed',
        label: 'Feed',
        icon: 'lucide:rss',
        routePath: '/workspace/feed',
        scope: 'workspace',
        nodeType: 'item',
        locked: true,
        order: 2,
      },
    ],
  },
  {
    id: 'ws-workspace',
    label: 'WORKSPACE',
    icon: 'lucide:briefcase',
    scope: 'workspace',
    nodeType: 'section',
    locked: true,
    collapsed: false,
    order: 20,
    sectionKey: 'personal-workspace',
    children: [
      {
        id: 'ws-calendar',
        label: 'Calendar',
        icon: 'lucide:calendar',
        routePath: '/workspace/calendar',
        entityType: 'event',
        scope: 'workspace',
        nodeType: 'item',
        order: 1,
      },
      {
        id: 'ws-projects',
        label: 'Projects',
        icon: 'lucide:folder-kanban',
        routePath: '/workspace/projects',
        entityType: 'project',
        scope: 'workspace',
        nodeType: 'item',
        order: 2,
      },
      {
        id: 'ws-tasks',
        label: 'Tasks',
        icon: 'lucide:check-square',
        routePath: '/workspace/tasks',
        entityType: 'task',
        scope: 'workspace',
        nodeType: 'item',
        order: 3,
      },
      {
        id: 'ws-sprints',
        label: 'Sprints',
        icon: 'lucide:zap',
        routePath: '/workspace/sprints',
        entityType: 'sprint',
        scope: 'workspace',
        nodeType: 'item',
        order: 4,
      },
      {
        id: 'ws-milestones',
        label: 'Milestones',
        icon: 'lucide:flag',
        routePath: '/workspace/milestones',
        entityType: 'milestone',
        scope: 'workspace',
        nodeType: 'item',
        order: 5,
      },
      {
        id: 'ws-notes',
        label: 'Notes',
        icon: 'lucide:sticky-note',
        routePath: '/workspace/notes',
        entityType: 'note',
        scope: 'workspace',
        nodeType: 'item',
        order: 6,
      },
    ],
  },
  {
    id: 'ws-personal',
    label: 'PERSONAL',
    icon: 'lucide:user',
    scope: 'workspace',
    nodeType: 'section',
    locked: true,
    collapsed: false,
    order: 25,
    sectionKey: 'personal-personal',
    children: [
      {
        id: 'ws-people',
        label: 'People',
        icon: 'lucide:users',
        routePath: '/workspace/people',
        entityType: 'person',
        scope: 'workspace',
        nodeType: 'item',
        order: 1,
      },
      {
        id: 'ws-goals',
        label: 'Goals',
        icon: 'lucide:target',
        routePath: '/workspace/goals',
        entityType: 'goal',
        scope: 'workspace',
        nodeType: 'item',
        order: 2,
      },
      {
        id: 'ws-budgets',
        label: 'Budgets',
        icon: 'lucide:wallet',
        routePath: '/workspace/budgets',
        entityType: 'budget',
        scope: 'workspace',
        nodeType: 'item',
        order: 3,
      },
      {
        id: 'ws-places',
        label: 'Places',
        icon: 'lucide:map-pin',
        routePath: '/workspace/places',
        scope: 'workspace',
        nodeType: 'item',
        order: 4,
      },
    ],
  },
  {
    id: 'ws-library',
    label: 'LIBRARY',
    icon: 'lucide:library',
    scope: 'workspace',
    nodeType: 'section',
    locked: true,
    collapsed: false,
    order: 30,
    sectionKey: 'personal-library',
    children: [
      {
        id: 'ws-documents',
        label: 'Documents',
        icon: 'lucide:file-text',
        routePath: '/workspace/documents',
        entityType: 'page',
        scope: 'workspace',
        nodeType: 'item',
        order: 1,
      },
      {
        id: 'ws-bookmarks',
        label: 'Bookmarks',
        icon: 'lucide:bookmark',
        routePath: '/workspace/bookmarks',
        entityType: 'bookmark',
        scope: 'workspace',
        nodeType: 'item',
        order: 2,
      },
    ],
  },
  {
    id: 'ws-pages',
    label: 'PAGES',
    icon: 'lucide:file-text',
    scope: 'workspace',
    nodeType: 'section',
    locked: true,
    collapsed: false,
    order: 40,
    sectionKey: 'personal-pages',
    specialItems: 'pages',
    editable: true,
  },
]
