/**
 * TQL Ontology Definitions
 *
 * Canonical schema definitions for every entity type in the Trellis system.
 * Each ontology defines both the data schema (fields) and UI metadata
 * (icon, color, projections, panels, property fields).
 *
 * The client fetches these from GET /api/graph/ontologies and derives
 * EntityTypeConfig objects. This is the single source of truth for what
 * entity types exist and how they look/behave.
 *
 * Also includes the legacy polymorphic entity namespace ontology for backward
 * compat with TQL queries (FIND <ENTITY_NAMESPACE> AS ?t WHERE ?t.type = "task").
 */

import type { SchemaDefinition, PropertyValueSpecification, WorkspaceConfig } from '@turtle.tech/trellis-kernel'
import { getRouteDefinitions } from './trellis-shell-routes'
import { ENTITY_NAMESPACE, entityQuery } from '../../app/lib/entity-namespace'

const DEFAULT_DEV_PORT = 1414
const parsedDevPort = Number.parseInt(process.env.TRELLIS_PORT || '', 10)
const DEV_PORT = Number.isFinite(parsedDevPort) ? parsedDevPort : DEFAULT_DEV_PORT

// ============================================================================
// Field helpers — compact builders for PropertyValueSpecification
// ============================================================================

type PVS = PropertyValueSpecification
const f = (name: string, valueType: PVS['valueType'], opts?: Partial<Omit<PVS, 'name' | 'valueType'>>): PVS =>
  ({ name, valueType, ...opts }) as PVS

// ── Shared field sets (per class) ──────────────────────────────────────────

const baseFields = (): PVS[] => [
  f('title', 'title', { required: true }),
  f('description', 'rich_text'),
  f('tags', 'multi_select', {
    icon: 'lucide:hash',
    group: 'annotation',
    display: 'inline-input',
    editable: true,
    defaultValue: [],
  }),
  f('owner', 'people', { icon: 'lucide:user', group: 'people', display: 'popover', editable: true }),
  f('involved', 'people', { icon: 'lucide:users', group: 'people', display: 'popover', editable: true }),
  f('category', 'select', {
    icon: 'lucide:tag',
    group: 'classification',
    display: 'popover',
    editable: true,
    selectOptions: [
      'general',
      'work',
      'personal',
      'meeting',
      'review',
      'appointment',
      'deadline',
      'health',
      'finance',
      'travel',
    ],
  }),
  f('createdAt', 'date'),
  f('updatedAt', 'date'),
]

const temporalFields = (): PVS[] => [
  f('startDate', 'date', { icon: 'lucide:calendar', group: 'scheduling', display: 'inline-input', editable: true }),
  f('endDate', 'date', { icon: 'lucide:calendar-range', group: 'scheduling', display: 'inline-input', editable: true }),
  f('allDay', 'checkbox', {
    icon: 'lucide:sun',
    group: 'scheduling',
    display: 'toggle',
    editable: true,
    defaultValue: false,
  }),
  f('startTime', 'rich_text'),
  f('endTime', 'rich_text'),
  f('priority', 'select', {
    selectOptions: ['critical', 'high', 'medium', 'low'],
    icon: 'lucide:minus',
    group: 'triage',
    display: 'popover',
    editable: true,
    computed: true,
  }),
  f('urgency', 'select', {
    selectOptions: ['urgent', 'not-urgent'],
    icon: 'lucide:clock',
    group: 'triage',
    display: 'popover',
    editable: true,
    computed: true,
  }),
  f('priorityOverride', 'checkbox'),
  f('urgencyOverride', 'checkbox'),
]

const documentFields = (): PVS[] => [
  f('content', 'rich_text'),
  f('pinned', 'checkbox', {
    icon: 'lucide:pin',
    group: 'annotation',
    display: 'toggle',
    editable: true,
    defaultValue: false,
  }),
]

const actorFields = (): PVS[] => [
  f('email', 'email'),
  f('phone', 'phone_number'),
  f('avatar', 'url'),
  f('role', 'rich_text'),
]

const containerFields = (): PVS[] => [
  f('status', 'select', {
    selectOptions: ['active', 'archived', 'completed', 'on-hold'],
    icon: 'lucide:circle-dot',
    group: 'triage',
    display: 'popover',
    editable: true,
  }),
  f('parentId', 'rich_text'),
  f('progress', 'number'),
]

// ============================================================================
// Per-Type Ontologies — Temporal
// ============================================================================

const taskOntology: SchemaDefinition = {
  '@id': 'trellis:schema/task',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Task',
  labelPlural: 'Tasks',
  icon: 'lucide:check-square',
  color: 'blue',
  projections: ['kanban', 'calendar', 'list', 'table', 'timeline'],
  defaultProjection: 'kanban',
  dialogShell: 'temporal',
  panels: { properties: 'TaskProperties', content: 'TaskContent', footerActions: ['complete', 'archive', 'delete'] },
  propertyFieldIds: [
    'type',
    'status',
    'startDate',
    'endDate',
    'allDay',
    'timeRange',
    'priority',
    'urgency',
    'category',
    'owner',
    'involved',
    'folder',
    'tags',
  ],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description', 'notes'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('taskStatus', 'select', {
      selectOptions: ['pending', 'in-progress', 'on-track', 'due-soon', 'overdue', 'completed'],
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
    f('folder', 'rich_text', { icon: 'lucide:folder', group: 'classification', display: 'popover', editable: true }),
    f('notes', 'rich_text'),
    f('checklistContent', 'rich_text'),
  ],
}

const eventOntology: SchemaDefinition = {
  '@id': 'trellis:schema/event',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Event',
  labelPlural: 'Events',
  icon: 'lucide:calendar',
  color: 'purple',
  projections: ['calendar', 'timeline', 'list', 'table'],
  defaultProjection: 'calendar',
  dialogShell: 'temporal',
  panels: { properties: 'EventProperties', content: 'EventContent', footerActions: ['duplicate', 'delete'] },
  propertyFieldIds: ['type', 'startDate', 'endDate', 'allDay', 'timeRange', 'category', 'owner', 'involved', 'tags', 'latitude', 'longitude'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description', 'location'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('location', 'rich_text'),
    f('latitude', 'number', { display: 'inline-input' }),
    f('longitude', 'number', { display: 'inline-input' }),
    f('conferenceLink', 'url'),
    f('eventSubtype', 'select', {
      selectOptions: ['meeting', 'appointment', 'training', 'deadline', 'social', 'other'],
    }),
  ],
}

const tripOntology: SchemaDefinition = {
  '@id': 'trellis:schema/trip',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Trip',
  labelPlural: 'Trips',
  icon: 'lucide:plane',
  color: 'cyan',
  projections: ['calendar', 'timeline', 'list', 'card-grid'],
  defaultProjection: 'calendar',
  dialogShell: 'temporal',
  panels: { properties: 'TripProperties', content: 'TripContent', footerActions: ['duplicate', 'archive', 'delete'] },
  propertyFieldIds: ['type', 'startDate', 'endDate', 'allDay', 'category', 'owner', 'involved', 'tags', 'latitude', 'longitude'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'destination', 'origin'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('origin', 'rich_text'),
    f('destination', 'rich_text'),
    f('latitude', 'number', { display: 'inline-input' }),
    f('longitude', 'number', { display: 'inline-input' }),
    f('transportation', 'select', { selectOptions: ['flight', 'drive', 'train', 'bus', 'other'] }),
    f('budget', 'number'),
    f('currency', 'rich_text'),
    f('confirmationNumber', 'rich_text'),
    f('tripStatus', 'select', { selectOptions: ['planning', 'booked', 'in-progress', 'completed', 'cancelled'] }),
  ],
}

const paymentOntology: SchemaDefinition = {
  '@id': 'trellis:schema/payment',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Payment',
  labelPlural: 'Payments',
  icon: 'lucide:credit-card',
  color: 'emerald',
  projections: ['calendar', 'list', 'table'],
  defaultProjection: 'table',
  dialogShell: 'temporal',
  panels: { properties: 'PaymentProperties', content: 'PaymentContent', footerActions: ['markPaid', 'void', 'delete'] },
  propertyFieldIds: ['type', 'startDate', 'allDay', 'priority', 'urgency', 'category', 'owner', 'tags'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'payee', 'invoiceNumber'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('amount', 'number'),
    f('currency', 'rich_text'),
    f('payee', 'rich_text'),
    f('paymentMethod', 'rich_text'),
    f('recurring', 'checkbox'),
    f('paymentStatus', 'select', { selectOptions: ['pending', 'paid', 'overdue', 'cancelled'] }),
    f('invoiceNumber', 'rich_text'),
  ],
}

const appointmentOntology: SchemaDefinition = {
  '@id': 'trellis:schema/appointment',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Appointment',
  labelPlural: 'Appointments',
  icon: 'lucide:stethoscope',
  color: 'rose',
  projections: ['calendar', 'list', 'table', 'timeline'],
  defaultProjection: 'calendar',
  dialogShell: 'temporal',
  panels: {
    properties: 'AppointmentProperties',
    content: 'AppointmentContent',
    footerActions: ['confirm', 'reschedule', 'cancel', 'delete'],
  },
  propertyFieldIds: ['type', 'startDate', 'endDate', 'timeRange', 'category', 'owner', 'tags', 'latitude', 'longitude'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'provider', 'location', 'specialty'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('provider', 'rich_text'),
    f('location', 'rich_text'),
    f('latitude', 'number', { display: 'inline-input' }),
    f('longitude', 'number', { display: 'inline-input' }),
    f('specialty', 'rich_text'),
    f('insurance', 'rich_text'),
    f('copay', 'number'),
    f('visitNotes', 'rich_text'),
    f('followUpDate', 'date'),
  ],
}

const reminderOntology: SchemaDefinition = {
  '@id': 'trellis:schema/reminder',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Reminder',
  labelPlural: 'Reminders',
  icon: 'lucide:bell',
  color: 'amber',
  projections: ['list', 'calendar'],
  defaultProjection: 'list',
  dialogShell: 'temporal',
  panels: {
    properties: 'ReminderProperties',
    content: 'ReminderContent',
    footerActions: ['acknowledge', 'snooze', 'delete'],
  },
  propertyFieldIds: ['type', 'startDate', 'timeRange', 'category', 'owner', 'tags'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description'],
  fields: [...baseFields(), ...temporalFields(), f('acknowledged', 'checkbox')],
}

const deadlineOntology: SchemaDefinition = {
  '@id': 'trellis:schema/deadline',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Deadline',
  labelPlural: 'Deadlines',
  icon: 'lucide:alarm-clock',
  color: 'red',
  projections: ['calendar', 'timeline', 'list'],
  defaultProjection: 'calendar',
  dialogShell: 'temporal',
  panels: {
    properties: 'DeadlineProperties',
    content: 'DeadlineContent',
    footerActions: ['markMet', 'extend', 'delete'],
  },
  propertyFieldIds: ['type', 'startDate', 'allDay', 'priority', 'urgency', 'category', 'owner', 'tags'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('sourceEntity', 'rich_text'),
    f('sourceType', 'rich_text'),
    f('isMet', 'checkbox'),
  ],
}

const milestoneOntology: SchemaDefinition = {
  '@id': 'trellis:schema/milestone',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Milestone',
  labelPlural: 'Milestones',
  icon: 'lucide:flag',
  color: 'orange',
  projections: ['timeline', 'list', 'calendar'],
  defaultProjection: 'timeline',
  dialogShell: 'temporal',
  panels: { properties: 'MilestoneProperties', content: 'MilestoneContent', footerActions: ['achieve', 'delete'] },
  propertyFieldIds: ['type', 'startDate', 'allDay', 'category', 'owner', 'tags'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description'],
  fields: [...baseFields(), ...temporalFields(), f('projectId', 'rich_text'), f('achieved', 'checkbox')],
}

const sprintOntology: SchemaDefinition = {
  '@id': 'trellis:schema/sprint',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Sprint',
  labelPlural: 'Sprints',
  icon: 'lucide:zap',
  color: 'violet',
  projections: ['list', 'kanban', 'timeline'],
  defaultProjection: 'list',
  dialogShell: 'temporal',
  panels: { properties: 'SprintProperties', content: 'SprintContent', footerActions: ['complete', 'cancel', 'delete'] },
  propertyFieldIds: ['type', 'startDate', 'endDate', 'allDay', 'category', 'owner', 'involved', 'tags'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description', 'sprintGoal'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('sprintGoal', 'rich_text'),
    f('sprintStatus', 'select', {
      selectOptions: ['planning', 'active', 'completed', 'cancelled'],
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
    f('velocity', 'number'),
    f('checklistContent', 'rich_text'),
  ],
}

const budgetOntology: SchemaDefinition = {
  '@id': 'trellis:schema/budget',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Budget',
  labelPlural: 'Budgets',
  icon: 'lucide:wallet',
  color: 'emerald',
  projections: ['list', 'table'],
  defaultProjection: 'list',
  dialogShell: 'temporal',
  panels: { properties: 'BudgetProperties', content: 'BudgetContent', footerActions: ['close', 'archive', 'delete'] },
  propertyFieldIds: ['type', 'startDate', 'endDate', 'category', 'owner', 'tags'],
  defaultSortField: 'startDate',
  searchFields: ['title', 'description'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('amount', 'number'),
    f('currency', 'rich_text'),
    f('budgetStatus', 'select', {
      selectOptions: ['draft', 'active', 'closed', 'over-budget'],
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
  ],
}

const expenseOntology: SchemaDefinition = {
  '@id': 'trellis:schema/expense',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Expense',
  labelPlural: 'Expenses',
  icon: 'lucide:receipt',
  color: 'amber',
  projections: ['table', 'list'],
  defaultProjection: 'table',
  dialogShell: 'temporal',
  panels: { properties: 'ExpenseProperties', content: 'ExpenseContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'category'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('category', 'select', {
      selectOptions: ['Infra', 'Travel', 'Tools', 'GTM'],
    }),
    f('budgeted', 'number'),
    f('spent', 'number'),
    f('quarter', 'rich_text'),
  ],
}

const githubIssueOntology: SchemaDefinition = {
  '@id': 'trellis:schema/github_issue',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Issue',
  labelPlural: 'Issues',
  icon: 'lucide:circle-dot',
  color: 'green',
  projections: ['kanban', 'list', 'table', 'timeline'],
  defaultProjection: 'list',
  dialogShell: 'temporal',
  panels: {
    properties: 'GithubIssueProperties',
    content: 'GithubIssueContent',
    footerActions: ['close', 'archive', 'delete'],
  },
  propertyFieldIds: [
    'type',
    'issueState',
    'priority',
    'labels',
    'assignees',
    'milestone',
    'repositoryFullName',
    'tags',
  ],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'body', 'labels', 'authorLogin', 'repositoryFullName'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('number', 'number', { icon: 'lucide:hash', group: 'identifiers', display: 'inline-input' }),
    f('body', 'rich_text'),
    f('issueState', 'select', {
      selectOptions: ['open', 'closed'],
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
    f('stateReason', 'select', {
      selectOptions: ['completed', 'not_planned', 'reopened'],
      icon: 'lucide:info',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
    f('labels', 'multi_select', { icon: 'lucide:tag', group: 'classification', display: 'popover', editable: true }),
    f('authorLogin', 'rich_text', { icon: 'lucide:user', group: 'people', display: 'inline-input' }),
    f('authorAvatarUrl', 'url'),
    f('assignees', 'multi_select', { icon: 'lucide:users', group: 'people', display: 'popover', editable: true }),
    f('milestone', 'rich_text', { icon: 'lucide:flag', group: 'classification', display: 'inline-input' }),
    f('commentsCount', 'number', { icon: 'lucide:message-square' }),
    f('closedAt', 'date', { icon: 'lucide:calendar-check', group: 'scheduling', display: 'inline-input' }),
    f('url', 'url', { icon: 'lucide:external-link', group: 'identifiers', display: 'inline-input' }),
    f('repositoryFullName', 'rich_text', {
      icon: 'lucide:git-branch',
      group: 'classification',
      display: 'inline-input',
    }),
    f('repositoryId', 'rich_text'),
    f('githubIssueId', 'rich_text'),
    f('source', 'rich_text'),
    f('connectionId', 'rich_text'),
  ],
}

const pullRequestOntology: SchemaDefinition = {
  '@id': 'trellis:schema/pull_request',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'temporal',
  label: 'Pull Request',
  labelPlural: 'Pull Requests',
  icon: 'lucide:git-pull-request',
  color: 'violet',
  projections: ['kanban', 'list', 'table', 'timeline'],
  defaultProjection: 'list',
  dialogShell: 'temporal',
  panels: {
    properties: 'PullRequestProperties',
    content: 'PullRequestContent',
    footerActions: ['merge', 'close', 'delete'],
  },
  propertyFieldIds: [
    'type',
    'prState',
    'priority',
    'labels',
    'reviewers',
    'assignees',
    'baseBranch',
    'headBranch',
    'repositoryFullName',
    'tags',
  ],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'body', 'labels', 'authorLogin', 'repositoryFullName'],
  fields: [
    ...baseFields(),
    ...temporalFields(),
    f('number', 'number', { icon: 'lucide:hash', group: 'identifiers', display: 'inline-input' }),
    f('body', 'rich_text'),
    f('prState', 'select', {
      selectOptions: ['open', 'closed', 'merged', 'draft'],
      icon: 'lucide:git-pull-request',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
    f('draft', 'checkbox', { icon: 'lucide:git-pull-request-draft', group: 'triage', display: 'toggle' }),
    f('merged', 'checkbox', { icon: 'lucide:git-merge', group: 'triage', display: 'toggle' }),
    f('mergeable', 'select', {
      selectOptions: ['mergeable', 'conflicting', 'unknown'],
      icon: 'lucide:git-merge',
      group: 'triage',
      display: 'popover',
    }),
    f('mergedAt', 'date', { icon: 'lucide:git-merge', group: 'scheduling', display: 'inline-input' }),
    f('closedAt', 'date', { icon: 'lucide:calendar-check', group: 'scheduling', display: 'inline-input' }),
    f('mergedByLogin', 'rich_text', { icon: 'lucide:user-check', group: 'people' }),
    f('authorLogin', 'rich_text', { icon: 'lucide:user', group: 'people', display: 'inline-input' }),
    f('authorAvatarUrl', 'url'),
    f('assignees', 'multi_select', { icon: 'lucide:users', group: 'people', display: 'popover', editable: true }),
    f('reviewers', 'multi_select', {
      icon: 'lucide:user-check',
      group: 'people',
      display: 'popover',
      editable: true,
    }),
    f('requestedReviewers', 'multi_select', {
      icon: 'lucide:user-plus',
      group: 'people',
      display: 'popover',
      editable: true,
    }),
    f('labels', 'multi_select', { icon: 'lucide:tag', group: 'classification', display: 'popover', editable: true }),
    f('milestone', 'rich_text', { icon: 'lucide:flag', group: 'classification', display: 'inline-input' }),
    f('baseBranch', 'rich_text', { icon: 'lucide:git-branch', group: 'git', display: 'inline-input' }),
    f('headBranch', 'rich_text', { icon: 'lucide:git-branch', group: 'git', display: 'inline-input' }),
    f('baseSha', 'rich_text'),
    f('headSha', 'rich_text'),
    f('commits', 'number', { icon: 'lucide:git-commit' }),
    f('additions', 'number'),
    f('deletions', 'number'),
    f('changedFiles', 'number', { icon: 'lucide:file-diff' }),
    f('commentsCount', 'number', { icon: 'lucide:message-square' }),
    f('reviewCommentsCount', 'number', { icon: 'lucide:message-square-reply' }),
    f('url', 'url', { icon: 'lucide:external-link', group: 'identifiers', display: 'inline-input' }),
    f('repositoryFullName', 'rich_text', {
      icon: 'lucide:git-branch',
      group: 'classification',
      display: 'inline-input',
    }),
    f('repositoryId', 'rich_text'),
    f('githubPrId', 'rich_text'),
    f('source', 'rich_text'),
    f('connectionId', 'rich_text'),
  ],
}

// ============================================================================
// Per-Type Ontologies — Document
// ============================================================================

const noteOntology: SchemaDefinition = {
  '@id': 'trellis:schema/note',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Note',
  labelPlural: 'Notes',
  icon: 'lucide:sticky-note',
  color: 'yellow',
  projections: ['card-grid', 'list', 'table'],
  defaultProjection: 'card-grid',
  dialogShell: 'document',
  panels: { properties: 'NoteProperties', content: 'NoteContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'pin', 'category', 'owner', 'involved', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'content', 'description'],
  fields: [...baseFields(), ...documentFields()],
}

const fileOntology: SchemaDefinition = {
  '@id': 'trellis:schema/file',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'File',
  labelPlural: 'Files',
  icon: 'lucide:file',
  color: 'slate',
  projections: ['card-grid', 'list', 'table'],
  defaultProjection: 'card-grid',
  dialogShell: 'document',
  panels: { properties: 'FileProperties', content: 'FileContent', footerActions: ['download', 'share', 'delete'] },
  propertyFieldIds: ['type', 'pin', 'category', 'owner', 'involved', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'description'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('mimeType', 'rich_text'),
    f('sizeBytes', 'number'),
    f('url', 'url'),
    f('storagePath', 'rich_text'),
  ],
}

const pageOntology: SchemaDefinition = {
  '@id': 'trellis:schema/page',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Page',
  labelPlural: 'Pages',
  icon: 'lucide:book-open',
  color: 'indigo',
  projections: ['list', 'card-grid'],
  defaultProjection: 'list',
  dialogShell: 'document',
  panels: { properties: 'PageProperties', content: 'PageContent', footerActions: ['publish', 'archive', 'delete'] },
  propertyFieldIds: ['type', 'pin', 'category', 'owner', 'involved', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'content', 'description'],
  fields: [...baseFields(), ...documentFields(), f('slug', 'rich_text'), f('isPublished', 'checkbox')],
}

const templateOntology: SchemaDefinition = {
  '@id': 'trellis:schema/template',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Template',
  labelPlural: 'Templates',
  icon: 'lucide:copy',
  color: 'violet',
  projections: ['list', 'card-grid', 'table'],
  defaultProjection: 'list',
  dialogShell: 'document',
  panels: {
    properties: 'TemplateProperties',
    content: 'TemplateContent',
    footerActions: ['useTemplate', 'duplicate', 'delete'],
  },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description'],
  fields: [...baseFields(), ...documentFields(), f('templateFor', 'rich_text')],
}

const slideDeckOntology: SchemaDefinition = {
  '@id': 'trellis:schema/slide_deck',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Slide Deck',
  labelPlural: 'Slide Decks',
  icon: 'lucide:presentation',
  color: 'rose',
  projections: ['slide-deck', 'list', 'table'],
  defaultProjection: 'slide-deck',
  dialogShell: 'document',
  panels: {
    properties: 'SlideDeckProperties',
    content: 'SlideDeckContent',
    footerActions: ['present', 'duplicate', 'delete'],
  },
  propertyFieldIds: ['type', 'pin', 'category', 'owner', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'description'],
  fields: [...baseFields(), ...documentFields()],
}

const sheetOntology: SchemaDefinition = {
  '@id': 'trellis:schema/sheet',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Sheet',
  labelPlural: 'Sheets',
  icon: 'lucide:table-2',
  color: 'emerald',
  projections: ['table', 'list'],
  defaultProjection: 'table',
  dialogShell: 'document',
  panels: {
    properties: 'SheetProperties',
    content: 'SheetContent',
    footerActions: ['duplicate', 'delete'],
  },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('query', 'rich_text', { required: true }),
    f('columns', 'rich_text', { required: true }),
    f('formulas', 'rich_text'),
    f('zoneId', 'rich_text'),
    f('facilityId', 'rich_text'),
  ],
}

const canvasOntology: SchemaDefinition = {
  '@id': 'trellis:schema/canvas',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Canvas',
  labelPlural: 'Canvases',
  icon: 'lucide:layout-dashboard',
  color: 'cyan',
  projections: ['canvas', 'list', 'table'],
  defaultProjection: 'canvas',
  dialogShell: 'document',
  panels: {
    properties: 'DocumentPropertiesTab',
    content: 'CanvasContent',
    footerActions: ['duplicate', 'delete'],
  },
  propertyFieldIds: ['type', 'pin', 'category', 'owner', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'description'],
  fields: [...baseFields(), ...documentFields(), f('layout', 'rich_text')],
}

const diagramOntology: SchemaDefinition = {
  '@id': 'trellis:schema/diagram',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Diagram',
  labelPlural: 'Diagrams',
  icon: 'lucide:workflow',
  color: 'teal',
  projections: ['card-grid', 'list', 'table'],
  defaultProjection: 'card-grid',
  dialogShell: 'document',
  panels: { properties: 'DiagramProperties', content: 'DiagramContent', footerActions: ['pin', 'duplicate', 'delete'] },
  propertyFieldIds: ['type', 'pin', 'category', 'owner', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'description', 'content'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('diagramType', 'select', {
      selectOptions: ['flowchart', 'sequence', 'gantt', 'class', 'er', 'mindmap', 'other'],
    }),
  ],
}

const bookmarkOntology: SchemaDefinition = {
  '@id': 'trellis:schema/bookmark',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Bookmark',
  labelPlural: 'Bookmarks',
  icon: 'lucide:bookmark',
  color: 'sky',
  projections: ['card-grid', 'list', 'table', 'moodboard'],
  defaultProjection: 'card-grid',
  dialogShell: 'document',
  panels: { properties: 'BookmarkProperties', content: 'BookmarkContent', footerActions: ['pin', 'archive', 'delete'] },
  propertyFieldIds: ['pin', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'url', 'description', 'siteName', 'excerpt'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('url', 'url', { required: true }),
    f('favicon', 'url'),
    f('thumbnail', 'url'),
    f('siteName', 'rich_text'),
    f('excerpt', 'rich_text'),
  ],
}

const emailOntology: SchemaDefinition = {
  '@id': 'trellis:schema/email',
  '@type': 'trellis:Schema',
  version: '1.1.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Email',
  labelPlural: 'Emails',
  icon: 'lucide:mail',
  color: 'red',
  projections: ['list', 'table', 'card-grid'],
  defaultProjection: 'list',
  dialogShell: 'document',
  panels: { properties: 'EmailProperties', content: 'EmailContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['from', 'to', 'date', 'labelIds', 'priority', 'aiLabels', 'tags'],
  defaultSortField: 'date',
  searchFields: ['title', 'subject', 'from', 'to', 'snippet', 'bodyText', 'summary', 'aiLabels'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('subject', 'rich_text'),
    f('snippet', 'rich_text'),
    f('from', 'email'),
    f('to', 'rich_text'),
    f('cc', 'rich_text'),
    f('bcc', 'rich_text'),
    f('date', 'date'),
    f('labelIds', 'multi_select'),
    f('threadId', 'rich_text'),
    f('messageId', 'rich_text'),
    f('isRead', 'checkbox'),
    f('isStarred', 'checkbox'),
    f('bodyText', 'rich_text'),
    f('bodyHtml', 'rich_text'),
    f('source', 'rich_text'),
    f('gmailMessageId', 'rich_text'),
    f('gmailThreadId', 'rich_text'),
    // ── AI enrichment (populated by gmail-notifier on ingest) ──────
    f('summary', 'rich_text'),
    f('summaryGeneratedAt', 'date'),
    f('aiSuggestions', 'rich_text'),
    f('aiSuggestedTags', 'multi_select'),
    f('aiTypeProposals', 'rich_text'),
    f('aiLabels', 'multi_select'),
    f('aiScannedAt', 'date'),
    f('priority', 'select', {
      selectOptions: ['critical', 'high', 'medium', 'low'],
      defaultValue: 'medium',
      icon: 'lucide:flag',
    }),
  ],
}

// ============================================================================
// Per-Type Ontologies — Actor
// ============================================================================

const personOntology: SchemaDefinition = {
  '@id': 'trellis:schema/person',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'actor',
  label: 'Person',
  labelPlural: 'People',
  icon: 'lucide:user',
  color: 'sky',
  projections: ['table', 'card-grid', 'list', 'graph'],
  defaultProjection: 'table',
  dialogShell: 'actor',
  panels: { properties: 'PersonProperties', content: 'PersonContent', footerActions: ['message', 'archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'email', 'jobTitle', 'organization', 'content'],
  fields: [...baseFields(), ...actorFields(), f('content', 'rich_text'), f('organization', 'rich_text'), f('jobTitle', 'rich_text')],
}

const contactOntology: SchemaDefinition = {
  '@id': 'trellis:schema/contact',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'actor',
  label: 'Contact',
  labelPlural: 'Contacts',
  icon: 'lucide:contact',
  color: 'teal',
  projections: ['table', 'card-grid', 'list'],
  defaultProjection: 'table',
  dialogShell: 'actor',
  panels: {
    properties: 'ContactProperties',
    content: 'ContactContent',
    footerActions: ['message', 'archive', 'delete'],
  },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'email', 'company', 'phone', 'content'],
  fields: [
    ...baseFields(),
    ...actorFields(),
    f('content', 'rich_text'),
    f('company', 'rich_text'),
    f('address', 'rich_text'),
    f('notes', 'rich_text'),
  ],
}

const organizationOntology: SchemaDefinition = {
  '@id': 'trellis:schema/organization',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'actor',
  label: 'Organization',
  labelPlural: 'Organizations',
  icon: 'lucide:building-2',
  color: 'zinc',
  projections: ['table', 'card-grid', 'list', 'graph'],
  defaultProjection: 'table',
  dialogShell: 'actor',
  panels: {
    properties: 'OrganizationProperties',
    content: 'OrganizationContent',
    footerActions: ['archive', 'delete'],
  },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'website', 'industry', 'content'],
  fields: [
    ...baseFields(),
    ...actorFields(),
    f('content', 'rich_text'),
    f('website', 'url'),
    f('industry', 'rich_text'),
    f('memberCount', 'number'),
  ],
}

const vendorOntology: SchemaDefinition = {
  '@id': 'trellis:schema/vendor',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'actor',
  label: 'Vendor',
  labelPlural: 'Vendors',
  icon: 'lucide:store',
  color: 'lime',
  projections: ['table', 'card-grid', 'list'],
  defaultProjection: 'table',
  dialogShell: 'actor',
  panels: { properties: 'VendorProperties', content: 'VendorContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'email', 'services', 'content'],
  fields: [
    ...baseFields(),
    ...actorFields(),
    f('content', 'rich_text'),
    f('services', 'multi_select'),
    f('contractEnd', 'date'),
    f('rating', 'number'),
  ],
}

// ============================================================================
// Per-Type Ontologies — Container
// ============================================================================

const projectOntology: SchemaDefinition = {
  '@id': 'trellis:schema/project',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Project',
  labelPlural: 'Projects',
  icon: 'lucide:folder-kanban',
  color: 'blue',
  projections: ['kanban', 'list', 'table', 'timeline', 'dashboard'],
  defaultProjection: 'kanban',
  dialogShell: 'container',
  panels: {
    properties: 'ProjectProperties',
    content: 'ProjectContent',
    footerActions: ['archive', 'complete', 'delete'],
  },
  propertyFieldIds: ['type', 'status', 'startDate', 'endDate', 'category', 'owner', 'involved', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description'],
  fields: [
    ...baseFields(),
    ...containerFields(),
    f('startDate', 'date', { icon: 'lucide:calendar', group: 'scheduling', display: 'inline-input', editable: true }),
    f('endDate', 'date', {
      icon: 'lucide:calendar-range',
      group: 'scheduling',
      display: 'inline-input',
      editable: true,
    }),
    f('budget', 'number'),
  ],
}

const folderOntology: SchemaDefinition = {
  '@id': 'trellis:schema/folder',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Folder',
  labelPlural: 'Folders',
  icon: 'lucide:folder',
  color: 'amber',
  projections: ['list', 'table'],
  defaultProjection: 'list',
  dialogShell: 'container',
  panels: { properties: 'FolderProperties', content: 'FolderContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description'],
  fields: [...baseFields(), ...containerFields(), f('isSystemGenerated', 'checkbox')],
}

const collectionOntology: SchemaDefinition = {
  '@id': 'trellis:schema/collection',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Collection',
  labelPlural: 'Collections',
  icon: 'lucide:database',
  color: 'indigo',
  projections: ['list', 'card-grid', 'table'],
  defaultProjection: 'table',
  dialogShell: 'container',
  panels: {
    properties: 'CollectionProperties',
    content: 'CollectionContent',
    footerActions: ['publish', 'archive', 'delete'],
  },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description'],
  fields: [
    ...baseFields(),
    ...containerFields(),
    f('collectionType', 'select', {
      selectOptions: ['database', 'document', 'board', 'calendar', 'gallery', 'form', 'page', 'list'],
    }),
  ],
}

const goalOntology: SchemaDefinition = {
  '@id': 'trellis:schema/goal',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Goal',
  labelPlural: 'Goals',
  icon: 'lucide:target',
  color: 'emerald',
  projections: ['list', 'kanban', 'table', 'timeline'],
  defaultProjection: 'kanban',
  dialogShell: 'container',
  panels: { properties: 'GoalProperties', content: 'GoalContent', footerActions: ['complete', 'archive', 'delete'] },
  propertyFieldIds: ['type', 'status', 'endDate', 'category', 'owner', 'involved', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description', 'metric'],
  fields: [
    ...baseFields(),
    ...containerFields(),
    f('targetDate', 'date'),
    f('metric', 'rich_text'),
    f('targetValue', 'number'),
    f('currentValue', 'number'),
    f('endDate', 'date', {
      icon: 'lucide:calendar-range',
      group: 'scheduling',
      display: 'inline-input',
      editable: true,
    }),
  ],
}

const repositoryOntology: SchemaDefinition = {
  '@id': 'trellis:schema/repository',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Repository',
  labelPlural: 'Repositories',
  icon: 'lucide:git-branch',
  color: 'slate',
  projections: ['card-grid', 'list', 'table'],
  defaultProjection: 'card-grid',
  dialogShell: 'container',
  panels: {
    properties: 'RepositoryProperties',
    content: 'RepositoryContent',
    footerActions: ['archive', 'delete'],
  },
  propertyFieldIds: ['type', 'visibility', 'language', 'defaultBranch', 'ownerLogin', 'pushedAt', 'tags'],
  defaultSortField: 'pushedAt',
  searchFields: ['title', 'fullName', 'description', 'topics', 'language'],
  fields: [
    ...baseFields(),
    ...containerFields(),
    f('fullName', 'rich_text', { icon: 'lucide:git-fork', group: 'identifiers', display: 'inline-input' }),
    f('ownerLogin', 'rich_text', { icon: 'lucide:user', group: 'identifiers', display: 'inline-input' }),
    f('ownerAvatarUrl', 'url'),
    f('ownerType', 'select', {
      selectOptions: ['User', 'Organization'],
      icon: 'lucide:users',
      group: 'identifiers',
      display: 'popover',
    }),
    f('url', 'url', { icon: 'lucide:external-link', group: 'identifiers', display: 'inline-input' }),
    f('cloneUrl', 'url'),
    f('homepage', 'url', { icon: 'lucide:home', group: 'identifiers', display: 'inline-input' }),
    f('defaultBranch', 'rich_text', {
      icon: 'lucide:git-branch',
      group: 'classification',
      display: 'inline-input',
    }),
    f('visibility', 'select', {
      selectOptions: ['public', 'private', 'internal'],
      icon: 'lucide:eye',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('language', 'rich_text', {
      icon: 'lucide:code-2',
      group: 'classification',
      display: 'inline-input',
    }),
    f('topics', 'multi_select', {
      icon: 'lucide:hash',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('license', 'rich_text'),
    f('stars', 'number', { icon: 'lucide:star' }),
    f('forks', 'number', { icon: 'lucide:git-fork' }),
    f('watchers', 'number', { icon: 'lucide:eye' }),
    f('openIssuesCount', 'number', { icon: 'lucide:circle-dot' }),
    f('isArchived', 'checkbox', { icon: 'lucide:archive', group: 'classification', display: 'toggle' }),
    f('isFork', 'checkbox', { icon: 'lucide:git-fork', group: 'classification', display: 'toggle' }),
    f('isPrivate', 'checkbox', { icon: 'lucide:lock', group: 'classification', display: 'toggle' }),
    f('isTemplate', 'checkbox', { icon: 'lucide:copy', group: 'classification', display: 'toggle' }),
    f('pushedAt', 'date', { icon: 'lucide:arrow-up-from-line', group: 'scheduling', display: 'inline-input' }),
    f('githubRepoId', 'rich_text'),
    f('source', 'rich_text'),
    f('connectionId', 'rich_text'),
  ],
}

// ============================================================================
// Per-Type Ontologies — Campus Substrate (Phase 0)
// ----------------------------------------------------------------------------
// Facility, Zone, Agent, Wallet, Decision, Artifact — the spatial/authority
// primitives inherited from turtleOS. See PLATFORM.md "The Spatial Substrate"
// section and the campus-substrate-c4s7b2.md plan (slice 0.1).
//
// Zone = capability grant. Every agent action is checked against the grants
// of the Zone it is acting in. Decisions and Artifacts are tagged with their
// originating Zone for provenance.
// ============================================================================

const facilityOntology: SchemaDefinition = {
  '@id': 'trellis:schema/facility',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Facility',
  labelPlural: 'Facilities',
  icon: 'lucide:building-2',
  color: 'slate',
  projections: ['list', 'card-grid', 'graph'],
  defaultProjection: 'card-grid',
  dialogShell: 'container',
  panels: { properties: 'FacilityProperties', content: 'FacilityContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'status', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description', 'facilityKind'],
  fields: [
    ...baseFields(),
    ...containerFields(),
    f('ownerAgent', 'rich_text', {
      icon: 'lucide:user',
      group: 'people',
      display: 'inline-input',
      editable: true,
    }),
    f('facilityKind', 'select', {
      selectOptions: ['root', 'agent', 'team', 'project', 'registry'],
      icon: 'lucide:building',
      group: 'classification',
      display: 'popover',
      editable: true,
      defaultValue: 'agent',
    }),
  ],
}

const zoneOntology: SchemaDefinition = {
  '@id': 'trellis:schema/zone',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Zone',
  labelPlural: 'Zones',
  icon: 'lucide:layout-panel-left',
  color: 'indigo',
  projections: ['list', 'table', 'graph'],
  defaultProjection: 'list',
  dialogShell: 'container',
  panels: { properties: 'ZoneProperties', content: 'ZoneContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'status', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description', 'zoneKind'],
  fields: [
    ...baseFields(),
    ...containerFields(),
    f('zoneKind', 'select', {
      required: true,
      selectOptions: ['lab', 'lobby', 'workshop', 'showroom', 'classroom', 'giftshop', 'vault'],
      icon: 'lucide:layout-panel-left',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('facilityId', 'rich_text', {
      icon: 'lucide:building-2',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
    // JSON-encoded CapabilityGrant[] — actions + target filters
    f('grants', 'rich_text'),
    f('memberAgents', 'multi_select', {
      icon: 'lucide:users',
      group: 'people',
      display: 'popover',
      editable: true,
    }),
    f('publicRead', 'checkbox', {
      icon: 'lucide:eye',
      group: 'classification',
      display: 'toggle',
      editable: true,
      defaultValue: false,
    }),
  ],
}

const agentOntology: SchemaDefinition = {
  '@id': 'trellis:schema/agent',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'actor',
  label: 'Agent',
  labelPlural: 'Agents',
  icon: 'lucide:bot',
  color: 'purple',
  projections: ['card-grid', 'list', 'table', 'graph'],
  defaultProjection: 'card-grid',
  dialogShell: 'actor',
  panels: { properties: 'AgentProperties', content: 'AgentContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description', 'role', 'model'],
  fields: [
    ...baseFields(),
    ...actorFields(),
    f('agentStatus', 'select', {
      selectOptions: ['active', 'inactive', 'deprecated'],
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
      defaultValue: 'active',
    }),
    f('model', 'rich_text', {
      icon: 'lucide:cpu',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
    f('provider', 'select', {
      selectOptions: ['anthropic', 'openai', 'google', 'ollama', 'local', 'human'],
      icon: 'lucide:plug',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('systemPrompt', 'rich_text'),
    // JSON-encoded graph scope — entity types and filters this agent reads/writes
    f('memoryScope', 'rich_text'),
    // JSON-encoded list of MCP tools available to this agent
    f('toolManifest', 'rich_text'),
    f('homeFacility', 'rich_text', {
      icon: 'lucide:building-2',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
    f('walletId', 'rich_text', {
      icon: 'lucide:wallet',
      group: 'identifiers',
      display: 'inline-input',
      editable: true,
    }),
    f('invitedToZones', 'multi_select', {
      icon: 'lucide:door-open',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
  ],
}

const walletOntology: SchemaDefinition = {
  '@id': 'trellis:schema/wallet',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'actor',
  label: 'Wallet',
  labelPlural: 'Wallets',
  icon: 'lucide:wallet',
  color: 'amber',
  projections: ['list', 'table', 'card-grid'],
  defaultProjection: 'card-grid',
  dialogShell: 'actor',
  panels: { properties: 'WalletProperties', content: 'WalletContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'title',
  searchFields: ['title', 'description', 'identity'],
  fields: [
    ...baseFields(),
    ...actorFields(),
    // Ed25519 public key (base58 or hex). Placeholder string in Phase 0.
    f('identity', 'rich_text', {
      icon: 'lucide:key',
      group: 'identifiers',
      display: 'inline-input',
      editable: true,
    }),
    // JSON-encoded reputation projection — derived from op-log retention scores
    f('reputation', 'rich_text'),
    f('holdsAgent', 'rich_text', {
      icon: 'lucide:bot',
      group: 'people',
      display: 'inline-input',
      editable: true,
    }),
    f('grantedZones', 'multi_select', {
      icon: 'lucide:door-open',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
  ],
}

const decisionOntology: SchemaDefinition = {
  '@id': 'trellis:schema/decision',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Decision',
  labelPlural: 'Decisions',
  icon: 'lucide:git-branch',
  color: 'cyan',
  projections: ['list', 'table', 'timeline'],
  defaultProjection: 'list',
  dialogShell: 'document',
  panels: { properties: 'DecisionProperties', content: 'DecisionContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'createdAt',
  searchFields: ['title', 'rationale', 'outcome', 'toolName'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('rationale', 'rich_text'),
    // JSON-encoded snapshot of the graph state the agent considered
    f('contextSnapshot', 'rich_text'),
    f('outcome', 'select', {
      selectOptions: ['proposed', 'executed', 'rejected', 'superseded', 'pending'],
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
      defaultValue: 'executed',
    }),
    f('toolName', 'rich_text', {
      icon: 'lucide:wrench',
      group: 'identifiers',
      display: 'inline-input',
      editable: true,
    }),
    // JSON-encoded tool call input
    f('toolInput', 'rich_text'),
    // JSON-encoded list of options the agent considered but did not choose
    f('alternatives', 'rich_text'),
    f('byAgent', 'rich_text', {
      icon: 'lucide:bot',
      group: 'people',
      display: 'inline-input',
      editable: true,
    }),
    f('inZone', 'rich_text', {
      icon: 'lucide:layout-panel-left',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
    f('informedBy', 'multi_select', {
      icon: 'lucide:link',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('supersedes', 'rich_text', {
      icon: 'lucide:corner-down-right',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
    f('producesArtifact', 'rich_text', {
      icon: 'lucide:package',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
  ],
}

const artifactOntology: SchemaDefinition = {
  '@id': 'trellis:schema/artifact',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Artifact',
  labelPlural: 'Artifacts',
  icon: 'lucide:package',
  color: 'teal',
  projections: ['card-grid', 'list', 'table'],
  defaultProjection: 'card-grid',
  dialogShell: 'document',
  panels: { properties: 'ArtifactProperties', content: 'ArtifactContent', footerActions: ['archive', 'delete'] },
  propertyFieldIds: ['type', 'category', 'owner', 'tags'],
  defaultSortField: 'updatedAt',
  searchFields: ['title', 'description', 'contentRef'],
  fields: [
    ...baseFields(),
    ...documentFields(),
    f('artifactType', 'select', {
      selectOptions: ['code', 'design', 'document', 'data', 'diagram', 'deliverable', 'other'],
      icon: 'lucide:layers',
      group: 'classification',
      display: 'popover',
      editable: true,
      defaultValue: 'document',
    }),
    f('contentRef', 'rich_text', {
      icon: 'lucide:link',
      group: 'identifiers',
      display: 'inline-input',
      editable: true,
    }),
    f('artifactVersion', 'rich_text', {
      icon: 'lucide:tag',
      group: 'identifiers',
      display: 'inline-input',
      editable: true,
    }),
    f('createdByAgent', 'rich_text', {
      icon: 'lucide:bot',
      group: 'people',
      display: 'inline-input',
      editable: true,
    }),
    f('publishedInZone', 'rich_text', {
      icon: 'lucide:layout-panel-left',
      group: 'classification',
      display: 'inline-input',
      editable: true,
    }),
    f('usedIn', 'multi_select', {
      icon: 'lucide:folder',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
  ],
}

// ============================================================================
// SidebarNode — navigation tree nodes (core, own TQL namespace)
// ============================================================================

export const SIDEBAR_NODE_NAMESPACE = 'sidebar_node'

const sidebarNodeOntology: SchemaDefinition = {
  '@id': `trellis:schema/${SIDEBAR_NODE_NAMESPACE}`,
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'core',
  fields: [
    f('label', 'title', { required: true }),
    f('icon', 'rich_text'),
    f('routePath', 'rich_text'),
    f('entityType', 'rich_text'),
    f('scope', 'select', { required: true, selectOptions: ['workspace', 'database', 'settings', 'graph'] }),
    f('nodeType', 'select', { required: true, selectOptions: ['section', 'item', 'separator'] }),
    f('locked', 'checkbox'),
    f('collapsed', 'checkbox'),
    f('order', 'number'),
    f('worldId', 'rich_text'),
    f('sectionKey', 'rich_text'),
    f('specialItems', 'rich_text'),
    f('editable', 'checkbox'),
  ],
}

// ============================================================================
// Polymorphic Entity Ontology — covers all entity types in one schema
// Used by TQL queries: FIND <ENTITY_NAMESPACE> AS ?t ...
// ============================================================================

const entityOntology: SchemaDefinition = {
  '@id': `trellis:schema/${ENTITY_NAMESPACE}`,
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  fields: [
    f('type', 'select', {
      required: true,
      selectOptions: [
        'task',
        'event',
        'trip',
        'payment',
        'note',
        'appointment',
        'reminder',
        'deadline',
        'milestone',
        'sprint',
        'budget',
        'expense',
        'bookmark',
        'email',
        'file',
        'page',
        'template',
        'slide_deck',
        'sheet',
        'canvas',
        'diagram',
        'person',
        'contact',
        'organization',
        'vendor',
        'project',
        'folder',
        'collection',
        'goal',
        'repository',
        'github_issue',
        'pull_request',
        'integration_definition',
        'integration_connection',
        // Campus Substrate (Phase 0)
        'facility',
        'zone',
        'agent',
        'wallet',
        'decision',
        'artifact',
      ],
    }),
    f('title', 'title', { required: true }),
    f('description', 'rich_text'),
    f('startDate', 'date'),
    f('endDate', 'date'),
    f('allDay', 'checkbox'),
    f('startTime', 'rich_text'),
    f('endTime', 'rich_text'),
    f('priority', 'select', { selectOptions: ['critical', 'high', 'medium', 'low'] }),
    f('urgency', 'select', { selectOptions: ['urgent', 'not-urgent'] }),
    f('priorityOverride', 'checkbox'),
    f('urgencyOverride', 'checkbox'),
    f('category', 'select', {
      selectOptions: [
        'general',
        'work',
        'personal',
        'meeting',
        'review',
        'appointment',
        'deadline',
        'health',
        'finance',
        'travel',
      ],
    }),
    f('tags', 'multi_select'),
    f('owner', 'rich_text'),
    f('involved', 'multi_select'),
    f('folder', 'rich_text'),
    f('notes', 'rich_text'),
    f('taskStatus', 'select', {
      selectOptions: ['pending', 'in-progress', 'on-track', 'due-soon', 'overdue', 'completed'],
    }),
    f('location', 'rich_text'),
    f('conferenceLink', 'url'),
    f('eventType', 'select', { selectOptions: ['meeting', 'appointment', 'training', 'deadline', 'social', 'other'] }),
    f('amount', 'number'),
    f('currency', 'rich_text'),
    f('payee', 'rich_text'),
    f('paymentMethod', 'rich_text'),
    f('recurring', 'checkbox'),
    f('paymentStatus', 'select', { selectOptions: ['pending', 'paid', 'overdue', 'cancelled'] }),
    f('content', 'rich_text'),
    f('pinned', 'checkbox'),
    f('origin', 'rich_text'),
    f('destination', 'rich_text'),
    f('transportation', 'select', { selectOptions: ['flight', 'drive', 'train', 'bus', 'other'] }),
    f('budget', 'number'),
    f('confirmationNumber', 'rich_text'),
    f('tripStatus', 'select', { selectOptions: ['planning', 'booked', 'in-progress', 'completed', 'cancelled'] }),
    f('checklistContent', 'rich_text'),
    // Integration fields (shared across integration_definition + integration_connection entities)
    f('provider', 'rich_text'),
    f('authType', 'select', { selectOptions: ['oauth', 'api_key', 'webhook', 'none'] }),
    f('icon', 'rich_text'),
    f('color', 'rich_text'),
    f('features', 'multi_select'),
    f('docsUrl', 'url'),
    f('webhookSupport', 'checkbox'),
    f('pushNotificationSupport', 'checkbox'),
    f('enrichmentSupport', 'checkbox'),
    f('syncDirection', 'select', { selectOptions: ['import', 'export', 'bidirectional'] }),
    f('requiredScopes', 'multi_select'),
    f('configSchema', 'rich_text'),
    f('integrationStatus', 'select', { selectOptions: ['available', 'beta', 'deprecated'] }),
    f('integrationId', 'rich_text'),
    f('userId', 'rich_text'),
    f('connectionStatus', 'select', { selectOptions: ['connected', 'error', 'configuring', 'disconnected'] }),
    f('connectedAt', 'date'),
    f('lastSyncAt', 'date'),
    f('syncEnabled', 'checkbox'),
    f('syncIntervalMs', 'number'),
    f('accountEmail', 'email'),
    f('accountName', 'rich_text'),
    f('config', 'rich_text'),
    f('credentialsRef', 'rich_text'),
    f('watchChannelId', 'rich_text'),
    f('watchExpiration', 'date'),
    f('errorMessage', 'rich_text'),
    f('syncedEntityCount', 'number'),
    // Google Calendar sync fields (for synced event entities)
    f('source', 'rich_text'),
    f('googleEventId', 'rich_text'),
    f('googleCalendarId', 'rich_text'),
    f('htmlLink', 'url'),
    f('googleStatus', 'rich_text'),
    f('googleUpdatedAt', 'rich_text'),
    f('gcalDeleted', 'checkbox'),
    // Event participants (persisted from Google Calendar payloads as
    // "Name <email>" strings so they match the Gmail from/to/cc format
    // and can be parsed by the same people-from-emails logic).
    f('organizer', 'rich_text'),
    f('attendees', 'multi_select'),
    // Email-specific fields (for synced email entities)
    f('subject', 'rich_text'),
    f('snippet', 'rich_text'),
    f('from', 'rich_text'),
    f('to', 'rich_text'),
    f('cc', 'rich_text'),
    f('bcc', 'rich_text'),
    f('date', 'date'),
    f('labelIds', 'multi_select'),
    f('threadId', 'rich_text'),
    f('messageId', 'rich_text'),
    f('isRead', 'checkbox'),
    f('isStarred', 'checkbox'),
    f('bodyText', 'rich_text'),
    f('bodyHtml', 'rich_text'),
    f('gmailMessageId', 'rich_text'),
    f('gmailThreadId', 'rich_text'),
    // GitHub-specific fields (repository / issue / pull_request entities)
    f('fullName', 'rich_text'),
    f('ownerLogin', 'rich_text'),
    f('ownerAvatarUrl', 'url'),
    f('ownerType', 'select', { selectOptions: ['User', 'Organization'] }),
    f('url', 'url'),
    f('cloneUrl', 'url'),
    f('homepage', 'url'),
    f('defaultBranch', 'rich_text'),
    f('visibility', 'select', { selectOptions: ['public', 'private', 'internal'] }),
    f('language', 'rich_text'),
    f('topics', 'multi_select'),
    f('license', 'rich_text'),
    f('stars', 'number'),
    f('forks', 'number'),
    f('watchers', 'number'),
    f('openIssuesCount', 'number'),
    f('isArchived', 'checkbox'),
    f('isFork', 'checkbox'),
    f('isPrivate', 'checkbox'),
    f('isTemplate', 'checkbox'),
    f('pushedAt', 'date'),
    f('githubRepoId', 'rich_text'),
    f('number', 'number'),
    f('body', 'rich_text'),
    f('issueState', 'select', { selectOptions: ['open', 'closed'] }),
    f('stateReason', 'select', { selectOptions: ['completed', 'not_planned', 'reopened'] }),
    f('prState', 'select', { selectOptions: ['open', 'closed', 'merged', 'draft'] }),
    f('draft', 'checkbox'),
    f('merged', 'checkbox'),
    f('mergeable', 'select', { selectOptions: ['mergeable', 'conflicting', 'unknown'] }),
    f('mergedAt', 'date'),
    f('closedAt', 'date'),
    f('mergedByLogin', 'rich_text'),
    f('authorLogin', 'rich_text'),
    f('authorAvatarUrl', 'url'),
    f('assignees', 'multi_select'),
    f('reviewers', 'multi_select'),
    f('requestedReviewers', 'multi_select'),
    f('labels', 'multi_select'),
    f('milestone', 'rich_text'),
    f('baseBranch', 'rich_text'),
    f('headBranch', 'rich_text'),
    f('baseSha', 'rich_text'),
    f('headSha', 'rich_text'),
    f('commits', 'number'),
    f('additions', 'number'),
    f('deletions', 'number'),
    f('changedFiles', 'number'),
    f('commentsCount', 'number'),
    f('reviewCommentsCount', 'number'),
    f('repositoryFullName', 'rich_text'),
    f('repositoryId', 'rich_text'),
    f('githubIssueId', 'rich_text'),
    f('githubPrId', 'rich_text'),
    f('connectionId', 'rich_text'),
  ],
}

// ============================================================================
// Comment — activity/comment entries linked to any entity
// ============================================================================

const commentOntology: SchemaDefinition = {
  '@id': 'trellis:schema/comment',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  fields: [
    f('entityId', 'rich_text', { required: true }),
    f('entityType', 'select', {
      required: true,
      selectOptions: ['entity', 'task', 'note', 'event', 'payment', 'trip'],
    }),
    f('authorId', 'rich_text', { required: true }),
    f('authorName', 'rich_text', { required: true }),
    f('authorAvatar', 'rich_text'),
    f('content', 'rich_text', { required: true }),
    f('type', 'select', { required: true, selectOptions: ['comment', 'status_change', 'attachment', 'created'] }),
    f('metadata', 'rich_text'),
    f('createdAt', 'number'),
    f('updatedAt', 'number'),
    f('deletedAt', 'number'),
  ],
}

// ============================================================================
// Notification — in-app notifications from graph ops, email, calendar, jobs, alerts
// ============================================================================

export const NOTIFICATION_NAMESPACE = 'notification'

const notificationOntology: SchemaDefinition = {
  '@id': `trellis:schema/${NOTIFICATION_NAMESPACE}`,
  '@type': 'trellis:Schema',
  version: '1.1.0',
  tier: 'system',
  fields: [
    f('title', 'title', { required: true }),
    f('body', 'rich_text'),
    // Visual kind — drives icon + color + sound selection
    f('kind', 'select', {
      required: true,
      selectOptions: ['success', 'error', 'warning', 'info', 'reminder', 'email', 'calendar', 'alert', 'ops', 'job'],
    }),
    // Origin system that produced the notification
    f('source', 'select', {
      required: true,
      selectOptions: ['system', 'email', 'calendar', 'graph', 'job', 'ops', 'workflow', 'ai', 'user'],
    }),
    f('sourceId', 'rich_text'),
    f('priority', 'select', { selectOptions: ['critical', 'high', 'normal', 'low'], defaultValue: 'normal' }),
    f('delivery', 'select', {
      selectOptions: ['interrupt', 'passive'],
      defaultValue: 'passive',
    }),
    f('requiredAction', 'select', {
      selectOptions: ['none', 'acknowledge', 'navigate', 'resolve'],
      defaultValue: 'none',
    }),
    f('status', 'select', {
      selectOptions: ['unread', 'read', 'archived', 'snoozed'],
      required: true,
      defaultValue: 'unread',
    }),
    f('readAt', 'date'),
    f('snoozeUntil', 'date'),
    f('archivedAt', 'date'),
    // Optional visual overrides
    f('icon', 'rich_text'),
    f('color', 'rich_text'),
    f('sound', 'select', { selectOptions: ['success', 'fail', 'reminder', 'email', 'none'] }),
    // Link to a related entity (for deep-link CTA + filtering)
    f('entityId', 'rich_text'),
    f('entityType', 'rich_text'),
    f('url', 'url'),
    // CTA actions serialized as JSON: [{ id, label, kind, ... }]
    f('actions', 'rich_text'),
    // Raw payload for source-specific metadata (JSON)
    f('metadata', 'rich_text'),
    f('groupKey', 'rich_text'),
    f('createdAt', 'date'),
    f('updatedAt', 'date'),
  ],
}

// ============================================================================
// User-tier demo ontology — browse Form view e2e
// ============================================================================

const feedbackOntology = {
  '@id': 'trellis:schema/feedback',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'user',
  entityClass: 'document',
  label: 'Feedback',
  labelPlural: 'Feedback',
  icon: 'lucide:message-square',
  color: 'violet',
  formPresentation: 'stacked',
  projections: ['list', 'table', 'card-grid'],
  defaultProjection: 'table',
  dialogShell: 'document',
  panels: { properties: 'DynamicProperties', content: 'DynamicContent', footerActions: ['archive', 'delete'] },
  defaultSortField: 'title',
  searchFields: ['title', 'comments'],
  fields: [
    f('title', 'title', { required: true }),
    f('rating', 'select', {
      required: true,
      selectOptions: ['Good', 'Neutral', 'Bad'],
      icon: 'lucide:star',
      group: 'feedback',
      display: 'popover',
      editable: true,
    }),
    f('comments', 'rich_text', { icon: 'lucide:message-square', group: 'feedback', display: 'inline-input', editable: true }),
    ...documentFields(),
  ],
} as SchemaDefinition

// ============================================================================
// All entity type ontologies — keyed by schema ID
// ============================================================================

const entityTypeOntologies: Record<string, SchemaDefinition> = {
  'trellis:schema/task': taskOntology,
  'trellis:schema/event': eventOntology,
  'trellis:schema/trip': tripOntology,
  'trellis:schema/payment': paymentOntology,
  'trellis:schema/appointment': appointmentOntology,
  'trellis:schema/reminder': reminderOntology,
  'trellis:schema/deadline': deadlineOntology,
  'trellis:schema/milestone': milestoneOntology,
  'trellis:schema/sprint': sprintOntology,
  'trellis:schema/budget': budgetOntology,
  'trellis:schema/expense': expenseOntology,
  'trellis:schema/github_issue': githubIssueOntology,
  'trellis:schema/pull_request': pullRequestOntology,
  'trellis:schema/note': noteOntology,
  'trellis:schema/file': fileOntology,
  'trellis:schema/page': pageOntology,
  'trellis:schema/template': templateOntology,
  'trellis:schema/slide_deck': slideDeckOntology,
  'trellis:schema/sheet': sheetOntology,
  'trellis:schema/canvas': canvasOntology,
  'trellis:schema/diagram': diagramOntology,
  'trellis:schema/bookmark': bookmarkOntology,
  'trellis:schema/email': emailOntology,
  'trellis:schema/person': personOntology,
  'trellis:schema/contact': contactOntology,
  'trellis:schema/organization': organizationOntology,
  'trellis:schema/vendor': vendorOntology,
  'trellis:schema/project': projectOntology,
  'trellis:schema/folder': folderOntology,
  'trellis:schema/collection': collectionOntology,
  'trellis:schema/goal': goalOntology,
  'trellis:schema/repository': repositoryOntology,
  // ── Campus Substrate (Phase 0) ─────────────────────────────────────
  'trellis:schema/facility': facilityOntology,
  'trellis:schema/zone': zoneOntology,
  'trellis:schema/agent': agentOntology,
  'trellis:schema/wallet': walletOntology,
  'trellis:schema/decision': decisionOntology,
  'trellis:schema/artifact': artifactOntology,
  'trellis:schema/feedback': feedbackOntology,
}

// ============================================================================
// Integration Ontologies — catalog + live connections
// ============================================================================

const integrationDefinitionOntology: SchemaDefinition = {
  '@id': 'trellis:schema/integration_definition',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Integration',
  labelPlural: 'Integrations',
  icon: 'lucide:plug',
  color: 'violet',
  projections: ['list', 'card-grid'],
  defaultProjection: 'card-grid',
  searchFields: ['title', 'description', 'provider'],
  fields: [
    f('title', 'title', { required: true }),
    f('description', 'rich_text'),
    f('provider', 'rich_text', { required: true }),
    f('category', 'select', {
      selectOptions: ['data', 'auth', 'communication', 'storage', 'automation', 'analytics'],
      required: true,
      icon: 'lucide:tag',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('authType', 'select', {
      selectOptions: ['oauth', 'api_key', 'webhook', 'none'],
      required: true,
      icon: 'lucide:key',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('icon', 'rich_text'),
    f('color', 'rich_text'),
    f('features', 'multi_select'),
    f('docsUrl', 'url'),
    f('webhookSupport', 'checkbox'),
    f('pushNotificationSupport', 'checkbox'),
    f('enrichmentSupport', 'checkbox'),
    f('syncDirection', 'select', { selectOptions: ['import', 'export', 'bidirectional'] }),
    f('requiredScopes', 'multi_select'),
    f('configSchema', 'rich_text'),
    f('integrationStatus', 'select', {
      selectOptions: ['available', 'beta', 'deprecated'],
      defaultValue: 'available',
    }),
  ],
}

const integrationConnectionOntology: SchemaDefinition = {
  '@id': 'trellis:schema/integration_connection',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Integration Connection',
  labelPlural: 'Integration Connections',
  icon: 'lucide:link',
  color: 'green',
  projections: ['list'],
  defaultProjection: 'list',
  searchFields: ['title', 'integrationId'],
  fields: [
    f('title', 'title', { required: true }),
    f('integrationId', 'rich_text', { required: true }),
    f('userId', 'rich_text', { required: true }),
    f('connectionStatus', 'select', {
      selectOptions: ['connected', 'error', 'configuring', 'disconnected'],
      required: true,
      defaultValue: 'configuring',
      icon: 'lucide:circle-dot',
      group: 'triage',
      display: 'popover',
      editable: true,
    }),
    f('connectedAt', 'date'),
    f('lastSyncAt', 'date'),
    f('syncEnabled', 'checkbox', { defaultValue: true }),
    f('syncIntervalMs', 'number', { defaultValue: 900000 }),
    f('accountEmail', 'email'),
    f('accountName', 'rich_text'),
    f('config', 'rich_text'),
    f('credentialsRef', 'rich_text'),
    f('watchChannelId', 'rich_text'),
    f('watchExpiration', 'date'),
    f('errorMessage', 'rich_text'),
    f('syncedEntityCount', 'number'),
  ],
}

// ============================================================================
// Workspace Configuration — the .trellis format
// ============================================================================

// ============================================================================
// Chat Ontologies — channel, message
// ============================================================================

const channelOntology: SchemaDefinition = {
  '@id': 'trellis:schema/channel',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'container',
  label: 'Channel',
  labelPlural: 'Channels',
  icon: 'lucide:hash',
  color: 'sky',
  projections: ['list'],
  defaultProjection: 'list',
  searchFields: ['title', 'description'],
  browse: { enabled: false },
  routed: '/messages',
  fields: [
    f('title', 'title', { required: true }),
    f('slug', 'rich_text', { icon: 'lucide:hash', group: 'classification', display: 'inline-input', editable: true }),
    f('description', 'rich_text'),
    f('type', 'select', {
      selectOptions: ['public', 'private', 'dm', 'thread'],
      icon: 'lucide:lock',
      group: 'classification',
      display: 'popover',
      editable: true,
    }),
    f('icon', 'rich_text'),
    f('orgId', 'rich_text'),
    f('memberIds', 'multi_select'),
    f('entityId', 'rich_text'),
    f('lastMessageAt', 'date'),
    f('createdBy', 'rich_text'),
    f('createdAt', 'date'),
  ],
}

const messageOntology: SchemaDefinition = {
  '@id': 'trellis:schema/message',
  '@type': 'trellis:Schema',
  version: '1.0.0',
  tier: 'system',
  entityClass: 'document',
  label: 'Message',
  labelPlural: 'Messages',
  icon: 'lucide:message-square',
  color: 'sky',
  projections: ['list'],
  defaultProjection: 'list',
  searchFields: ['content', 'authorName'],
  browse: { enabled: false },
  routed: '/messages',
  fields: [
    f('content', 'rich_text', { required: true }),
    f('channelId', 'rich_text'),
    f('authorId', 'rich_text'),
    f('authorName', 'rich_text'),
    f('authorAvatar', 'url'),
    f('replyToId', 'rich_text'),
    f('reactions', 'json'),
    f('entityRefs', 'json'),
    f('edited', 'checkbox'),
    f('editedAt', 'date'),
    f('deletedAt', 'date'),
    f('createdAt', 'date'),
  ],
}

export function createWorkspaceConfig(): WorkspaceConfig {
  return {
    workspace: {
      name: 'Trellis',
      description: 'Single graph, many projections — all app data as a graph.',
      ontologies: {
        // System ontologies
        [`trellis:schema/${ENTITY_NAMESPACE}`]: entityOntology,
        'trellis:schema/comment': commentOntology,
        [`trellis:schema/${NOTIFICATION_NAMESPACE}`]: notificationOntology,
        [`trellis:schema/${SIDEBAR_NODE_NAMESPACE}`]: sidebarNodeOntology,
        // Chat ontologies
        'trellis:schema/channel': channelOntology,
        'trellis:schema/message': messageOntology,
        // Integration ontologies
        'trellis:schema/integration_definition': integrationDefinitionOntology,
        'trellis:schema/integration_connection': integrationConnectionOntology,
        // Per-type ontologies (all 22 entity types)
        ...entityTypeOntologies,
      },
      routes: getRouteDefinitions() as any,
      app: {
        '@id': 'trellis:app',
        '@type': 'trellis:App' as const,
        title: 'Trellis',
        description: 'Personal knowledge graph platform',
        version: '0.1.0',
        devPort: DEV_PORT,
      },
      projections: {
        'trellis:projection/all-tasks': {
          '@id': 'trellis:projection/all-tasks',
          '@type': 'trellis:Projection',
          name: 'All Tasks',
          type: 'table',
          query: `${entityQuery('?t')} WHERE ?t.type = "task"`,
        },
        'trellis:projection/all-events': {
          '@id': 'trellis:projection/all-events',
          '@type': 'trellis:Projection',
          name: 'All Events',
          type: 'table',
          query: `${entityQuery('?e')} WHERE ?e.type = "event"`,
        },
        'trellis:projection/all-notes': {
          '@id': 'trellis:projection/all-notes',
          '@type': 'trellis:Projection',
          name: 'All Notes',
          type: 'card-grid',
          query: `${entityQuery('?n')} WHERE ?n.type = "note"`,
        },
        'trellis:projection/all-payments': {
          '@id': 'trellis:projection/all-payments',
          '@type': 'trellis:Projection',
          name: 'All Payments',
          type: 'table',
          query: `${entityQuery('?p')} WHERE ?p.type = "payment"`,
        },
      },
    },
  }
}

export {
  entityOntology,
  commentOntology,
  notificationOntology,
  sidebarNodeOntology,
  entityTypeOntologies,
  taskOntology,
  eventOntology,
  tripOntology,
  paymentOntology,
  appointmentOntology,
  reminderOntology,
  deadlineOntology,
  milestoneOntology,
  noteOntology,
  fileOntology,
  pageOntology,
  templateOntology,
  slideDeckOntology,
  bookmarkOntology,
  emailOntology,
  personOntology,
  contactOntology,
  organizationOntology,
  vendorOntology,
  projectOntology,
  folderOntology,
  collectionOntology,
  goalOntology,
  sprintOntology,
  budgetOntology,
  diagramOntology,
  repositoryOntology,
  githubIssueOntology,
  pullRequestOntology,
  integrationDefinitionOntology,
  integrationConnectionOntology,
  facilityOntology,
  zoneOntology,
  agentOntology,
  walletOntology,
  decisionOntology,
  artifactOntology,
  feedbackOntology,
}
