#!/usr/bin/env bun

/**
 * HQ Demo Script Generator — creates client presentation scripts from the knowledge graph.
 *
 * Usage:
 *   bun run hooks/tql-demo.ts                        # Demo for all time
 *   bun run hooks/tql-demo.ts --since 2026-02-01     # Demo for changes since date
 */

import { TrellisKernel } from '../packages/trellis-kernel/kernel/trellis-kernel.js';
import { createKernel, requireInit } from './_kernel.js';

async function safeQuery(kernel: TrellisKernel, q: string): Promise<Record<string, unknown>[]> {
  try {
    const result = kernel.query(q);
    const resolved = result instanceof Promise ? await result : result;
    return resolved.rows;
  } catch {
    return [];
  }
}

async function main() {
  requireInit();
  const kernel = createKernel();

  try {
    const features = await safeQuery(kernel,
      'FIND Feature AS ?f RETURN ?f.title, ?f.status, ?f.scope, ?f.priority ORDER BY ?f.priority DESC'
    );
    const doneFeatures = features.filter(f => f['?f.status'] === 'done');

    const milestones = await safeQuery(kernel,
      'FIND Milestone AS ?m RETURN ?m.title, ?m.targetDate, ?m.completionPct, ?m.status'
    );

    const changes = await safeQuery(kernel,
      'FIND Change AS ?c RETURN ?c.filePath, ?c.linesAdded, ?c.linesRemoved'
    );

    const decisions = await safeQuery(kernel,
      'FIND Decision AS ?d RETURN ?d.title, ?d.rationale, ?d.status'
    );

    const sessions = await safeQuery(kernel,
      'FIND Session AS ?s RETURN ?s.trajectoryId, ?s.promptCount'
    );

    const topFiles = await safeQuery(kernel,
      'FIND File AS ?f WHERE ?f.writeCount > 0 RETURN ?f.path, ?f.writeCount ORDER BY ?f.writeCount DESC LIMIT 10'
    );

    // Aggregate stats
    const totalAdded = changes.reduce((s, c) => s + (Number(c['?c.linesAdded']) || 0), 0);
    const totalRemoved = changes.reduce((s, c) => s + (Number(c['?c.linesRemoved']) || 0), 0);
    const uniqueFiles = new Set(changes.map(c => c['?c.filePath']));

    let md = `# Demo Script — ${new Date().toISOString().split('T')[0]}\n\n`;

    // Overview
    md += `## Project Overview\n\n`;
    md += `- **Sessions**: ${sessions.length} Cascade conversations\n`;
    md += `- **Code changes**: ${changes.length} mutations across ${uniqueFiles.size} files (+${totalAdded}/-${totalRemoved} lines)\n`;
    if (doneFeatures.length > 0) md += `- **Features completed**: ${doneFeatures.length}\n`;
    if (decisions.length > 0) md += `- **Decisions made**: ${decisions.length}\n`;
    md += '\n';

    // Milestones
    if (milestones.length > 0) {
      md += `## Milestones\n\n`;
      for (const m of milestones) {
        const pct = Number(m['?m.completionPct'] || 0);
        const filled = Math.round(pct * 10);
        const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);
        md += `- **${m['?m.title']}** [${bar}] ${Math.round(pct * 100)}%`;
        if (m['?m.targetDate']) md += ` — Target: ${m['?m.targetDate']}`;
        md += '\n';
      }
      md += '\n';
    }

    // Features
    if (doneFeatures.length > 0) {
      md += `## Features Completed\n\n`;
      for (let i = 0; i < doneFeatures.length; i++) {
        const f = doneFeatures[i]!;
        md += `${i + 1}. **${f['?f.title']}** (scope: ${f['?f.scope'] || 'general'})\n`;
      }
      md += '\n';
    }

    // Key decisions
    if (decisions.length > 0) {
      md += `## Key Decisions\n\n`;
      for (const d of decisions) {
        md += `- **${d['?d.title']}** — ${d['?d.rationale'] || 'See ADR for details'}\n`;
      }
      md += '\n';
    }

    // Most active files
    if (topFiles.length > 0) {
      md += `## Most Active Files\n\n`;
      for (const f of topFiles) {
        md += `- \`${f['?f.path']}\` (${f['?f.writeCount']} modifications)\n`;
      }
      md += '\n';
    }

    // Talking points
    md += `## Talking Points\n\n`;
    md += `- ${changes.length} code changes tracked automatically via HQ knowledge graph\n`;
    md += `- ${sessions.length} AI-assisted development sessions\n`;
    if (decisions.length > 0) md += `- ${decisions.length} architectural decisions documented\n`;
    md += `- All documentation auto-generated from project activity\n`;
    md += '\n';

    // Next steps
    const pendingFeatures = features.filter(f => f['?f.status'] !== 'done');
    if (pendingFeatures.length > 0) {
      md += `## Next Steps\n\n`;
      for (const f of pendingFeatures.slice(0, 5)) {
        md += `- ${f['?f.title']} (${f['?f.status'] || 'backlog'})\n`;
      }
      md += '\n';
    }

    md += `---\n*Generated by HQ at ${new Date().toISOString()}*\n`;

    console.log(md);
  } finally {
    kernel.close();
  }
}

main().catch((err) => {
  console.error('[HQ Demo] Error:', err);
  process.exit(1);
});
