#!/usr/bin/env bun

/**
 * HQ Devlog Generator — creates daily narrative summaries from the knowledge graph.
 *
 * Usage:
 *   bun run hooks/tql-devlog.ts           # Generate today's devlog
 *   bun run hooks/tql-devlog.ts 2026-02-07  # Generate for a specific date
 */

import { TrellisKernel } from '../packages/tql/kernel/trellis-kernel.js';
import { createKernel, requireInit, TQL_DIR } from './_kernel.js';
import { resolve } from 'path';
import { existsSync } from 'fs';
import { mkdir } from 'fs/promises';

const DEVLOG_DIR = resolve(TQL_DIR, 'devlog');

async function safeQuery(kernel: TrellisKernel, q: string): Promise<Record<string, unknown>[]> {
  try {
    const result = kernel.query(q);
    const resolved = result instanceof Promise ? await result : result;
    return resolved.rows;
  } catch {
    return [];
  }
}

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0]!;
}

async function main() {
  const targetDate = process.argv[2] || formatDate(new Date());

  requireInit();
  const kernel = createKernel();

  try {
    const sessions = await safeQuery(kernel, 'FIND Session AS ?s RETURN ?s.trajectoryId, ?s.startTime, ?s.promptCount, ?s.intent');
    const changes = await safeQuery(kernel, 'FIND Change AS ?c RETURN ?c.filePath, ?c.linesAdded, ?c.linesRemoved, ?c.timestamp');
    const actions = await safeQuery(kernel, 'FIND Action AS ?a RETURN ?a.actionType, ?a.timestamp, ?a.executionId, ?a.data');
    const decisions = await safeQuery(kernel, 'FIND Decision AS ?d RETURN ?d.title, ?d.rationale, ?d.status');
    const topFiles = await safeQuery(kernel, 'FIND File AS ?f WHERE ?f.writeCount > 0 RETURN ?f.path, ?f.writeCount, ?f.readCount ORDER BY ?f.writeCount DESC LIMIT 10');
    const pendingTasks = await safeQuery(kernel, 'FIND Task AS ?t WHERE ?t.status = "pending" RETURN ?t.title, ?t.priority ORDER BY ?t.priority DESC LIMIT 5');

    // Build aggregate stats
    const totalLinesAdded = changes.reduce((sum, c) => sum + (Number(c['?c.linesAdded']) || 0), 0);
    const totalLinesRemoved = changes.reduce((sum, c) => sum + (Number(c['?c.linesRemoved']) || 0), 0);
    const uniqueFiles = new Set(changes.map(c => c['?c.filePath']));

    // Count action types
    const actionCounts: Record<string, number> = {};
    for (const a of actions) {
      const t = String(a['?a.actionType'] || 'unknown');
      actionCounts[t] = (actionCounts[t] || 0) + 1;
    }

    // Build markdown
    let md = `# Devlog — ${targetDate}\n\n`;

    // Summary
    md += `## Summary\n`;
    md += `${sessions.length} session(s), ${changes.length} code change(s) touching ${uniqueFiles.size} file(s). `;
    md += `+${totalLinesAdded} / -${totalLinesRemoved} lines. `;
    md += `${actions.length} total agent actions.\n\n`;

    // Sessions
    if (sessions.length > 0) {
      md += `## Sessions\n`;
      for (const s of sessions) {
        const tid = String(s['?s.trajectoryId'] || '').slice(0, 12);
        const prompts = s['?s.promptCount'] || 0;
        const intent = s['?s.intent'] || 'general';
        md += `- **Session ${tid}** — ${prompts} prompt(s), intent: ${intent}\n`;
      }
      md += '\n';
    }

    // Changes
    if (changes.length > 0) {
      md += `## Changes\n`;
      for (const c of changes) {
        const path = c['?c.filePath'] || 'unknown';
        const added = c['?c.linesAdded'] || 0;
        const removed = c['?c.linesRemoved'] || 0;
        md += `- \`${path}\` — +${added} / -${removed} lines\n`;
      }
      md += '\n';
    }

    // Top files
    if (topFiles.length > 0) {
      md += `## Most Active Files\n`;
      for (const f of topFiles) {
        md += `- \`${f['?f.path']}\` — ${f['?f.writeCount']} write(s), ${f['?f.readCount']} read(s)\n`;
      }
      md += '\n';
    }

    // Activity breakdown
    if (Object.keys(actionCounts).length > 0) {
      md += `## Activity Breakdown\n`;
      for (const [type, count] of Object.entries(actionCounts).sort((a, b) => b[1] - a[1])) {
        md += `- **${type}**: ${count}\n`;
      }
      md += '\n';
    }

    // Decisions
    if (decisions.length > 0) {
      md += `## Decisions Made\n`;
      for (const d of decisions) {
        md += `- **${d['?d.title']}** — ${d['?d.rationale'] || 'No rationale recorded'} (${d['?d.status'] || 'proposed'})\n`;
      }
      md += '\n';
    }

    // Next up
    if (pendingTasks.length > 0) {
      md += `## Next Up\n`;
      for (const t of pendingTasks) {
        md += `- Task: "${t['?t.title']}" (priority: ${t['?t.priority'] || 'unset'})\n`;
      }
      md += '\n';
    }

    // Stats footer
    md += `---\n`;
    md += `*Generated by HQ at ${new Date().toISOString()}*\n`;

    // Write to file
    if (!existsSync(DEVLOG_DIR)) {
      await mkdir(DEVLOG_DIR, { recursive: true });
    }

    const filePath = resolve(DEVLOG_DIR, `${targetDate}.md`);
    await Bun.write(filePath, md);

    console.log(`[HQ Devlog] Generated: .tql/devlog/${targetDate}.md`);
    console.log(`  Sessions: ${sessions.length}`);
    console.log(`  Changes: ${changes.length}`);
    console.log(`  Actions: ${actions.length}`);
  } finally {
    kernel.close();
  }
}

main().catch((err) => {
  console.error('[HQ Devlog] Error:', err);
  process.exit(1);
});
