#!/usr/bin/env bun

/**
 * HQ Auto-Docs Generator — generates structured documentation from the knowledge graph.
 *
 * Outputs: CHANGELOG.md, DECISIONS.md, ROADMAP.md, SPEC.md, CONVENTIONS.md
 * All written to .tql/generated/
 *
 * Usage: bun run hooks/tql-docs.ts [--all | --changelog | --decisions | --roadmap | --spec | --conventions]
 */

import { TrellisKernel } from '../tql/kernel/trellis-kernel.js';
import { createKernel, requireInit, TQL_DIR } from './_kernel.js';
import { resolve } from 'path';
import { existsSync } from 'fs';
import { mkdir } from 'fs/promises';

const GENERATED_DIR = resolve(TQL_DIR, 'generated');

async function safeQuery(kernel: TrellisKernel, q: string): Promise<Record<string, unknown>[]> {
  try {
    const result = kernel.query(q);
    const resolved = result instanceof Promise ? await result : result;
    return resolved.rows;
  } catch {
    return [];
  }
}

// ── Generators ─────────────────────────────────────────────────────────

async function generateChangelog(kernel: TrellisKernel): Promise<string> {
  const changes = await safeQuery(kernel,
    'FIND Change AS ?c RETURN ?c.filePath, ?c.linesAdded, ?c.linesRemoved, ?c.timestamp'
  );

  const commits = await safeQuery(kernel,
    'FIND Commit AS ?c RETURN ?c.hash, ?c.message, ?c.timestamp'
  );

  let md = `# Changelog\n\nAll notable changes to this project are tracked automatically by HQ.\n\n`;

  if (commits.length > 0) {
    md += `## Commits\n\n`;
    for (const c of commits) {
      md += `- **${c['?c.hash']}** — ${c['?c.message'] || 'No message'} (${c['?c.timestamp'] || ''})\n`;
    }
    md += '\n';
  }

  if (changes.length > 0) {
    md += `## Code Changes\n\n`;
    md += `| File | Lines Added | Lines Removed | Timestamp |\n`;
    md += `|------|------------|--------------|----------|\n`;
    for (const c of changes) {
      md += `| \`${c['?c.filePath']}\` | +${c['?c.linesAdded'] || 0} | -${c['?c.linesRemoved'] || 0} | ${c['?c.timestamp'] || ''} |\n`;
    }
    md += '\n';
  }

  if (changes.length === 0 && commits.length === 0) {
    md += `*No changes tracked yet.*\n`;
  }

  md += `\n---\n*Auto-generated by HQ at ${new Date().toISOString()}*\n`;
  return md;
}

async function generateDecisions(kernel: TrellisKernel): Promise<string> {
  const decisions = await safeQuery(kernel,
    'FIND Decision AS ?d RETURN ?d.title, ?d.rationale, ?d.alternatives, ?d.status'
  );

  let md = `# Architecture Decision Records\n\nDecisions tracked by HQ from Cascade sessions.\n\n`;

  if (decisions.length === 0) {
    md += `*No decisions recorded yet. Decisions are auto-extracted from Cascade responses.*\n`;
  } else {
    for (let i = 0; i < decisions.length; i++) {
      const d = decisions[i]!;
      md += `## ADR-${String(i + 1).padStart(3, '0')}: ${d['?d.title'] || 'Untitled'}\n\n`;
      md += `- **Status**: ${d['?d.status'] || 'proposed'}\n`;
      md += `- **Rationale**: ${d['?d.rationale'] || 'Not recorded'}\n`;
      md += `- **Alternatives considered**: ${d['?d.alternatives'] || 'None recorded'}\n\n`;
    }
  }

  md += `\n---\n*Auto-generated by HQ at ${new Date().toISOString()}*\n`;
  return md;
}

async function generateRoadmap(kernel: TrellisKernel): Promise<string> {
  const milestones = await safeQuery(kernel,
    'FIND Milestone AS ?m RETURN ?m.title, ?m.targetDate, ?m.status, ?m.completionPct'
  );

  const features = await safeQuery(kernel,
    'FIND Feature AS ?f RETURN ?f.title, ?f.status, ?f.priority, ?f.scope'
  );

  let md = `# Roadmap\n\nProject roadmap generated from HQ knowledge graph.\n\n`;

  if (milestones.length > 0) {
    for (const m of milestones) {
      const pct = Number(m['?m.completionPct'] || 0);
      const filled = Math.round(pct * 10);
      const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);
      md += `## ${m['?m.title'] || 'Untitled'} [${bar}] ${Math.round(pct * 100)}%`;
      if (m['?m.targetDate']) md += ` — Target: ${m['?m.targetDate']}`;
      md += '\n\n';
    }
  }

  if (features.length > 0) {
    md += `## Features\n\n`;
    for (const f of features) {
      const status = f['?f.status'] || 'backlog';
      const check = status === 'done' ? 'x' : ' ';
      md += `- [${check}] **${f['?f.title'] || 'Untitled'}** (${status}) — scope: ${f['?f.scope'] || 'unscoped'}\n`;
    }
    md += '\n';
  }

  if (milestones.length === 0 && features.length === 0) {
    md += `*No milestones or features defined yet.*\n`;
  }

  md += `\n---\n*Auto-generated by HQ at ${new Date().toISOString()}*\n`;
  return md;
}

async function generateSpec(kernel: TrellisKernel): Promise<string> {
  const features = await safeQuery(kernel,
    'FIND Feature AS ?f RETURN ?f.title, ?f.description, ?f.status, ?f.priority, ?f.scope'
  );

  const deps = await safeQuery(kernel,
    'FIND Dependency AS ?d RETURN ?d.name, ?d.version, ?d.depType'
  );

  let md = `# Project Specification\n\nCanonical spec derived from HQ knowledge graph.\n\n`;

  // Group features by scope
  const byScope: Record<string, typeof features> = {};
  for (const f of features) {
    const scope = String(f['?f.scope'] || 'general');
    if (!byScope[scope]) byScope[scope] = [];
    byScope[scope]!.push(f);
  }

  if (Object.keys(byScope).length > 0) {
    md += `## Features\n\n`;
    for (const [scope, scopeFeatures] of Object.entries(byScope)) {
      md += `### ${scope.charAt(0).toUpperCase() + scope.slice(1)}\n\n`;
      for (const f of scopeFeatures) {
        md += `- **${f['?f.title'] || 'Untitled'}** (${f['?f.status'] || 'backlog'}, priority: ${f['?f.priority'] || 'unset'})\n`;
        if (f['?f.description']) md += `  ${f['?f.description']}\n`;
      }
      md += '\n';
    }
  }

  if (deps.length > 0) {
    md += `## Dependencies\n\n`;
    md += `| Package | Version | Type |\n`;
    md += `|---------|---------|------|\n`;
    for (const d of deps) {
      md += `| ${d['?d.name']} | ${d['?d.version'] || '-'} | ${d['?d.depType'] || '-'} |\n`;
    }
    md += '\n';
  }

  if (features.length === 0 && deps.length === 0) {
    md += `*No features or dependencies tracked yet.*\n`;
  }

  md += `\n---\n*Auto-generated by HQ at ${new Date().toISOString()}*\n`;
  return md;
}

async function generateConventions(kernel: TrellisKernel): Promise<string> {
  const conventions = await safeQuery(kernel,
    'FIND Convention AS ?c RETURN ?c.name, ?c.rule, ?c.examples'
  );

  let md = `# Coding Conventions\n\nProject conventions tracked by HQ.\n\n`;

  if (conventions.length === 0) {
    md += `*No conventions defined yet. Add them via the TQL kernel or through Cascade sessions.*\n`;
  } else {
    for (const c of conventions) {
      md += `## ${c['?c.name'] || 'Unnamed'}\n\n`;
      md += `**Rule**: ${c['?c.rule'] || 'No rule defined'}\n\n`;
      if (c['?c.examples']) {
        md += `**Examples**:\n${c['?c.examples']}\n\n`;
      }
    }
  }

  md += `\n---\n*Auto-generated by HQ at ${new Date().toISOString()}*\n`;
  return md;
}

// ── Main ───────────────────────────────────────────────────────────────

async function main() {
  const flag = process.argv[2] || '--all';

  requireInit();

  if (!existsSync(GENERATED_DIR)) {
    await mkdir(GENERATED_DIR, { recursive: true });
  }

  const kernel = createKernel();

  const generators: Record<string, { fn: (k: TrellisKernel) => Promise<string>; file: string }> = {
    '--changelog': { fn: generateChangelog, file: 'CHANGELOG.md' },
    '--decisions': { fn: generateDecisions, file: 'DECISIONS.md' },
    '--roadmap': { fn: generateRoadmap, file: 'ROADMAP.md' },
    '--spec': { fn: generateSpec, file: 'SPEC.md' },
    '--conventions': { fn: generateConventions, file: 'CONVENTIONS.md' },
  };

  try {
    const toGenerate = flag === '--all'
      ? Object.entries(generators)
      : generators[flag]
        ? [[flag, generators[flag]!] as const]
        : [];

    if (toGenerate.length === 0) {
      console.error(`[HQ Docs] Unknown flag: ${flag}. Use --all, --changelog, --decisions, --roadmap, --spec, or --conventions`);
      process.exit(1);
    }

    for (const [_key, gen] of toGenerate) {
      const content = await gen.fn(kernel);
      const filePath = resolve(GENERATED_DIR, gen.file);
      await Bun.write(filePath, content);
      console.log(`[HQ Docs] Generated: .tql/generated/${gen.file}`);
    }
  } finally {
    kernel.close();
  }
}

main().catch((err) => {
  console.error('[HQ Docs] Error:', err);
  process.exit(1);
});
