export { default as Page } from './Page.vue'
export { default as PageDashboard } from './PageDashboard.vue'
export { default as PageSkeleton } from './PageSkeleton.vue'
export { default as PageSplit } from './PageSplit.vue'
export { default as PageTable } from './PageTable.vue'
export { default as LayoutCard } from './LayoutCard.vue'
export { default as BackButton } from './BackButton.vue'
export { default as IconRail } from './IconRail.vue'
