/**
 * @deprecated This file is a backward-compatibility re-export shim.
 * The canonical type system is now `~/types/entity`.
 * All types, factories, UI options, and type guards are re-exported from there.
 * New code should import directly from `~/types/entity`.
 */

// ── Types ──
export type {
  CalendarItemType,
  CalendarItemBase,
  CalendarItem,
  Entity,
  EntityType,
  EntityItemBase,
  Priority,
  Urgency,
  TaskStatus,
  EventType,
  EventSubtype,
  TripStatus,
  PaymentStatus,
  TransportMode,
  SprintStatus,
  BudgetStatus,
  ProjectStatus,
  DefaultCategory,
  Reminder,
  RecurrenceRule,
  ChecklistItem,
  Attendee,
  FormulaField,
  Attachment,
  SocialLink,
  FileReference,
  EntityReference,
  BookmarkReference,
  Reference,
  FileType,
  TaskItem,
  EventItem,
  TripItem,
  PaymentItem,
  PaymentChannel,
  PaymentDirection,
  TransactionCounterparty,
  PaymentLineItem,
  NoteItem,
  SlideDeckItem,
  FileItem,
  BookmarkItem,
  PersonItem,
  OrganizationItem,
  ProjectItem,
  SprintItem,
  MilestoneItem,
  GoalItem,
  BudgetItem,
  PageItem,
  TemplateItem,
} from '~/types/entity'

// ── Values (factories, options, guards) ──
export {
  DEFAULT_CATEGORIES,
  CALENDAR_ITEM_TYPES,
  ENTITY_TYPE_OPTIONS,
  PRIORITY_OPTIONS,
  URGENCY_OPTIONS,
  TASK_STATUS_OPTIONS,
  EVENT_TYPE_OPTIONS,
  TRIP_STATUS_OPTIONS,
  TRANSPORT_OPTIONS,
  PAYMENT_STATUS_OPTIONS,
  SPRINT_STATUS_OPTIONS,
  BUDGET_STATUS_OPTIONS,
  CURRENCY_OPTIONS,
  CATEGORY_OPTIONS,
  createDefaultBase,
  createDefaultTask,
  createDefaultEvent,
  createDefaultTrip,
  createDefaultPayment,
  createDefaultNote,
  createDefaultSlideDeck,
  createDefaultBookmark,
  createDefaultPerson,
  createDefaultOrganization,
  createDefaultFile,
  createDefaultSprint,
  createDefaultMilestone,
  createDefaultGoal,
  createDefaultBudget,
  createDefaultProject,
  createDefaultItem,
  isTask,
  isEvent,
  isTrip,
  isPayment,
  isNote,
  isSlideDeck,
  isFile,
  isBookmark,
  isPerson,
  isOrganization,
  isProject,
  isSprint,
  isMilestone,
  isGoal,
  isBudget,
  isFileReference,
  isEntityReference,
  isBookmarkReference,
} from '~/types/entity'
